### ISSUE TITLE
Error: could not find function "%>>%"

### ISSUE THREAD

**Issue by hack-r** [rich-iannone/DiagrammeR#100]
In R 3.2.0 on Windows, running 

"An Example with Data from the nycflights13 Package" 

from 

https://github.com/rich-iannone/DiagrammeR

leads to

> graphviz_graph(nodes_df = nodes_df, edges_df = edges_df,
+                graph_attrs = graph_attrs, node_attrs = node_attrs,
+                edge_attrs = edge_attrs, directed = TRUE) %>>%
+   graphviz_render(width = 1200, height = 800)

Error: could not find function "%>>%"

http://pastebin.com/Czd06Ais

**Comment by hack-r** [comment]
Someone on StackOverflow identified the problem/solution -- this function is from a package called `pipeR` which needs to be loaded in the example code

**Comment by rich-iannone** [comment]
I'm going to try to make some of the examples a bit more standalone and have a library statement for pipeR. That might cause less confusion going forward.
