### ISSUE TITLE
Using text connections in R-C interface for reading agwrite() output

### ISSUE THREAD

**Issue by taylorruss** [rich-iannone/DiagrammeR#102]
Fantastic package. 

Would you be able to suggest a way for passing graphviz output created in an external package?
package -> write_to_file
Diagrammer(file)

package -> write_to_textConnection
Diagrammer(connection)

The second option makes more sense.  I am just not clear about how textConnection() work involving R-C interface.

thanks,
TR

**Comment by timelyportfolio** [comment]
Happy to help, but I'm not sure I understand.  Could you clarify with some more details?  Thanks.  I noticed in #103  that you are pairing with `Rgraphviz`.  Is this related?

**Comment by taylorruss** [comment]
Impressed with inference making:) The two are indeed related, and yes, I was trying to eliminate a tempfile that is actually written to the hard drive. It seems something like a pipe() that stores the text in a buffer should be able to eliminate an actual file.  But, I am not familiar with R-connections or C pipes!  Thanks again.
BTW, the new website is fabulous.
