### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by cboettig** [rich-iannone/DiagrammeR#104]
Can you bump the package version on Github so that it isn't the same as the one on CRAN?  (e.g. Rstudio uses the convention of adding a `.999` or such to the end of the Github versions so that CRAN versions can still follow the same semantic versioning).

Context: I've created a [drat](https://github.com/eddelbuettel/drat) repo that contains DiagrammeR to facilitate installing (in particular, I hit API rate limits when installing everything on `install_github`, and it doesn't work with `update.packages`) to let me install the latest Github versions of a suite of awesome packages like this one.  Unfortunately `install.packages` can't tell which one to pick and installs the CRAN version.

**Comment by rich-iannone** [comment]
@cboettig I just increased the version number to 0.7 and included some release notes. I marked the release as a development one, please let me know if that's okay. And, thank for associating this package with awesomeness!

**Comment by cboettig** [comment]
Cool, thanks! that works for me.  (Once 0.7 is on CRAN though it would be nice if you bump the Github version again so R can tell they aren't the same).

**Comment by rich-iannone** [comment]
@cboettig Great! That will be the new habit for me (increasing the dev version after a CRAN submission).
