### ISSUE TITLE
unexpected error on simple example?

### ISSUE THREAD

**Issue by cboettig** [rich-iannone/DiagrammeR#105]
No idea what's going wrong here, but this simple example throws an error when exporting to svg.  otherwise it runs fine:

```r
n <- c("a", "b", "c", "d")
nodes <- create_nodes(nodes = n)
edges <- create_edges(edge_from = n, 
                      edge_to = c(n[-1], n[1]))
graph <- create_graph(nodes = nodes, edges = edges, 
                      graph_attrs = c(layout = "circo"))

out <- render_graph(graph, output = "SVG")
```

error:

```
Warning: syntax error in line 3 near ']'
13
Error: abort() at Error
    at Error (<anonymous>)
    at bb (<anonymous>:9:172)
    at aa (<anonymous>:34:259)
    at Array.GG (<anonymous>:1245:30917)
    at sx (<anonymous>:1237:24178)
    at Wx (<anonymous>:1237:36967)
    at IA (<anonymous>:1209:36701)
    at Pz (<anonymous>:1209:14637)
    at ld (<anonymous>:1201:850)
    at qb (<anonymous>:3:8)

```

(could have sworn this was working a few days ago)

**Comment by rich-iannone** [comment]
@cboettig try this:
```
n <- c("a", "b", "c", "d")
nodes <- create_nodes(nodes = n)
edges <- create_edges(edge_from = n, 
                      edge_to = c(n[-1], n[1]))
graph <- create_graph(nodes = nodes, edges = edges, 
                      graph_attrs = c("layout = circo"))

out <- render_graph(graph, output = "SVG")
```
So, the attributes should be given as a vector of character values and not as a named vector. I realize that this is poor implementation as it's not natural in R, so, I'm going to address this so both ways (named vectors, strings) are accepted.

**Comment by cboettig** [comment]
ah, thanks! my mistake.  yup, named vectors would be nice since it makes it easier to support defining attributes as variables too.

**Comment by rich-iannone** [comment]
Ah yes! Okay, I'll make this happen soon. Also, if you find any ways to make the package better/nicer, feel free to send a PR. (Always, looking for ideas too.)
