### ISSUE TITLE
how to get a line break for text inside the diagram objects

### ISSUE THREAD

**Issue by benmarwick** [rich-iannone/DiagrammeR#106]
It's wonderful to be able to make these kind of charts within R, thanks for your work on this package. 

I'd like to put some line breaks in the text so that the shapes are not so big, for example, the circles in the example below. If I use `\n` it breaks. 

```
diagram <- "
graph LR
A[Zip file]-->B[R functions]
A[Zip file]-->C[manual for R functions]
A[Zip file]-->D[vingettes]
D[vingettes]-->E[data]
D[vingettes]-->F[figures]
D[vingettes]-->G((R markdown file))
A[Zip file]-->H((README file))
"

mermaid(diagram)
```

![rplot](https://cloud.githubusercontent.com/assets/1262179/7692162/c4958c1a-fd75-11e4-8c5b-8855f531c640.png)

For example 
```
diagram <- "
graph LR
A[Zip file]-->B[R functions]
A[Zip file]-->C[manual for R functions]
A[Zip file]-->D[vingettes]
D[vingettes]-->E[data]
D[vingettes]-->F[figures]
D[vingettes]-->G((R \nmarkdown \nfile))
A[Zip file]-->H((README file))
"

mermaid(diagram)
```

gives 
```
parse error with 
graph LR
A[Zip file]-->B[R functions]
A[Zip file]-->C[manual for R functions]
A[Zip file]-->D[vingettes]
D[vingettes]-->E[data]
D[vingettes]-->F[figures]
D[vingettes]-->G((R 
markdown 
file))
A[Zip file]-->H((README file))

undefined is not an object (evaluating 'w[0]')
```

**Comment by timelyportfolio** [comment]
Try `<br>` instead of `\n`.  I believe that still  works.

**Comment by benmarwick** [comment]
Thanks, that does the trick.

**Comment by riinuots** [comment]
The only thing that works for me is `\\n`.

Thanks so much for an amazing package!

**Comment by Asc2011** [comment]
hi, 
sry to say but using the Atom-markdown-enhanced package neither `\\n` nor `<br>` ?
any alternatives i could try ?

**Comment by zippy78753** [comment]
What worked for me: just put multiple comments in for the same state.  For instance:
`
stateDiagram
    State1 : Line 1
    State1 : Line 2
`

**Comment by bjourne** [comment]
For me, embedding \n worked just fine: `box_name: "bla\nbla\nbla"`
