### ISSUE TITLE
How to put parentheses within mermaid diagram objects

### ISSUE THREAD

**Issue by benmarwick** [rich-iannone/DiagrammeR#107]
How can I get the text of an object to read something like `R (functions)`? I've tried [unicode and HTML](http://en.wikipedia.org/wiki/Bracket#Encoding_in_digital_media) but can't seem to get it.

```
diagram <- "
graph LR
A[Zip file]-->B[R functions]
A[Zip file]-->C[manual<br>for R<br>functions]
A[Zip file]-->D[vingettes]
D[vingettes]-->E[data]
D[vingettes]-->F[figures]
D[vingettes]-->G((R<br>markdown<br>file))
A[Zip file]-->H((README<br>file))
"

mermaid(diagram)
```

![rplot](https://cloud.githubusercontent.com/assets/1262179/7695065/dd69f5b8-fd9e-11e4-872d-f7ab0c056b57.png)

If I put a `(` in any of the text in the square brackets I get `undefined is not an object (evaluating 'w[0]')`. I can't see anything obviously helpful in the [mermaid docs](http://knsv.github.io/mermaid/).

Also, is it possible to center the text in the object? Thanks again.

**Comment by shrektan** [comment]
@benmarwick really? I think write like this `"abc(abc)abc"` should be ok. Try the code below:

```
diagram <- "
graph LR
A[Zip file]-->B[\"R (abc) functions\"]
A[Zip file]-->C[manual<br>for R<br>functions]
A[Zip file]-->D[vingettes]
D[vingettes]-->E[data]
D[vingettes]-->F[figures]
D[vingettes]-->G((R<br>markdown<br>file))
A[Zip file]-->H((README<br>file))

style B fill:red
"

DiagrammeR::mermaid(diagram)
```

**Comment by joshgraymd** [comment]
The second question from @benmarwick re: centering text has not been addressed.
