### ISSUE TITLE
[enhancement] add binding to drill down

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#110]
Hi,

Firstly, thanks for the continued great work.

I have been thinking of this use case that could have many applications - on Shiny, enable nodes to explode and maybe refresh the current diagram:
have a igraph object as the source data, plot a subgraph from the object to render a diagram you want to show initially.
when user double click a node in the diagram, shiny pick up the node name and send the query to igraph, to find out it's parents or child and rebuild another subgraph and refresh the current diagram.
Also, there should be some roll back mechanism to drill up to original diagram/subgraph.

I know how to traverse the nodes in igraph, but I am now very familiar with R shiny bindings :(

just an idea, if you know how to get the bindings work in diagrammeR, it would be easy to implement.

**Comment by rich-iannone** [comment]
I'm thinking of using something like `vis.js` for this because I believe there is interactivity built in for this sort of this. So, I'm just at the beginning of exploring how to do this.

**Comment by happyshows** [comment]
Thanks, I found something interesting already being built in visNetwork package, but interfacing or integration between each package would be super nice...

https://github.com/DataKnowledge/visNetwork

**Comment by abresler** [comment]
Sigma.js maybe another always helps to have palantir backing it considering
their love and dependency on node graphs

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​
