### ISSUE TITLE
suggestions to plot decision tree?

### ISSUE THREAD

**Issue by vnijs** [rich-iannone/DiagrammeR#116]
I added an interface in Radiant to [data.tree](https://github.com/gluc/data.tree) for decision trees. See link below (Decide > Decision tree) for an example. Click the `Calculate` button to see the output. 

http://vnijs.rady.ucsd.edu:3838/quant/?SSUID=c4e9c5f289

I played around with the plotting code @gluc provided in his presentation at UseR (see link to image below). The labels are the main issue i see (code linked below). I'm curious if you have any suggestions on which tools might work best to accommodate (longish) labels and (potentially) many terminal nodes. Being able to collapse (parts) of the tree would also be nice. I actually already like the simple text output shown in Radiant now so maybe even something like @timelyportfolio's list viewer could work.

https://github.com/vnijs/radiant/blob/master/R/dtree.R#L113-L155

Link to image:
https://www.dropbox.com/s/ueqp3fbpv02ubax/dtree_plot.png?dl=0

See also discussion here: https://github.com/gluc/data.tree/issues/19

**Comment by vnijs** [comment]
Made some progress with mermaid in Diagrammer images below. Code also below. 

http://vnijs.github.io/radiant/quant/dtree/mermaid-dtree-init.html
http://vnijs.github.io/radiant/quant/dtree/mermaid-dtree-final.html

Three questions:
1. Is it possible to remove the gray back-ground for the labels?
2. How to include ( ) in the labels. I tried putting them inside quotes as suggested in discussions in mermaid.js issues but that caused a parse error
3. Final step will be to go from this [list of two data.tree objects](https://www.dropbox.com/s/8kr8pb95ntuc82z/quant_job.rda?dl=0) to the two graphs linked above. Is it best-practice to [create the string for mermaid using paste](http://www.rdocumentation.org/packages/DiagrammeR/functions/mermaid) or to create a [specialized data.frame](http://rich-iannone.github.io/DiagrammeR/graphs.html)? Or are the specialized data.frames only for graphviz?

`
library(DiagrammeR); library(magrittr)

mermaid("
graph LR
        A[ ] --> |Accept John's Offer| B[$12,000]
        A --> |Reject John's Offer |C(( ))
        C --> |Offer from Vanessa 0.6| D[ ]
        D --> |Accept Vanessa's Offer| E[$14,000]
        D --> |Reject Vanessa's Offer| F(( ))
        C --> |No Offer from Vanessa 0.4| G(( ))
        G --> |Salary 1 0.05| H[$21,600]
        G --> |Salary 2 0.25| I[$16,800]
        G --> |Salary 3 0.40| J[$12,800]
        G --> |Salary 4 0.25| K[$6,000]
        G --> |Salary 5 0.05| L[$0]

        F --> |Salary 1 0.05| M[$21,600]
        F --> |Salary 2 0.25| N[$16,800]
        F --> |Salary 3 0.40| O[$12,800]
        F --> |Salary 4 0.25| P[$6,000]
        F --> |Salary 5 0.05| Q[$0]

        classDef default fill:none, bg:none, stroke-width:0px;
 	      classDef decision fill:#9f6,stroke:#333,stroke-width:1px;
 	      classDef chance fill:red,stroke:#333,stroke-width:1px;
	 	    class A,D decision;
	 	    class C,G,F chance;
")

mermaid("
graph LR
        A[$13,032] --> |Accept John's Offer| B[$12,000]
        A ==> |Reject John's Offer |C(($13,032))
        C --> |Offer from Vanessa 0.6| D[$14,000]
        D ==> |Accept Vanessa's Offer| E[$14,000]
        D --> |Reject Vanessa's Offer| F(($11,580))
        C --> |No Offer from Vanessa 0.4| G(($11,580))
        G --> |Salary 1 0.05| H[$21,600]
        G --> |Salary 2 0.25| I[$16,800]
        G --> |Salary 3 0.40| J[$12,800]
        G --> |Salary 4 0.25| K[$6,000]
        G --> |Salary 5 0.05| L[$0]

        F --> |Salary 1 0.05| M[$21,600]
        F --> |Salary 2 0.25| N[$16,800]
        F --> |Salary 3 0.40| O[$12,800]
        F --> |Salary 4 0.25| P[$6,000]
        F --> |Salary 5 0.05| Q[$0]

        classDef default fill:none, bg:none, stroke-width:0px;
        classDef decision fill:#9f6,stroke:#333,stroke-width:1px;
        classDef chance fill:red,stroke:#333,stroke-width:1px;
        class A,D decision;
        class C,G,F chance;
        ")
`

**Comment by rich-iannone** [comment]
@vnijs sorry for the delay in getting to this, but, really great work! I think the parenthesis issue and the setting of the background color might be solved in newer versions of mermaid. So far, the specialized data frames are only for Graphviz. I do plan to implement mermaid as a render option for that.

I'd encourage you to try using the graph constructing functions with Graphviz as the render option. It is highly configurable and it definitely does hierarchical left-to-right layouts while avoiding some of the issues you've faced with mermaid.

Finally, if you'd like to modify the code to better suit your implementation, feel free to send a pull request. The mermaid part of DiagrammeR hasn't gotten as many improvements lately.

**Comment by vnijs** [comment]
@rich-iannone Thanks for the suggestions. I actually just finished an initial implementation using DiagrammeR and mermaid :) See link below (press the `Calculate` button in Decide > Decision trees ? Plot). One thing I really like about mermaid is the kinked arrows that work quite well with long(ish) labels.

http://vnijs.rady.ucsd.edu:3838/quant/?SSUID=a3a383df34

The main thing I haven't been able to figure out is how to download a diagrammer plot from inside a Shiny app (e.g., to pdf). Any examples?

I would, of course, be interested to know if the graphs could look even nicer with GraphViz. In case you are interested, the code for the decision trees is here: 

https://github.com/vnijs/radiant/blob/master/R/dtree.R

Most of this code is based on this gist created by @gluc:

https://gist.github.com/gluc/79ef7a0e747f217ca45e

**Comment by vnijs** [comment]
An issue (possibly) related to saving plots is getting the plot in a knitry document. When I tried knitting the package vignette with the command below there are not DiagrammeR plots show. Am I missing something?

knit2html("~/Desktop/diagrammer.Rmd")

**Comment by vnijs** [comment]
FYI I found a work-around to save a mermaid graph to pdf from Shiny using the browsers print dialog. You need and actionButton or actionLink (e.g., below).

```r
actionLink("dtree_save_plot", "", class = "fa fa-download alignright", onclick = "window.print();"),
```

```css
/* print option relevant to print a decision tree to pdf */
/* based on http://stackoverflow.com/a/2618980/1974918 */
@media print {
  #dtree * {
    visibility: hidden;
  }
  #dtree_plot, #dtree_plot * {
    visibility: visible;
  }
  #dtree_plot {
    position: absolute;
    left: 0;
    top: 0;
  }
}

# css to change edge label background
.mermaid g .edgeLabel span { background: white !important; }
```
