### ISSUE TITLE
DiagrammeROutput example

### ISSUE THREAD

**Issue by kmezhoud** [rich-iannone/DiagrammeR#121]
Hi,
I am seeking for example that uses DiagrammeROutput function.
Thanks
Karim

**Comment by achubaty** [comment]
Hi @kmezhoud, I'm not sure if this is the place for help requests, so I'll assume you're asking for an example to be added to the documentation. Here is a quick example:

```r
# server.R
library(DiagrammeR)

shinyServer(
  function(input, output) {
    output$diagram <- renderDiagrammeR({
      d <- paste(
        paste0("graph ", input$orientation),
        "A[A]-->B[B]",
        "B-->C[C]",
        "C-->D[D]",
        "A-->D",
        "B-->E[E]",
        sep = "\n")
      mermaid(d)
    })
  }
)
```

```r
# ui.R

shinyUI(fluidPage(
  titlePanel("DiagrammeR + shiny"),

  sidebarLayout(
    sidebarPanel(
      helpText("Example showing DiagrammeR output in a shiny app."),

      selectInput("orientation",
                  label = "Select diagram orientation",
                  choices = c("BT", "TB", "LR", "RL"),
                  selected = "TB")
    ),

    mainPanel(DiagrammeROutput("diagram"))
  )
))
```

@rich-iannone, if this example is useful, feel free to use this as you see fit

**Comment by kmezhoud** [comment]
@achubaty Many Thanks, I think the doc lacks this example.
I found a solution with grVis function. Now I am asking the question:
@rich-iannone  why DiagrammeR uses two functions grVis and mermaid that may have the same output? or what is the difference?
Thanks

**Comment by manalirupji** [comment]
How can one pass and reactive input (selected by the user) to the diagrammeR? For example, I want to create a flowchart for an multi step process based on user input. Some of the reactive objects need to be included in the flowchart 

 d <- paste(
        paste0("graph ", input$orientation),
        "A[#Samples input$n]-->B[B]",
        "B-->C[C]",
        "C-->D[D]",
        "A-->D",
        "B-->E[E]",
        sep = "\n")

This throws errors as I am unsure of the format for passing the reactive values inside the flowchart. Is that possible?

**Comment by achubaty** [comment]
@manalirupji without a reproducible example, I can only guess at what you are trying to achieve. What aspect of the output do you want to be reactive/user-selectable?

My example above shows how to pass a reactive input (that's the `input$orientation` part).

Your `paste*` command needs to use valid syntax. You have specified a node `#Samples input$n`, which is invalid: variables (reactives) should not be in quotes; variables cannot have spaces in them; `#` is R's comment symbol. Additionally, `input$n` needs to be a character type.

**Comment by manalirupji** [comment]
Thanks, I apologize for the poor documentation in the question. Please see below a snippet of what I would like to achieve,

library(DiagrammeR)


# Shiny app
server <- function(input, output) {
    
  output$diagram <- renderDiagrammeR({
      d <- paste(
        paste0("graph ", "TB"),
        "A[Input Data <br/> No. of Genes:] --> B[Filtering Parameters]",
        "B --> C{A Rhombus}",
        "C --> D[Rectangle One]",
        "C --> E[Rectangle Two]",
        sep = "\n")
      mermaid(d)
    })
  }


ui <- fluidPage(
  titlePanel("DiagrammeR + shiny"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Example showing DiagrammeR output in a shiny app."),
      
      selectInput("ngenes",
                  label = "Select n genes",
                  choices = c("100", "200", "300", "400"),
                  selected = "100")
    ),
    
    mainPanel(DiagrammeROutput("diagram"))
  )
)

shinyApp(ui = ui, server = server)

I would like to incorporate the number of genes selected by the user in the ui side of side into the rectangular box in the line  "A[Input Data <br/> No. of Genes: ] --> B[Filtering Parameters]"

**Comment by achubaty** [comment]
The solution is the same as in my example above:

```r
library(DiagrammeR)
library(shiny)

server <- function(input, output) {
  output$diagram <- renderDiagrammeR({
    d <- paste(
      paste0("graph ", "TB"),
      paste0("A[Input Data No. of Genes: ", input$ngenes, "] --> B[Filtering Parameters]"),
      "B --> C{A Rhombus}",
      "C --> D[Rectangle One]",
      "C --> E[Rectangle Two]",
      sep = "\n")
    mermaid(d)
  })
}

ui <- fluidPage(
  titlePanel("DiagrammeR + shiny"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Example showing DiagrammeR output in a shiny app."),
      
      selectInput("ngenes",
                  label = "Select n genes",
                  choices = c("100", "200", "300", "400"),
                  selected = "100")
    ),
    
    mainPanel(DiagrammeROutput("diagram"))
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by manalirupji** [comment]
Thanks so much for your help! it works well!
