### ISSUE TITLE
Shiny: I can't display Node with 300 interaction. DiagrammeR has limited network size?

### ISSUE THREAD

**Issue by kmezhoud** [rich-iannone/DiagrammeR#122]
Hi,
In biology, some important protein (cancer biomarker) can get more than 300 interactions as TP53. 
In the following session, when I use proteins ("MYO6", "DKK3") with a few interactions (less than 100) I can display network in shiny App. But with I use TP53, I can not.
How can I set network (edge length, node size, layouts) to save space in grViz function?

Please Here a session with necessary code: 
https://drive.google.com/file/d/0B9NOY9eukkEeMXQ1eVFRZDVLYjg/view?usp=sharing

save file as bigNet.RData

load("~/Desktop/bigNet.RData")
GeneList <- ("MYO6", "DKK3")
shinyApp(ui = ui, server = server ## that works

##Test with TP53
GeneList <- "TP53"
shinyApp(ui = ui, server = server)  ## error

Thanks
Karim

**Comment by kmezhoud** [comment]
Hi, 
I can't identify the mistake? why this does not work?

server <- function(input, output){
output$diagram <- renderGrViz({
grViz('
digraph{
AKT1 ->   AKT2 [dir = forward,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
AKT1 ->   AKT3 [ dir = none,   reaction arrowsize=0.5,    penwidth= 1 ] ;
AKT1 -> PIK3CA [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ];
AKT1 -> PIK3R1 [ dir = back, arrowtail = normal,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
EGFR ->  ERBB2 [  dir = none, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
EGFR ->   HRAS [   dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
EGFR ->   KRAS [  dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ; 
EGFR ->    MET [   dir = none,    style = dashed, arrowsize=0.5, penwidth= 0.61 ] ;
EGFR ->    NF1 [dir = none, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ; 
EGFR ->   NRAS [  dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
EGFR -> PIK3CA [ dir=both,arrowhead = tee, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
EGFR -> PIK3R1 [ dir=both,arrowhead = tee, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
EGFR ->  SPRY2 [ dir=both,arrowtail = tee, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
ERBB2 ->   KRAS [  dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
ERBB2 ->    NF1 [ dir = none, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
ERBB2 ->   NRAS [dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
  ERBB2 -> PIK3CA [ dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
  ERBB2 -> PIK3R1 [ dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
  ERBB2 ->  SPRY2 [     dir= back, arrowtail = tee,     arrowhead=tee, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS ->   KRAS [  dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS ->    MET [ dir = back, arrowtail = normal,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS ->    NF1 [  dir = none,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS ->   NRAS [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS -> PDGFRA [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS -> PIK3CA [ dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS -> PIK3R1 [       dir=both,arrowhead = tee, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
   HRAS ->  SPRY2 [ dir = none,    style = dashed, arrowsize=0.5, penwidth= 0.61 ] ;
   KRAS -> PDGFRA [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   KRAS -> PIK3CA [   dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
   KRAS -> PIK3R1 [       dir=both,arrowhead = tee, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
    MET ->   NRAS [    dir = forward,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
    MET -> PIK3CA [   dir = forward,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
    MET -> PIK3R1 [ dir = forward,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
    NF1 ->   NRAS [ dir = none,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
    NF1 -> PIK3CA [ dir = none, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
   NRAS -> PDGFRA [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   NRAS -> PIK3CA [                  dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
   NRAS -> PIK3R1 [       dir=both,arrowhead = tee, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
 PDGFRA -> PIK3CA [                  dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
 PDGFRA -> PIK3R1 [                  dir = forward, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
 PIK3CA -> PIK3R1 [                     dir = none, arrowhead=diamond, arrowsize=0.5,    penwidth= 1 ] ;
   AKT1 ->   EGFR [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT1 ->  ERBB2 [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT1 ->    NF1 [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT1 ->   PTEN [     dir= back, arrowtail = tee,     arrowhead=tee, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 ->   AKT3 [                     dir = none,    style = dashed, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 ->   EGFR [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 ->  ERBB2 [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 ->    NF1 [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 -> PIK3CA [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 -> PIK3R1 [ dir = back, arrowtail = normal,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
   AKT2 ->   PTEN [     dir= back, arrowtail = tee,     arrowhead=tee, arrowsize=0.5,    penwidth= 1 ] ;
   AKT3 ->   EGFR [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT3 ->  ERBB2 [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT3 ->    NF1 [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT3 -> PIK3CA [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   AKT3 -> PIK3R1 [ dir = back, arrowtail = normal,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
   AKT3 ->   PTEN [     dir= back, arrowtail = tee,     arrowhead=tee, arrowsize=0.5,    penwidth= 1 ] ;
  ERBB2 ->   HRAS [                  dir = forward,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
   KRAS ->    MET [ dir = back, arrowtail = normal,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
   KRAS ->    NF1 [                     dir = none,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
   KRAS ->   NRAS [ dir = back, arrowtail = normal,     arrowhead=dot, arrowsize=0.5,    penwidth= 1 ] ;
 PIK3CA ->   PTEN [       dir=both,arrowtail = tee,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ] ;
 PIK3CA ->  SPRY2 [ dir = forward, arrowhead = tee,     arrowhead=tee, arrowsize=0.5,    penwidth= 1 ] ;
 PIK3R1 ->   PTEN [       dir=both,arrowtail = tee,  arrowhead=normal, arrowsize=0.5,    penwidth= 1 ]}
    
   ')
  })
  
}

ui <- shinyUI(
  
  grVizOutput('diagram')
)

shinyApp(ui = ui, server = server)

**Comment by kmezhoud** [comment]
Hi,
I think, it is possible to render a big network in shiny. But the graph comes too small (see Example 119 nodes and 348 interactions).

Example (119/348)
https://drive.google.com/file/d/0B9NOY9eukkEeOVE5T1d6TGZlNzQ/view?usp=sharing

**Comment by kmezhoud** [comment]
Now I am sure, There is a limit to plot network with grVis(obj)
This two networks can to be, but can not together with this error message (93 nodes/436 interaction, [grViz_obj.txt](https://drive.google.com/drive/folders/0B9NOY9eukkEefmpIaHFVVmRSYmxDYWtaUGtEcVAtYmctWlRqSkVXcFBkNHVic3ZueE01aHc)).
```
abort() at bb
aa
GG
sx
Wx
IA
Pz
ld
qb
ccall
Viz
renderValue
superFuncBound


onValueChange@http://127.0.0.1:7588/shared/shiny.min.js:3:43619
onValueChange@http://127.0.0.1:7588/shared/shiny.min.js:4:7926
receiveOutput@http://127.0.0.1:7588/shared/shiny.min.js:3:29316
http://127.0.0.1:7588/shared/shiny.min.js:3:30916
_sendMessagesToHandlers@http://127.0.0.1:7588/shared/shiny.min.js:3:30658
dispatchMessage@http://127.0.0.1:7588/shared/shiny.min.js:3:30491
onmessage@http://127.0.0.1:7588/shared/shiny.min.js:3:41906``

```
[Network 1](https://drive.google.com/open?id=0B9NOY9eukkEeYVdsb2U2THQzc0E)
[Network 2](https://drive.google.com/open?id=0B9NOY9eukkEeeXlKQ1k0WExXSUE)

**Comment by kmezhoud** [comment]
Suggestion to better interact with big networks:
Maybe it will be interesting to add some utilities as zooming and selecting network.
Here [pkerpedjiev](https://gist.github.com/pkerpedjiev/0389e39fad95e1cf29ce)  or [this](http://emptypipes.org/2015/02/15/selectable-force-directed-graph/)  two examples.
Thanks

**Comment by happyshows** [comment]
@kmezhoud  for medium sized network (100<x<1000), I suggest you to use visNetwork directly if you insist the interactivity piece, for graph larger than that, I believe it's better to export the graph and render in Cytoscape. There's no point to render a network for documentation purpose for size like that.

**Comment by rich-iannone** [comment]
@kmezhoud There are functions to select nodes and to create a subgraph from the selection. So, that could limit what is rendered. But I do agree with @happyshows about the option to export the DOT code and import the graph in Cytoscape or Gephi.
