### ISSUE TITLE
Edge attribute: dash line

### ISSUE THREAD

**Issue by kmezhoud** [rich-iannone/DiagrammeR#123]
Hi,
How to set Edges wit Dash line?
Thanks

**Comment by rich-iannone** [comment]
Hi @kmezhoud ! Sorry for not answering those last few questions before, I'll try to get to those soon. However, I've got an example for this one:

```R
library(DiagrammeR)

nodes_df <- create_nodes(nodes = c("a", "b"))

edges_df <- create_edges(from = "a", to = "b",
                         style = "dashed")


graph <- create_graph(nodes_df = nodes_df,
                      edges_df = edges_df)

render_graph(graph = graph)
```
Let me know if this doesn't work for you.

**Comment by kmezhoud** [comment]
@rich-iannone 
That works also with shiny without double quote,
Docs is missing this argument. 
Thanks

**Comment by skanskan** [comment]
Hello.

What are other alternatives instead of "dashed"?

I need to plot a graph with too many crossing lines and using just different colours is not enough. I'd like to define different edge styles to identify them
dashed, dotted, normal...
