### ISSUE TITLE
Non English characters do not appear 

### ISSUE THREAD

**Issue by gd047** [rich-iannone/DiagrammeR#124]
An example:
- I have tried grViz(enc2utf8(...)) and grViz(iconv(..., to ="utf8")) without success.  
What should I do in order to see multilingual text on DiagrammeR?

      grViz("
      digraph a_nice_graph {
      graph [compound = true, nodesep = .5, ranksep = .25,
      color = crimson]

      # node definitions with substituted label text
      node [fontname = Helvetica, fontcolor = darkslategray,
      shape = rectangle, color = darkslategray]

      edge [color = grey, arrowhead = none, arrowtail = none]

      a [label = '@@1']
      Ba [label = '@@2-1']
      Bb [label = '@@2-2']
      Bc [label = '@@2-3']

      
      # edge definitions with the node IDs
      a -> {Ba Bb Bc}
      }
      
      [1]: 'A - 10 (2 από 5 θέματα)'
      [2]: 10:12
      ")

**Comment by sdc3** [comment]
One solution is to use html codes.

```{r}
library(DiagrammeR)

grViz("
 digraph a_nice_graph {
      graph [compound = true, nodesep = .5, ranksep = .25,
      color = crimson]
      
      # node definitions with substituted label text
      node [fontname = Helvetica, fontcolor = darkslategray,
      shape = rectangle, color = darkslategray]
      
      edge [color = grey, arrowhead = none, arrowtail = none]
      
      a [label = '@@1']
      Ba [label = '@@2-1']
      Bb [label = '@@2-2']
      Bc [label = '@@2-3']
      
      # edge definitions with the node IDs
      a -> {Ba Bb Bc}
      }
      
      [1]: 'A - 10 (2 &alpha; &pi; &#956; &#964;)'
      [2]: 10:12
      ")
```

**Comment by rich-iannone** [comment]
@sdc3 That's a really great solution... Now I'm wondering if there should be a unicode to html code translator in place to facilitate this.

**Comment by rich-iannone** [comment]
@gd047 @sdc3 @timelyportfolio 

If you use the graph functions (really not that hard to use, once you get going on it), unicode characters are supported:

```R
library(DiagrammeR)

# Create a node data frame
nodes <- create_nodes(nodes = c("α", "β", "γ", "δ",
                                "ε", "ζ", "η", "θ",
                                "ι"),
                      label = TRUE,
                      type = c("Χ", "Χ", "Χ", "Χ",
                               "Ψ", "Ψ", "Ψ", "Ω",
                               "Ω"),
                      color = c("blue", "blue",
                                "red", "red", "pink",
                                "blue", "pink", "red",
                                "pink"),
                      width = c(1.3, 0.7, 1.3, 0.8,
                                1.1, 0.9, 1.8, 1.1,
                                1.2),
                      value = c(182, 98, 182, 112,
                                154, 126, 252, 154,
                                168))

# Create an edge data frame
edges <- create_edges(from = c("α", "β", "ι", "ε", "η", "ζ", "θ", "δ", "δ"),
                      to =   c("β", "ι", "ε", "θ", "θ", "θ", "γ", "γ", "α"),
                      rel = c("rel_a", "rel_a", "rel_b", "rel_c",
                              "rel_b", "rel_a", "rel_b", "rel_c",
                              "rel_c"))

# Create a graph object
graph <- create_graph(nodes_df = nodes,
                      edges_df = edges)

# Render to graph object to the RStudio Viewer panel
render_graph(graph, output = "graph")
render_graph(graph, output = "visNetwork")
```

<img width="341" alt="unicode-graphviz" src="https://cloud.githubusercontent.com/assets/5612024/10229775/a4e94f9a-682e-11e5-95f4-eff0218024a7.png">

<img width="452" alt="unicode-visnetwork" src="https://cloud.githubusercontent.com/assets/5612024/10229784/afe84c84-682e-11e5-8f03-208106ecd208.png">
