### ISSUE TITLE
Combine DiagrammeR Output with Other Plots (e.g. ggplot2) 

### ISSUE THREAD

**Issue by tinyheero** [rich-iannone/DiagrammeR#126]
Hi there,

Is there a way to use the DiagrammeR output in some multipanel figure? For instance, after using grViz to generate a binary tree (for phylogenetic work) I would to combine this graph into a figure with plots made from ggplot. 

The `plot_grid` function from the cowplot R package doesn't work with non ggplot/gtable objects. And the `multiplot` function (http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/) doesn't work either. 

This is mainly for publication purposes. 

Thanks,

**Comment by sdc3** [comment]
Do you want the final result to be rendered in html or as an image?

**Comment by tinyheero** [comment]
Ideally, I want to be able to take some corresponding SVG (?) into something like Adobe Illustrator (or Affinity Designer) to make final edits for scientific publication.

So image? Sorry, I am not 100% clear what you mean by rendering in html or as image. Is it not the same?

**Comment by timelyportfolio** [comment]
I would recommend using `render_graph` with `output='SVG'` and then use the new [`RSvgDevice`](https://github.com/mdecorde/RSvgDevice) for `svg` of the other graphics, such as `ggplot2`.  I'll try to work up an example.

**Comment by tinyheero** [comment]
Thanks. I currently use `render_graph` with output=`SVG` for my diagrammer plot which from my understanding uses the V8 R package to export it. Didn't think about using RSvgDevice for ggplot2 though. Looking forward to an example.

On this note, the only issue I have with `render_graph` is that the width and height parameters are not respected in the final output:

```{r}
render_graph(tree, output = "SVG", width = 98, height = 116)
```

The rendered tree is not 98px by 116px.

**Comment by timelyportfolio** [comment]
Unfortunately, you are correct.  The `width` and `height` are not respected, but since the `viewBox` attribute is nicely set on the `SVG`, we can manipulate the `width` and `height` to get the size we want.  This example will flow nicely into the more thorough example including `ggplot2`.

```
# Render the graph using Graphviz
svg <- render_graph(graph, output = "SVG")

library(XML)
svg_xml <- xmlParse(svg)
root <- xmlRoot(svg_xml)
svg_attrs <- xmlAttrs(root)
svg_attrs[["width"]] <- "98"
svg_attrs[["height"]] <- "116"
xmlAttrs(root) <- svg_attrs

library(htmltools)
browsable(HTML(saveXML(svg_xml)))
```
