### ISSUE TITLE
How to do subgraph clustering?

### ISSUE THREAD

**Issue by ivanhanigan** [rich-iannone/DiagrammeR#127]
Thanks for the great product!  I have been looking through the document http://rich-iannone.github.io/DiagrammeR/graphs.html and trying to figure out how to group nodes in a graphviz subgraph cluster.  Can you help?

My first idea was to hack as below:

#### Code
    # use create_graph on separate nodes and edges data frames, one for each cluster
    # then access the dot codes for each
    gr1 <- graph1$dot_code
    gr2 <- graph2$dot_code
    # then replace the graph with subgraph
    gr1 <- gsub("digraph", "subgraph cluster1", gr1)
    gr2 <- gsub("digraph", "subgraph cluster2", gr2)
    # and then combine the subgraphs into one graph
    gr3 <- sprintf("digraph{\n%s\n\n %s\n}", gr1, gr2)
    grViz(gr3)

Do you have a better way for this?

Thanks again

**Comment by rich-iannone** [comment]
@ivanhanigan Sorry this took so outrageously long to get to... Thanks for the good words. I like your idea but I want to show you another method you may like:

```R
devtools::install_github("rich-iannone/DiagrammeR")
library(DiagrammeR)

# Group 1
nodes_1 <- 
  create_nodes(nodes = c("a", "b", "c", "d",
                         "e", "f", "g", "h",
                         "i"),
               label = TRUE,
               type = c("X", "X", "X", "X",
                        "Y", "Y", "Y", "Z",
                        "Z"),
               color = "blue",
               value = c(182, 98, 182, 112,
                         154, 126, 252, 154,
                         168))

edges_1 <- create_edges(from = c("a", "b", "i", "e", "g", "f", "h", "d", "d"),
                        to =   c("b", "i", "e", "h", "h", "h", "c", "c", "a"),
                        rel = c("rel_a", "rel_a", "rel_b", "rel_c",
                                "rel_b", "rel_a", "rel_b", "rel_c",
                                "rel_c"))

# Group 2
nodes_2 <- 
  create_nodes(nodes = c("j", "k", "l", "m",
                         "n", "o", "p", "q",
                         "r"),
               label = TRUE,
               type = c("A", "A", "A", "A",
                        "B", "B", "B", "C",
                        "C"),
               color = "red",
               value = c(182, 98, 182, 112,
                         154, 126, 252, 154,
                         168))

edges_2 <- create_edges(from = c("j", "m", "q", "r", "k", "m", "r", "q", "o"),
                        to =   c("k", "q", "o", "n", "o", "n", "j", "l", "r"),
                        rel = c("rel_a", "rel_a", "rel_b", "rel_c",
                                "rel_b", "rel_a", "rel_b", "rel_c",
                                "rel_c"))

# Combine graphs
nodes <- combine_nodes(nodes_1, nodes_2)
edges <- combine_edges(edges_1, edges_2)

# Render graph
graph <- create_graph(nodes_df = nodes,
                      edges_df = edges)

render_graph(graph, output = "visNetwork")
```

**Comment by ivanhanigan** [comment]
@rich-iannone Thanks again.
I like that approach.  However I am struggling to apply it for my work.  Below you can see an example of what I am trying to achieve.

```r
library(DiagrammeR)
#### First create the outcome
nodes_outcome <- create_nodes(nodes = c('suicide','depression','anxiety'),
                        label = TRUE,
                        colour = "black")

edges_outcome <- create_edges(from = c('depression','anxiety'),
                        to =   c("suicide", "suicide")
                        )

graph_outcome <- create_graph(nodes_df = nodes_outcome,
                       edges_df = edges_outcome)
# just test this out
## render_graph(graph_outcome)
                        
#### now the social capital factors  
nodes_social <- 
  create_nodes(nodes =  c("stress", "decreased community support", "migration"),
               label = TRUE,
               color = "blue")

edges_social <- create_edges(from =  c("stress", "stress", "decreased community support",
                          "migration"),
                        to =   c("anxiety", "depression", "anxiety",
                          "decreased community support")
                        )
graph_social <- create_graph(nodes_df = nodes_social,
                       edges_df = edges_social)
# render_graph(graph_social)

#### now the financial capital factors
nodes_financial <- 
  create_nodes(nodes = c("employment", "debt"),
               label = TRUE,
               color = "green")

edges_financial <- create_edges(from = c("employment", "employment", "debt"),
                        to =   c("stress", "debt", "stress")
                        )
graph_financial <- create_graph(nodes_df = nodes_financial,
                       edges_df = edges_financial)
# render_graph(graph_financial)


#### now the natural capital factors
nodes_natural <- 
  create_nodes(nodes = c("drought", "declined agricultural productivity", "decreased food security"),
               label = TRUE,
               color = "red")

edges_natural <- create_edges(from = c("drought", "drought", "declined agricultural productivity",
                          "declined agricultural productivity", "declined agricultural productivity",
                          "decreased food security",
                          "drought"),
                        to =   c("declined agricultural productivity", "decreased food security", "decreased food security",
                          "anxiety", "employment",
                          "anxiety",
                          "migration")
                        )
graph_natural <- create_graph(nodes_df = nodes_natural,
                       edges_df = edges_natural)
## render_graph(graph_natural)

# use create_graph on separate nodes and edges data frames, one for each cluster
# then access the dot codes for each
gr0 <- graph_outcome$dot_code
gr1 <- graph_social$dot_code
gr2 <- graph_financial$dot_code
gr3 <- graph_natural$dot_code
# then replace the graph with subgraph
gr0 <- gsub("digraph", "subgraph cluster0", gr0)
gr1 <- gsub("digraph", "subgraph cluster1", gr1)
gr2 <- gsub("digraph", "subgraph cluster2", gr2)
gr3 <- gsub("digraph", "subgraph cluster3", gr3)
# and then combine the subgraphs into one graph
gr_out <- sprintf("digraph{\n%s\n\n %s\n%s\n%s\n}", gr0, gr1, gr2, gr3)
cat(gr_out)
grViz(gr_out)


```

# which gives this output

![suicide-drought](https://cloud.githubusercontent.com/assets/1305767/10261346/5753ff92-69d6-11e5-8c8d-78b16d020b87.png)

# following your approach I get a good thing too

```r
nodes <- combine_nodes(nodes_outcome, nodes_social, nodes_natural, nodes_financial)
edges <- combine_edges(edges_outcome, edges_social, edges_natural, edges_financial)
# Render graph
graph <- create_graph(nodes_df = nodes,
                      edges_df = edges)
render_graph(graph, output = "visNetwork")  
```

[http://ivanhanigan.github.io/viewhtml21f36d8c5d7d/index.html](http://ivanhanigan.github.io/viewhtml21f36d8c5d7d/index.html)

# But they are not grouping so I probably did something wrong.

- Any advice on how I should best go about utilising this in my work would be really helpful.
- I want to incorporate the diagrammer tool into hypothesis generation and also workflow planning etc

**Comment by rich-iannone** [comment]
@ivanhanigan this is great stuff and I do think that with a little work the clustering can be done effectively with the `visNetwork` rendering. I'm planning on looking into this tonight. I'll keep you posted!

**Comment by GitChub** [comment]
@ivanhanigan I just found that in my application it's useful to keep the edges separate from the subgraph clusters in the DOT code.  You can see an example in my 2nd comment on this issue:  
https://github.com/rich-iannone/DiagrammeR/issues/166

**Comment by ivanhanigan** [comment]
@GitChub thanks for this.  Can I just clarify though, you are recommending I change the structure of the dot code (keeping edges sep from subgraph clusters) for improvements/stability in `graphviz` rendering, but not to solve the `visNetwork` rendering issue I was having?   Or can your solution somehow solve the issue of adding structure to the `visNetwork` output too?

The code below shows that modifying my example will create a good graphviz output with clustering (ie this is as good as the previous approach but now is more stable as per your issue of weird flipping as per #166) but I cannot render the dot_code using the following

    render_graph(dot_code, output="visNetwork")
    # returns
    # Error: class(graph) == "dgr_graph" is not TRUE

My revised codes:

    library(DiagrammeR)
    nodes_outcome <- create_nodes(nodes = c('suicide','depression','anxiety'),
                            label = TRUE,
                            colour = "black")
    graph_outcome <- create_graph(nodes_df = nodes_outcome)
    
    nodes_social <- 
      create_nodes(nodes =  c("stress", "decreased community support", "migration"),
                   label = TRUE,
                   color = "blue")
    
    graph_social <- create_graph(nodes_df = nodes_social)
    
    gr0 <- graph_outcome$dot_code
    gr1 <- graph_social$dot_code
    gr0 <- gsub("digraph", "subgraph cluster0", gr0)
    gr1 <- gsub("digraph", "subgraph cluster1", gr1)
    # and then combine the subgraphs into one graph
    subgraphs_dot_code_vector <- sprintf("digraph{\n%s\n\n %s\n", gr0, gr1)
    cat(subgraphs_dot_code_vector)
    
    # as recommended by gitchub, keep edges sep
    edges <- create_edges(from =  c("stress", "stress", "decreased community support",
                              "migration", "depression", "anxiety"),
                            to =   c("anxiety", "depression", "anxiety",
                              "decreased community support", "suicide", "suicide")
                            )
    #edges
    edges_only_dot_code <- gsub('digraph \\{', '',
                                create_graph(edges_df = edges)$dot_code
                                )
    #cat(edges_only_dot_code)
    dot_code <- paste0(
                       paste0(subgraphs_dot_code_vector, collapse = ' ')
                       ,
                       edges_only_dot_code
                       , collapse = ' '
                       )
    
    #cat(dot_code)
    
    grViz(dot_code, allow_subst = FALSE)
    
    # that is as expected however
    render_graph(dot_code, output="visNetwork")
    # returns
    # Error: class(graph) == "dgr_graph" is not TRUE

**Comment by rich-iannone** [comment]
@ivanhanigan The reason it does not work for `visNetwork` output is because it doesn't use `DOT` code but instead the data frames within the `dgr_graph` object. The effect of clusters with `visNetwork` can be achieved by providing different `type` values to nodes of a particular grouping.

**Comment by GitChub** [comment]
@ivanhanigan Yes, I was only mentioning that for improvements/stability in `graphviz` rendering and not to solve the `visNetwork` rendering issue, which it appears Rich has just illuminated.

**Comment by rich-iannone** [comment]
@GitChub ah, okay. I think a helper function for creating clusters might be useful. That way, the dot code won't have to be extracted and modified. Then the graph could be further modified via functions and rendered with `render_graph`. What do you think?

**Comment by ivanhanigan** [comment]
@rich-iannone @GitChub thanks for this.  I will probably not use visNetwork as much as graphviz for this work, so I reckon the solution to my issue is to manipulate the dot_code using @GitChub approach.
I'm happy to close this issue now, and happy to test if/when any cluster_helper_function is developed in the future.
Kind regards,
Ivan.

**Comment by GitChub** [comment]
@rich-iannone A helper function for creating clusters sounds like a good idea at first blush. I should mention that, in my particular situation, I am also modifying the DOT code to include other GraphViz subgraph attributes such as "label" and "labelloc".  I suspect that other users of subgraph clusters would also be inclined to assign subgraph attributes.  I'm guessing, however, that subgraph attributes are beyond the capability of the helper function you had in mind.
