### ISSUE TITLE
diagrammer (mermaid) plots in knitr document?

### ISSUE THREAD

**Issue by vnijs** [rich-iannone/DiagrammeR#129]
Is there a way to get a mermaid plot to show in a knitr document? It works in rmarkdown. For example, when I try knitting the package vignette with the command below no DiagrammeR plots are shown. I looked at what rmarkdown does and tried including all the js and css files but still couldn't get it to work.

`knit2html("~/Desktop/diagrammer.Rmd")`

**Comment by sdc3** [comment]
Hi,
[This stackoverflow question](http://stackoverflow.com/questions/31645528/knit-dtdatatable-without-pandoc) may correspond to what you're looking for. The "render_with_widgets" function works on the DiagrammeR vignette.

**Comment by vnijs** [comment]
Thanks @ghost. Got it working.
