### ISSUE TITLE
Shiny apps that use DiagrammeR don't work when deployed on shinyapps.io or Shiny Server Pro

### ISSUE THREAD

**Issue by wch** [rich-iannone/DiagrammeR#134]
This happens because Shiny Server inserts a `<base>` tag in the HTML body, which causes problems with some SVG elements, like arrowheads and gradients.

Fortunately, the latest version of mermaid.js has a fix for this (thanks to yours truly), so simply including the latest version should fix it for DiagrammeR. See knsv/mermaid#209 for more information about this problem.

**Comment by rich-iannone** [comment]
@wch thanks very much for doing all this! I think @timelyportfolio added in the latest release of mermaid.js in a recent PR (and it was accepted). Kent: can you verify that that version was indeed the latest build?

**Comment by wch** [comment]
I think the needed version of mermaid.js (0.5.2) was released 2 days ago, and your version is 0.5.1 (I found this by searching the mermaid.slim.min.js file for `version`).

**Comment by rich-iannone** [comment]
@wch thanks again. The most recent version of mermaid.slim.min.js (0.5.3) is now part of the package (along with the updated mermaid.css file).

**Comment by wch** [comment]
Great, thanks for updating it!
