### ISSUE TITLE
pie chart custom icons to replace nodes

### ISSUE THREAD

**Issue by rmflight** [rich-iannone/DiagrammeR#136]
This may be a duplicate of #108 , but I'm not sure. Is it possible to replace nodes with a custom pie chart icon, with different nodes having different icons?

It would also be great in the documentation to have an example of using an `icon`, or did I miss that?

**Comment by rich-iannone** [comment]
Here's an example that currently works best when the output option is `visNetwork`

```
node <- create_nodes(nodes = "a",
             shape = "image",
             image = "https://raw.githubusercontent.com/rich-iannone/DiagrammeR/master/inst/examples/blue-circle.png")

render_graph(create_graph(nodes_df = node),
             output = "visNetwork")
```

**Comment by guiastrennec** [comment]
Not sure if it is what you are trying to achieve but Graphviz also allows the nodes to be ```wedged``` (when circles) or ```striped``` (when rectangles) and this can be achieved through DiagrammeR. All you need to do is: 

1. Add a ```style``` column in your ```node_df``` in which you will use ```filled``` for regular nodes and either ``wedged``` or ```striped``` the ones where you want your charts.

2. Define the ```fillcolor``` for the charts as follow : ```yellow;0.3:blue``` this will make a node filled at 70 % in blue and 30 % in yellow. You can use more than 2 colors if needed.

**Comment by rich-iannone** [comment]
Thanks for verifying this works (and for the good explanation). The background documentation on how this works in Graphviz is here: http://www.graphviz.org/content/attrs

It's near the bottom of that page. Search for "wedged".

**Comment by rmflight** [comment]
The motivation is to do nodes that look like Figure B [here](http://www.frontiersin.org/files/Articles/73104/fgene-05-00098-r2/image_m/fgene-05-00098-g004.jpg) in the viewer. Currently I connect to cytoscape, and may use cytoscape js, but having other options is good.

**Comment by rmflight** [comment]
Awesome, both of the methods mentioned work. I may also try Graphviz label with html style labels and define the `img` attribute.

BTW @rich-iannone, you can also start up a python webserver and use `http://localhost:8000/path_to_fig` and it will work.
