### ISSUE TITLE
Disable SVG warnings

### ISSUE THREAD

**Issue by guiastrennec** [rich-iannone/DiagrammeR#137]
Hello, 
Exporting diagrams in SVG usually works fine but, I sometimes get a warning row, which then prevent web browser from rendering the diagram. If I edit the SVG code and remove the warning the diagram is then rendered properly. Is there any way to disable this type of warnings?

The usual warnings are :
```
pre-main prep time: 1 ms
Warning: node 'A4', graph '%3' size too small for label
```

I use the following command to generate the SVG files:
```r
sink('diagram.svg')
cat( render_graph(graph, output = 'SVG') )
sink()
```

Thanks in advance

**Comment by sculptor3** [comment]
@quiastrennec Can you show how you construct the graph? When I use your code on my graph, nothing happens.

**Comment by guiastrennec** [comment]
Thank you for looking into my issue. At the moment the SVG export feature has been removed from DiagrammeR (See commit here: <https://github.com/rich-iannone/DiagrammeR/commit/8ea70b00189eb50d4163fbc5ab47266c9cfa1746>). According to rich-iannone the feature will be back at some point.

**Comment by rich-iannone** [comment]
@guiastrennec @sculptor3 I'm hoping that an external solution to the graphics export issue will materialize (e.g., htmlwidgets might offer support for export of graphics). The reason for the removal is that the feature relied on the `V8` package to work and CRAN didn't want that dependency in the package (it can result in installation problems across different system types).

A possible interim solution might be to make a standalone package, hosted only on GitHub, that provides the export functionality. Good idea?

**Comment by sculptor3** [comment]
Thank you for your response. Good to know it will be back some time.
Op 3 nov. 2015 20:32 schreef "Benjamin" <notifications@github.com>:

**Comment by sculptor3** [comment]
@rich-iannone that sounds like a good idea!!

**Comment by guiastrennec** [comment]
I also think it would be nice to have an option to export graphs at least on the github repository, in the wait of a permanent solution. I am not aware of any package to achieve this yet but given the interest to packages like ggvis I am sure that things will come out.

**Comment by ajholguin** [comment]
+1 for restoring SVG export functionality.

**Comment by rich-iannone** [comment]
@guiastrennec @sculptor3 @ajholguin 

I apologize for the delay on this, but the separate package for exporting Graphviz diagrams in DiagrammeR is now available at: https://github.com/rich-iannone/DiagrammeRsvg. It contains a single function that performs the conversion of a `grViz` object to SVG text. A simple example is included in the help file for the function.

**Comment by sculptor3** [comment]
@rich-iannone, please don't appologize! Thank you very much for this new package!  I will try it out as soon as possible.

**Comment by guiastrennec** [comment]
Great, thank you very much for the follow up !
