### ISSUE TITLE
Implementation of rank when using functions?

### ISSUE THREAD

**Issue by Kenkleinman** [rich-iannone/DiagrammeR#138]
Here's a course sequence I threw together that makes use of the rank=same feature in graphviz.  I think that's absent in the functional approach to DiagrammeR (0.8.1).  Can you add it?  Would be great to have it!

grViz('digraph mine {
      rankdir = TB;
      node [shape = diamond]; 
      edge [color=white];
      "FALL #1" -> "SPRING #1" -> "FALL #2" -> "SPRING #2";
      node [shape = circle; penwidth = 3];
      "540\nIntroduction"; "690NR\nMethods II"; "690KK\nMethods III"; "690JQ\nMethods IV";
      "691F\nSAS"; "748\nSurvival";"597D\nIntro R";"741\nMixed"; 
      node [shape = box; penwidth = 3];
      "STAT515"; "STAT516"; 
      node [shape = circle; penwidth=1]
      edge [color=black]
      
      "540\nIntroduction"-> {"640\nIntermediate"; "690NR\nMethods II"} 
      "540\nIntroduction"-> "691F\nSAS" [style=dotted]
      "640\nIntermediate";
      "749\nTrials";
      "597D\nIntro R"-> {"690NR\nMethods II";"597E\nR II";}
      "691F\nSAS"-> {"740\nSampling";"690KK\nMethods III";}
      "690NR\nMethods II"-> {  "740\nSampling"; "748\nSurvival"; "690T\nGenetics";"690KK\nMethods III";};
      "690KK\nMethods III" -> {"690JQ\nMethods IV"; "741\nMixed";}
      "690DS\nData Science";      
      edge [color = red];
      "STAT515" -> "STAT516";
      "STAT516" -> {"740\nSampling"; "749\nTrials"; "748\nSurvival"; "747\nBiomarkers";
      "690T\nGenetics"; "690MS\nStochastic"; "741\nMixed";}
      
      
      
      {rank=same; "540\nIntroduction"; "597D\nIntro R"; "STAT515"; "691F\nSAS"; "FALL #1"};
      {rank=same; "640\nIntermediate"; "690NR\nMethods II"; "STAT516"; "597E\nR II";
      "690DS\nData Science";  "SPRING #1"};
      {rank=same;  "740\nSampling"; "749\nTrials";"690KK\nMethods III";"690MS\nStochastic"; "FALL #2"}
      {rank=same; "690JQ\nMethods IV"; "690T\nGenetics"; "748\nSurvival"; "741\nMixed";
      "747\nBiomarkers"};
      }', engine = "dot")

**Comment by rich-iannone** [comment]
Ken, that looks really good! I think you're right in that there's no way currently to implement `rank=same` with the functional approach in DiagrammeR. But, I will work toward getting that in the package.

**Comment by Kenkleinman** [comment]
Awesome, thanks, and thanks for the good work!

_______________________________________________________
_______________________________________________________
Ken Kleinman, ScD
Associate Professor, Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

Lecturer, Department of Population Medicine
Harvard Medical School

My blog on SAS and R: http://sas-and-r.blogspot.com
My professional web home: http://www.kenkleinman.net/home/
My cites on Google Scholar: http://tinyurl.com/KenK-cites
__________________________________________________
** Electronic Mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues. **

**Comment by guiastrennec** [comment]
If it is of any help I am already using ```rank = same``` with DiagrammeR. I had edited the create_graph.R function, and all I did was to add the code below (create_graph has been edited since I made my edit but on the latest github version you would have to insert it somewhere around row 484).

```r
    if('rank' %in% colnames(nodes_df)){
      node_block <- tapply(node_block, nodes_df$rank, FUN = function(x){
        if(length(x) > 1){
          x <- paste0('subgraph{rank = same\n',
                      paste0(x, collapse = '\n'),
                      '}\n')
        }
        return(x)
      })
    }

    node_block <- paste(node_block, collapse = "\n")
```

**Comment by rich-iannone** [comment]
That's great! Mind if I add that in? Or would you like to send a PR?

**Comment by guiastrennec** [comment]
Please go ahead, I am still new with Github and trying to figure things out.

**Comment by marton-balazs-kovacs** [comment]
Do you have an example code on how to add ranks to nodes in the functional approach?
