### ISSUE TITLE
Problem with pandoc / mermaid

### ISSUE THREAD

**Issue by gluc** [rich-iannone/DiagrammeR#139]
After updating to the latest DiagrammeR from CRAN, my vignette is not building any more, giving me the following error:

pandoc.exe: Could not fetch .\R\win-library\3.2\DiagrammeR\htmlwidgets\lib\mermaid\dist\#arrowhead

See here: https://gist.github.com/gluc/b385cf03eda6387b16d4

If I run the code in R (not in markdown), it does not produce an error, but the arrowheads are not displayed any more.

I think this is related to this commit:

https://github.com/rich-iannone/DiagrammeR/commit/dbdabc1fb3a27007f01215370bb11ad8c90e069f#diff-7767211fc4f816e6791a70636bff7322

**Comment by stephlocke** [comment]
+1
Getting this too in Windows, from CRAN version + github version

**Comment by ianjacobs** [comment]
Me also,
On Mac, from CRAN version and github version

Incidentally, arrowheads are not displaying when rendering mermaid diagrams within R scripts, could be a related issue?

**Comment by yulijia** [comment]
Is there any way to bring arrowhead back to the package?
I am a new user of this package, I run some examples at [DiagrammeR website](http://rich-iannone.github.io/DiagrammeR/mermaid.html) , none of  arrowheads are displayed in the figures.
