### ISSUE TITLE
engine argument in grVis seems not to be working (windows)

### ISSUE THREAD

**Issue by AndySouth** [rich-iannone/DiagrammeR#140]
I'm loving diagrammer, thankyou.

However with grVis I can't get anything other than the default dot layout.

I even took the neato example from the webpage (copied on the end of this) and that displays as dot layout. 

Changing the engine argument has no effect, even when I change it to something spurious.

I have tried installing from both CRAN & Github.

Apologies if I'm missing something obvious.

Andy

Some system details : 
> packageDescription("DiagrammeR")
Package: DiagrammeR
Version: 0.8.1
Date: 2015-10-11

RemoteType: github
RemoteHost: api.github.com
RemoteRepo: DiagrammeR
RemoteUsername: rich-iannone
RemoteRef: master
RemoteSha: 2034cd7da24c0701913f2cf6ef6443493add95ea
GithubRepo: DiagrammeR
GithubUsername: rich-iannone
GithubRef: master
GithubSHA1: 2034cd7da24c0701913f2cf6ef6443493add95ea

Built: R 3.2.2; ; 2015-10-23 11:16:06 UTC; windows

RStudio Version 0.99.669

Reproducible example.
grViz("
digraph neato {

node [shape = circle,
      style = filled,
      color = grey,
      label = '']

node [fillcolor = red]
a

node [fillcolor = green]
b c d

node [fillcolor = orange]

edge [color = grey]
a -> {b c d}
b -> {e f g h i j}
c -> {k l m n o p}
d -> {q r s t u v}
}",
engine = "neato")

**Comment by Auburngrads** [comment]
Second this...The engine argument seems to be ignored.  Ran the examples from the DiagrammeR website, like what  AndySouth showed, but I also tried nonsensical arguments like `engine = '#&^@*#'`.  This did not result in any errors.

**Comment by rich-iannone** [comment]
Sorry for the late reply @AndySouth (and thanks for checking also, @Auburngrads). Obviously, this is broken and thus a bit terrible. I'm going to prioritize fixing this and I'll report back here when it's indeed fixed.

**Comment by rich-iannone** [comment]
@AndySouth @Auburngrads in the meantime, you could use `graph [layout = neato]` within the graph spec in order to get the `neato` layout working:

```
grViz("
digraph neato {
      
      node [shape = circle,
      style = filled,
      color = grey,
      label = '']

      graph [layout = neato]
      
      node [fillcolor = red]
      a
      
      node [fillcolor = green]
      b c d
      
      node [fillcolor = orange]
      
      edge [color = grey]
      a -> {b c d}
      b -> {e f g h i j}
      c -> {k l m n o p}
      d -> {q r s t u v}
      }")
```

**Comment by rich-iannone** [comment]
Okay, this seems to be a problem with the new JS version of `viz.js`. It's ignoring the engine argument (everything is passed through to the htmlwidget `x` object as always, since nothing's changed).

I don't really know how to fix this in the near term. So, is the above workaround (specifying layout in the grViz spec) sufficient? If so, I could drop the `engine` argument and update the documentation.

Another option to creating graphs with different layouts is to use the graph-building functions (e.g., `create_graph()`, `render_graph()`. Set a global `graph_attr = "neato"` when using `create_graph()`.

**Comment by Auburngrads** [comment]
Using `graph[layout = neato]` in the graph spec seems to work well for me.  Thanks for the fix!

**Comment by AndySouth** [comment]
Thanks, yes adding the layout argument to graph works for me too.

**Comment by ericwatt** [comment]
Another confirmation that ```graph [layout = neato] ``` fixed the issue on windows. Thanks.

**Comment by rich-iannone** [comment]
Thanks @ericwatt! It's perhaps preferred to included the layout information within the graph spec (it aligns better with existing Graphviz code). I'll close the issue now.
