### ISSUE TITLE
example of using a tooltip in Mermaid plot?

### ISSUE THREAD

**Issue by vnijs** [rich-iannone/DiagrammeR#141]
I see references to tooltips in the DiagrammeR code but haven't been able to find any examples of how to add a tooltip to a node in a mermaid plot. Is this possible?

**Comment by rich-iannone** [comment]
@vnijs I don't think this is possible with mermaid plots but it's possible with `Graphviz` and `visNetwork` plots. This may change as `mermaid.js` gets updated in the future.

**Comment by vnijs** [comment]
Looks like it should be possible as of release 0.5.3 (see link below). Still not clear how to do it however. Could you point to an example using `Graphviz` or `vizNetwork` perhaps? Thanks

https://github.com/knsv/mermaid/releases/tag/0.5.3
