### ISSUE TITLE
delete_node fix

### ISSUE THREAD

**Issue by iwi** [rich-iannone/DiagrammeR#143]
I came across an issue with the current delete_node function. When a node in the graph has no edges, it gives the following error:

    Error in if (all(!(colnames(edges_df)[j] %in% c("edgetooltip", "headtooltip",  : 
      missing value where TRUE/FALSE needed

It seems the problem is that edges_df is actually empty because the lines

```r
 # Create a revised edge data frame
 revised_edges_df <- graph$edges_df[-which((graph$edges_df$from == node) |
                                                (graph$edges_df$to == node)),]
```

produce an empty dataframe instead of keeping the original one.

I've written a quick fix, that works for me.

```r
    # Create a revised edge data frame
    if (nrow(graph$edges_df[-which((graph$edges_df$from == node) |
                                    (graph$edges_df$to == node)),]) == 0) {
      revised_edges_df <- graph$edges_df
    } else {
      revised_edges_df <- graph$edges_df[-which((graph$edges_df$from == node) |
                                                  (graph$edges_df$to == node)),]
    }
```

What do yo think?

Thanks,

**Comment by rich-iannone** [comment]
@iwi Thanks so much for fixing (and sending that PR)! Feel free to do so again, I really appreciate it.

**Comment by iwi** [comment]
@rich-iannone thank you for creating DiagrammeR. 
I started adding a test for this fix, but got into some issues, I'll PR when it works.

**Comment by rich-iannone** [comment]
Thanks @iwi. If you'd like to make regular contributions like this I can include you as a developer on the DiagrammeR website.

I do appreciate the help and so I'd like it to be recognized.

**Comment by iwi** [comment]
As you wish @rich-iannone.
Maybe you should wait to see if I can really be a _regular_ contributor :).

But happy either way.
