### ISSUE TITLE
keeping graph$edge_attrs and graph$node_attrs after delete_node or delete_edge

### ISSUE THREAD

**Issue by iwi** [rich-iannone/DiagrammeR#145]
I've seen that in the re-construction of the graph after deleting a node or an edge the process ignores the previous graph$edge_attrs and graph$node_attrs. 

[Here](http://stackoverflow.com/questions/33445480/how-to-keep-edge-colours-after-delete-edge-in-diagrammer) a question I posted on stackoverflow the other day .

I've amended `delete_node` and `delete_edge` and for my needs they work, but before sending a PR I wanted to know if there is a specific reason why you decided not to keep the general node and edge attributes.

**Comment by rich-iannone** [comment]
@iwi the non-retention of these attributes is not intentional. This was an oversight so if you have a PR you can deliver, it would be a great contribution.
