### ISSUE TITLE
grViz produces an “abort” message in the browser. 

### ISSUE THREAD

**Issue by Malabady** [rich-iannone/DiagrammeR#151]
Hi there, 
When I try to produce some graphs in RStudio  using grViz, it doesn’t produce any graphs. Instead, it shows the following errors in the browsers. 

I am running RStudio on Mac OS X (10.11.1), latest release of RStudio and R.3.0.3

Any suggestions how to fix this problem!

Thanks.

abort() at bb@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:9:177
aa@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:34:261
GG@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1245:30919
sx@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1237:24178
Wx@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1237:36969
IA@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1209:36703
Pz@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1209:14639
ld@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1201:852
qb@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:3:13
ccall@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:47:226
Viz@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/viz-0.3/viz.js:1301:209
renderValue@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/grViz-binding-0.4/grViz.js:38:27
staticRender@file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/htmlwidgets-0.3.2/htmlwidgets.js:475:30
file:////var/folders/8_/f3kg92b93739frx2rpfnzsxm0000gn/T/RtmplKP9bh/viewhtmlb008bdddcfe/lib/htmlwidgets-0.3.2/htmlwidgets.js:485:19

**Comment by rich-iannone** [comment]
Hi, can you try running the examples in the README after a fresh install with `install_github`? Then submit the code you using to create a graph here.

**Comment by Malabady** [comment]
When I try to install using install_github, it complains that the package "visNetwork" isn't available for R version 3.0.2, see this: 

ERROR: dependency ‘visNetwork’ is not available for package ‘DiagrammeR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.0/Resources/library/DiagrammeR’
Error: Command failed (1)
In addition: Warning message:
package ‘visNetwork’ is not available (for R version 3.0.2) 

When I install with biocLite it doesn't produce the same error message or any other error message.

**Comment by rich-iannone** [comment]
Could you try once again? I've updated the minimum version of **visNetwork** that's required.

**Comment by MarkEdmondson1234** [comment]
Hi @rich-iannone I got a similar error in DiagrammeR 0.8.1 trying to graph a big matrix:

```
abort() at jsStackTrace@http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:5:22072
stackTrace@http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:5:22258
abort@http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:28:10656
oc@http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:11:71
stringToC@http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:5:15479
ccallFunc@http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:5:15930
http://localhost:20863/session/viewhtml118a395315a1/lib/viz-0.3/viz.js:47:42
renderValue@http://localhost:20863/session/viewhtml118a395315a1/lib/grViz-binding-0.8.1/grViz.js:38:27
http://localhost:20863/session/viewhtml118a395315a1/lib/htmlwidgets-0.5/htmlwidgets.js:514:30
forEach@[native code]
forEach@http://localhost:20863/session/viewhtml118a395315a1/lib/htmlwidgets-0.5/htmlwidgets.js:55:21
http://localhost:20863/session/viewhtml118a395315a1/lib/htmlwidgets-0.5/htmlwidgets.js:447:14
forEach@[native code]
forEach@http://localhost:20863/session/viewhtml118a395315a1/lib/htmlwidgets-0.5/htmlwidgets.js:55:21
staticRender@http://localhost:20863/session/viewhtml118a395315a1/lib/htmlwidgets-0.5/htmlwidgets.js:445:12
http://localhost:20863/session/viewhtml118a395315a1/lib/htmlwidgets-0.5/htmlwidgets.js:524:38
```

I guess its memory but just checking in here in case its not, my graph is 115600 obs...

```
plot_data <- mc@transitions[[1]] ## for first order
plot_data$names <- row.names(plot_data)

m <- reshape2::melt(plot_data)

# Create a graph from an edge data frame, the nodes will
edges <- create_edges(from = m$names,
                      to = m$variable,
                      value = m$value,
                      rel = "leading_to")

## took a while
graph <- create_graph(edges_df = edges)

## doesn't work
render_graph(graph)

str(m)
> str(m)
'data.frame':	115600 obs. of  3 variables:
 $ names   : chr  "/" "/aabenraa-krusaa/aabenraa-en-historisk-koebstad" "/aabenraa-krusaa/barsoe" "/aabenraa-krusaa/det-sker-i-aabenraa" ...
 $ variable: Factor w/ 340 levels "/","/aabenraa-krusaa/aabenraa-en-historisk-koebstad",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ value   : num  0.436 0 0 0 0 ...
```

**Comment by rich-iannone** [comment]
@MarkEdmondson1234 It's definitely memory. The graphviz rendering c/o `viz.js` doesn't handle all that many nodes, so, `render_graph` blows up. With `render_graph(graph, output = "visNetwork")` more nodes/edges may be displayed but it's slow. For large graphs then, it's probably best to visualize small parts of the graph using subgraphs
