### ISSUE TITLE
grViz will not produce graphics in RStudio viewer, but I can see them in Chrome

### ISSUE THREAD

**Issue by ianagutierrez** [rich-iannone/DiagrammeR#153]
Hi all,

When I use the grViz function in RStudio, it generates empty plots in the RStudio viewer. No error messages whatsoever. If I run "is_graph_empty" on the object created by grViz, RStudio returns "TRUE." However, if I click on the "show in new window" button in the RStudio viewer panel, it will route me to a Google Chrome browser window and correctly reproduce the graph there.

Here's an example of what's happening. I have included the sessionInfo() at the end of the code. 

> library(DiagrammeR)
> x<-grViz("
+ digraph SEM {
+          
+          graph [layout = neato,
+          overlap = true,
+          outputorder = edgesfirst]
+          
+          node [shape = rectangle, fontname=Courier]
+          
+          x [pos = '0, 0!', label = 'Test Node for DiagrammeR']}")

x #this produces a empty graph, but if I click the "show in new window" button in RStudio, it will correctly reproduce the graph in Google Chrome

is_graph_empty(x)
[1] TRUE
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] foreign_0.8-65   DiagrammeR_0.8.1

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.5  magrittr_1.5     visNetwork_0.1.2 htmltools_0.2.6  tools_3.2.2     
 [6] rstudioapi_0.3.1 yaml_2.1.13      stringi_1.0-1    jsonlite_0.9.19  stringr_1.0.0   
[11] digest_0.6.8    
> 

Any help would be greatly appreciated, and thank you, Rich, for producing this package!

**Comment by rich-iannone** [comment]
Hi Ian, the above code snippet works in my RStudio Viewer so this is strange. Try getting a fresh build of DiagrammeR with `install_github` and try again. Also, try running the code samples on the README (just to see if those work).

By the way, the `is_graph_empty` function only works on graph objects (not objects created by `grViz`).

**Comment by ianagutierrez** [comment]
The fresh build using install_github worked! Previous install has been via CRAN. Thank you for the help!

**Comment by ianagutierrez** [comment]
Hmm, having this issue again, even when installing the package via devtools::install_github. Might it be something to do with another package I might be running? Why would the image render in Chrome but not RStudio? Something to do with html?
