### ISSUE TITLE
example in create_subgraph_from_selection needs update

### ISSUE THREAD

**Issue by swiftsam** [rich-iannone/DiagrammeR#154]
The Examples in create_subgraph_from_selection include [this block](https://github.com/rich-iannone/DiagrammeR/blob/master/R/create_subgraph_from_selection.R#L35)

```R
# Create a selection of nodes, stored within the
# graph object
graph <-
  select_nodes(graph, node_attr = "value",
               comparison = "> 3")
```

which needs to be updated to use the new select_nodes argument `search` as of [this commit](https://github.com/rich-iannone/DiagrammeR/commit/35f6ac6929072620dec325841c8317260e43a759)

Suggested:
```R
# Create a selection of nodes, stored within the
# graph object
graph <-
  select_nodes(graph, node_attr = "value",
               search = "> 3")
```

Thanks for a great package!

**Comment by rich-iannone** [comment]
Thanks very much for catching this and letting me know! It's now updated :)
