### ISSUE TITLE
edge_info.R error

### ISSUE THREAD

**Issue by garyfeng** [rich-iannone/DiagrammeR#155]
If you load both `ggplot2` and `diagrammeR`, and create a graph *without* a column named `rel` in your edge data frame, then you'd see an error message when you do `edge_info(graph)` telling you that you are trying to subset a function. As it turns out, `ggplot2` defines a function `rel`. So the following check in `edge_info.R`, line 82, will return True, and you end up subsetting the ggplot2 function `rel()`.

```
      edge_properties[i, 3] <-
        ifelse(exists("rel"),
               rel[which((edge_from %in% edge_from[i]) &
                           (edge_to %in% edge_to[i]))],
               rep(NA, length(edge_from)))
```

This can be fixed with

```
ifelse("rel" %in% colnames(graph$edges_df),
```
which was the test to create 'rel'.

**Comment by rich-iannone** [comment]
@garyfeng Thanks very much for spotting this and suggesting a fix. The function has now been modified!
