### ISSUE TITLE
set_graph_name not exported on CRAN version

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#157]
Hi,

Actually I found two issues:
1. the CRAN version does not support set_graph_name
2. when I tried to set a graph name inside create_graph function, it didn't work. Instead, it showed <title>%3</title>

I tried to install the latest dev version from Github, however it kept crashing

Error in fetch(key) : 
  lazy-load database 'C:/R/Lib/DiagrammeR/help/DiagrammeR.rdb' is corrupt

**Comment by rich-iannone** [comment]
I'll get a more recent version out on CRAN very soon. I'm a little surprised that `install_github` produces a non-working version. I'll look into that as well.

**Comment by happyshows** [comment]
cool, look forward for your update :D

**Comment by happyshows** [comment]
It's been a while since I decided to wait when you just released 0.6, almost my shiny app code stopped working, please retest them before the 0.8.2 release, appreciate it.

**Comment by rich-iannone** [comment]
Thanks @happyshows ! I was supposed to do this awhile back but I've been so focused on documentation that it got pushed back. :/
