### ISSUE TITLE
plaintext as node shape did not seem to work

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#158]
Hi,

Could you please check?

**Comment by rich-iannone** [comment]
@happyshows 

It does work for me. I used:

```r
library(DiagrammeR)
library(magrittr)

create_graph(nodes_df = create_nodes(1:4, shape = "plaintext")) %>% render_graph
```

<img width="563" alt="plaintext_nodes" src="https://cloud.githubusercontent.com/assets/5612024/12731079/d8c86204-c8e3-11e5-9379-409b5df6ec75.png">

There's a new version of **DiagrammeR** on **CRAN** (version 0.8.2). If this code snippet doesn't work, could you try again with the latest version?

**Comment by happyshows** [comment]
somehow CRAN only release 0.81, will wait for a few hours and try again.

**Comment by happyshows** [comment]
@rich-iannone I figured out the issue, in my case, shape = plainText got overriden by style = 'filled'. should I set the style column to NA?

**Comment by rich-iannone** [comment]
@happyshows it's not ideal but try setting the appropriate field in the `style` column to `""`.

**Comment by happyshows** [comment]
sure, that's what I did later on
