### ISSUE TITLE
error when sending tbl_df object (as nodes_df, edges_df) into create_graph

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#159]
since the classes of ndf,edf are "tbl_df"     "tbl"        "data.frame"

It will cause a failure in below if clause
```
In if (class(edges_df) == "data.frame") { :
  the condition has length > 1 and only the first element will be used
```

Can this be changed to %in% instead of ==?

**Comment by timelyportfolio** [comment]
`inherits(edges_df,"data.frame")` probably best way to handle.

**Comment by ramnathv** [comment]
I have had really bad experiences using code that resembles `class(x) == "foo"`. Always use `inherits(x, "foo")`.

**Comment by stephlocke** [comment]
I just forked the repo to do this - will submit a PR request in the next day
