### ISSUE TITLE
Graph Nodes Alignment

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#161]
Hi,

I noticed that when the graph canvas size becomes big, the graph is centered in the canvas.

Is there a way to specify the first nodes should start from left or right.

The reason is I'm dynamically generating the graph and canvas size on shiny, however when canvas size becomes unnecessarily big, user always needs to scroll to the middle of canvas.

**Comment by rich-iannone** [comment]
@happyshows there must be a way! I think it may have something to do with making a cluster and then aligning that cluster. I'll have to dig into the Graphviz docs to find out more, however.

**Comment by timelyportfolio** [comment]
Most likely has to do with these [lines](https://github.com/rich-iannone/DiagrammeR/blob/master/inst/htmlwidgets/grViz.js#L19-L27) which provides the nice benefits of responsiveness but also likely results in the behavior @happyshows mentions.  We could make this optional, but would also have to put a lot of extra effort into other methods of sizing and positioning.
