### ISSUE TITLE
Deploying Shiny Site

### ISSUE THREAD

**Issue by rachwhatsit** [rich-iannone/DiagrammeR#165]
Hi all,

I'm working on an shiny app that has an interactive mind map bit. I'm working in Rstudio, and I can run an app locally with DiagrammeR no problem. The trouble is that when I deploy, all of a sudden I get this: 
ERROR: could not find function "grVizOutput"

ui.R 
`shinyUI(fluidPage(
  titlePanel("censusVis"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Here goes nothing...")
      
    ),
    mainPanel(grVizOutput("picture"))
  )
))
`
and server.R 

`library(DiagrammeR)

diagram <- "
digraph {

# graph attributes
graph [overlap = true]

# node attributes
node [shape = box,
fontname = Helvetica,
color = blue]

# edge attributes
edge [color = gray]

# node statements
A; B; C; D; E
F [color = black]

# node attributes
node [shape = circle,
fixedsize = true,
width = 0.9]

# node statements
1; 2; 3; 4; 5; 6; 7; 8

# edge statements
A->1; B->2                   // gray
B->3 [color = red]           // red
B->4                         // gray
C->A [color = green]         // green
1->D; E->A; 2->4; 1->5; 1->F // gray
E->6; 4->6; 5->7; 6->7       // gray
3->8 [color = blue]          // blue
}
"
shinyServer(
  function(input, output) {
    output$picture<-renderGrViz({
      grViz({
      diagram
    })
    })
   
  }
)`

I'm totally stumped.

**Comment by rich-iannone** [comment]
@rachwhatsit I'm having difficulty deploying because I'm doing it from the development machine (a different error occurs, not related to yours). I can check this on a different machine but this will take just a bit longer.

**Comment by rachwhatsit** [comment]
ARRRRGH, rookie mistake. I created and added a global.R file and it's good to go. I refuse to admit how long troubleshooting that took. 

Thanks for making a neat package. I have a very cool (er...IMHO) interactive Bayesian network loose on the internet now.

**Comment by rich-iannone** [comment]
@rachwhatsit thanks for the nice words (and for using the package!). Keep making cool stuff! Let me know if there are any other questions.

**Comment by ablazko** [comment]
Hi @rachwhatsit !

I'm going through the same problem that you've mentioned. The message `ERROR: could not find function "grVizOutput"` is really annoying me! But I didn't follow how did you get this work. 
Could you please walk me through your solution using global.R?

Even sometimes when I run local I get this error. :/

I appreciate a lot! ;)
Thanks

**Comment by ablazko** [comment]
Hi @rachwhatsit !

I've figure it out the solution, which was very simple after all!

**Solution**: just write a call of `library(Diagrammer)` in the ui.R file!

;-)

**Comment by rachwhatsit** [comment]
@ablazko Do you have a global.R file that loads all the packages you're using in your Shiny site? That's what did it for me. 

Full code of my example here: https://github.com/rachwhatsit/summer-decision-net
