### ISSUE TITLE
DOT code is constant, but the generated graph flips between 2 very different-looking graphs

### ISSUE THREAD

**Issue by GitChub** [rich-iannone/DiagrammeR#166]
This is very strange.  This problem occurs in a Shiny app.  I noticed that the graphs being rendered were sometimes correct and sometimes incorrect.  So, to remove all the possible sources of error in my code, I even changed the renderGrViz code to use *constant* DOT code for the graph.  Even then, it *still* flips (primarily) between two different outputs.

One clue is that (even in the minimal Shiny app at the bottom of this comment), the first graph generated is always correct.  So there must be some internal state information that is causing the mis-renderings.  This suggests that, in lieu of a bug fix, there might be a workaround that involves re-initializing the internal state of a library (?).
 
This is the code:
```
output$diagram <- renderGrViz({
    # This code is here just to have a reactive dependency that triggers re-running this renderGrViz
    if (isTRUE(input$flag)) {
        whatever <- TRUE
    }

    grViz("digraph {subgraph cluster1 {\n\n  '1' [label = 'A', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '2' [label = 'B', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '6' [label = 'C', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '15' [label = 'D', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '16' [label = 'E', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '18' [label = 'F', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n} subgraph cluster2 {\n\n  '3' [label = 'G', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '4' [label = 'H', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '10' [label = 'I', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '11' [label = 'J', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '12' [label = 'K', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '13' [label = 'L', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '14' [label = 'M', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n'6'->'4' [penwidth = '2'] \n'6'->'3' [penwidth = '2'] \n'2'->'3' [penwidth = '2'] \n'1'->'14' [penwidth = '2'] \n'1'->'13' [penwidth = '2'] \n'1'->'12' [penwidth = '2'] \n'1'->'11' [penwidth = '2'] \n'1'->'10' [penwidth = '2'] \n} }")

})
```

About half of the time, the graph is rendered correctly like this:
![image](https://cloud.githubusercontent.com/assets/9663419/13305126/0e75f11e-db27-11e5-8661-e99ca81445a9.png)

The other half of the time it's rendered incorrectly like this:
![image](https://cloud.githubusercontent.com/assets/9663419/13305085/bd68aee2-db26-11e5-8d36-045ab3f7a8a1.png)

Occasionally, there is a slight variation on the two previous graphs in which the tail of one of the edges coming out of the "C" vertex starts right at the letter "C" instead of starting at the edge of the box for "C".  That slight variation, which occurs about 1% to 2% of the time, looks like this:
![image](https://cloud.githubusercontent.com/assets/9663419/13305178/741287c6-db27-11e5-8609-f6c11bb0e2f9.png)
Or like this:
![image](https://cloud.githubusercontent.com/assets/9663419/13305198/9983029c-db27-11e5-8007-73f12c071cbd.png)

Any idea of what's going on here?

I've found that similar flipping occurs with other graphs with clusters in them.  When there are more than 2 clusters, it can flip between more than 2 different-looking renderings.

Note that it consistently renders correctly via this one-shot command in RStudio:
`grViz("digraph {subgraph cluster1 {\n\n  '1' [label = 'A', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '2' [label = 'B', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '6' [label = 'C', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '15' [label = 'D', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '16' [label = 'E', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '18' [label = 'F', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n} subgraph cluster2 {\n\n  '3' [label = 'G', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '4' [label = 'H', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '10' [label = 'I', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '11' [label = 'J', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '12' [label = 'K', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '13' [label = 'L', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '14' [label = 'M', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n'6'->'4' [penwidth = '2'] \n'6'->'3' [penwidth = '2'] \n'2'->'3' [penwidth = '2'] \n'1'->'14' [penwidth = '2'] \n'1'->'13' [penwidth = '2'] \n'1'->'12' [penwidth = '2'] \n'1'->'11' [penwidth = '2'] \n'1'->'10' [penwidth = '2'] \n} }")`

I should add that when I take that DOT code and plug it into the GraphvizFiddle at http://stamm-wilbrandt.de/GraphvizFiddle/ , it also renders correctly every time.  (Note that I did have to replace the occurrences of "\n" with " " and replace the single quotes with double quotes for that GraphvizFiddle to accept the DOT code.)

Finally, here's a minimal Shiny app based on the above code that you can run to reproduce the problem.  Sometimes you have to toggle the checkbox several times before the wrong version of the graph is displayed:
```
library(shiny)
library(DiagrammeR)

ui = shinyUI(fluidPage(fluidRow(
  column(width = 12
    ,checkboxInput('flag', 'Toggle this checkbox to get the graph to re-render: ', value = FALSE)
    ,grVizOutput('diagram')
  )
)))

server = function(input, output){
  output$diagram <- renderGrViz({
    # This code is here just to have a reactive dependency that triggers re-running this renderGrViz
    if (isTRUE(input$flag)) { whatever <- TRUE }      
    grViz("digraph {subgraph cluster1 {\n\n  '1' [label = 'A', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '2' [label = 'B', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '6' [label = 'C', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '15' [label = 'D', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '16' [label = 'E', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n  '18' [label = 'F', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#4CAF50'] \n} subgraph cluster2 {\n\n  '3' [label = 'G', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '4' [label = 'H', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '10' [label = 'I', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '11' [label = 'J', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '12' [label = 'K', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '13' [label = 'L', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n  '14' [label = 'M', penwidth = '2', shape = 'box', style = 'filled', fillcolor = '#789750'] \n'6'->'4' [penwidth = '2'] \n'6'->'3' [penwidth = '2'] \n'2'->'3' [penwidth = '2'] \n'1'->'14' [penwidth = '2'] \n'1'->'13' [penwidth = '2'] \n'1'->'12' [penwidth = '2'] \n'1'->'11' [penwidth = '2'] \n'1'->'10' [penwidth = '2'] \n} }")
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by GitChub** [comment]
I found a fix for this in my own code.  You may have noticed that the edges portion of the DOT code was included within the subgraph curly braces.  It's a long story, but that's a consequence of the method I was using to generate the subgraphs and stitch together their DOT code. While GraphViz seemed to be able to handle that, it occurred to me that that's probably not the preferred structure; the edge definitions are probably best situated outside the curly braces for any subgraph.  e.g.:
`digraph {

subgraph cluster1 {\n\n  '1' [label = 'A'] \n  '2' [label = 'B'] \n  '6' [label = 'C'] \n  '15' [label = 'D'] \n  '16' [label = 'E'] \n  '18' [label = 'F'] \n
} 

subgraph cluster2 {'3' [label = 'G'] \n  '4' [label = 'H'] \n  '10' [label = 'I'] \n  '11' [label = 'J'] \n  '12' [label = 'K'] \n  '13' [label = 'L'] \n  '14' [label = 'M'] 
} \n

'6'->'4' [penwidth = '2'] \n'6'->'3' [penwidth = '2'] \n'2'->'3' [penwidth = '2'] \n'1'->'14' [penwidth = '2'] \n'1'->'13' [penwidth = '2'] \n'1'->'12' [penwidth = '2'] \n'1'->'11' [penwidth = '2'] \n'1'->'10' [penwidth = '2'] \n 

}
`

That fixed the problem.

Interestingly, the way that GraphViz lays out the diagram is still not entirely deterministic.  It will still flip between a "right hand" and "left hand" version of the layout for at least some graphs.  That's weird, but not a problem for me.  So I'm closing this issue.

**Comment by rich-iannone** [comment]
Thanks @GitChub ! You solved the issue faster than I could. And... the Graphviz codebase is not entirely clean and modular so there are all sorts of oddities from heuristics interacting with each other in strange ways.

**Comment by GitChub** [comment]
Thanks for looking into this Rich.  And, I should have said at the outset:  Great work on DiagrammeR!

**Comment by rich-iannone** [comment]
@GitChub Aww, thanks! I am glad that it's useful.
