### ISSUE TITLE
Error with set_op arg

### ISSUE THREAD

**Issue by cderv** [rich-iannone/DiagrammeR#167]
Hi, 

When using `select_nodes`, I tried to use `r set_op = "intersection"` as mentionned in the help page. 
It get me an error : 'nodes_combined' was not found.

The reason is that in the code, tests for `set_op` is not on `"intersection"` but `"intersect"` so 'nodes_combined' was not created.

````r
if (set_op == "union") {
    nodes_combined <- union(nodes_prev_selection, nodes_selected)
  }
  else if (set_op == "intersect") {
    nodes_combined <- intersect(nodes_prev_selection, nodes_selected)
  }
  else if (set_op == "difference") {
    nodes_combined <- setdiff(nodes_prev_selection, nodes_selected)
  }
```
I check on `select_edges` and it is the same.
So either the code has to be change or the documentation must be updated. 

a test may be done in the functions to check that `set_op` is one of `c("union", "intersect", "difference")`, may be with a `match.arg`, and throws an error otherwise.

I did not tried to do a pull request before deciding what is to be done.

**Comment by rich-iannone** [comment]
@cderv This caused general confusion for myself as well (and that has crept into the examples). Thank you for bringing this up and providing some solutions. I will address this very soon.

**Comment by rich-iannone** [comment]
@crderv Finally modified the help files associated with all functions that have the `set_op` arg. Thanks again for filing this issue.
