### ISSUE TITLE
Include Moderators in Graph

### ISSUE THREAD

**Issue by AndreWal** [rich-iannone/DiagrammeR#170]
Hi,

Thank you for providing the great package diagrammer.

One question:

Is it possible to create an edge that points from a node to another edge? Similar to a moderator/intervening variable?

Best,
André

**Comment by eborbath** [comment]
I was actually wondering about the same. Do you have a good suggestion for this? maybe I am missing something. I would like to make a simple moderated mediation graph.
Thanks for the package, it's really great!
