### ISSUE TITLE
Multiline labels

### ISSUE THREAD

**Issue by michsvob** [rich-iannone/DiagrammeR#172]
I can't find a possibility to split long label over multiple lines - is this even supported? 
Thanks

My code:
library(DiagrammeR)
dataNodes<-as.list(read.csv(file.path("/nodes.csv"),header=FALSE,sep=";"))
dataEdges<-as.list(read.csv(file.path("/edges.csv"),header=FALSE,sep=";"))

nodes <-create_nodes(
	nodes=dataNodes$V1,  
	label = dataNodes$V2,
	shape=dataNodes$V3,
	color=dataNodes$V4,
	fontcolor=dataNodes$V5)

edges <-create_edges(
    	from = dataEdges$V1,
    	to=dataEdges$V2,
    	label = dataEdges$V3)

graph <- create_graph(
	nodes_df=nodes,
        edges_df=edges)

render_graph(graph)

**Comment by michsvob** [comment]
I found the way - splitting each label by inserting \n into the string to be split. Though it might be better to add newline somehow automatically when reaching the width of the node element.

**Comment by rich-iannone** [comment]
@michsvob sorry for the delay, but yeah, it's `\n` to force a line break. What you're suggesting about the automatic line break is interesting and I think would be a great enhancement! I'll make a separate issue and label it as an **enhancement** to remind myself to work on it.
