### ISSUE TITLE
export_graph does not work with mermaid

### ISSUE THREAD

**Issue by stephlocke** [rich-iannone/DiagrammeR#174]
If I try using the latest dev version of DiagrammeR to do
```
DiagrammeR("graph TB 
           A-->B") %>% 
  export_graph("rand.png")
```
I get `Error in file.exists(diagram) : invalid 'file' argument`. If I use the other diagram engine things work fine:
```
create_random_graph(2,1) %>%
  export_graph("rand.png")
```

## If it's a bug
Can we fix it?

## If it's not a bug but a limitation
It would be helpful if there was validation on the function export_graph() to provide a more informative error message, and the documentation for export_graph should express this limitation.

**Comment by chelliusbee** [comment]
Just piping up to confirm this, I get the same error with mermaid and export_graph.

**Comment by rich-iannone** [comment]
Sorry for the long wait on this. This is currently a limitation but I will work on making 'export_graph()' produce graphical output files with mermaid and Graphviz graph definitions. This is high priority and the next feature to add.

**Comment by rich-iannone** [comment]
@timelyportfolio not sure if you have time for this, but `mermaid.js` does have SVG support. I just don't know how to expose it with `V8` in the `export_svg()` function (that currently creates SVG text for Graphviz). What might take me hours might take you much less than one, so, if you're interested, your help here would be appreciated.
