### ISSUE TITLE
example csv files missing?

### ISSUE THREAD

**Issue by tbates** [rich-iannone/DiagrammeR#178]
[home page example](https://github.com/rich-iannone/DiagrammeR) uses calls like:

    system.file("examples/contributors.csv", package = "DiagrammeR")

These files appear to be missing, and `ls(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/DiagrammeR/examples
)` tells me that examples is empty. Are the csvs supposed to ship with the package?

An alternative would be to move these into the data folder (currently empty)

    data(package="DiagrammeR") # no data sets

**Comment by rich-iannone** [comment]
@tbates There are indeed supposed to be CSV files shipping with the package for the purpose of demonstrating some examples. I thought that `system.file` used the `/inst` folder as root, but I guess I was mistaken.

Putting the data in the `data` folder does seem sensible though, so, I'll do that. Thanks for letting me know about this!
