### ISSUE TITLE
Diagram renders in graphviz.app but gives error in .js

### ISSUE THREAD

**Issue by tbates** [rich-iannone/DiagrammeR#179]
This .gv file [tsls.txt](https://github.com/rich-iannone/DiagrammeR/files/235661/tsls.txt) (renamed for upload with .txt suffix) renders thus in graphviz.app on mac:
![tsls](https://cloud.githubusercontent.com/assets/736156/14803317/5347ff68-0b50-11e6-9757-dc5b5e32e9e8.png)

Drawn by Diagrammer() it gives the error below in the browser. Other models are drawing fine (which is fabulous!).

This is the in browser error:

<pre>
abort() at jsStackTrace@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:5:22072
stackTrace@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:5:22258
abort@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:28:10656
_abort@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:5:606487
B1@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:20:92486
Sf@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:11:127973
Lf@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:11:124094
vF@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:9:174897
xc@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:11:786
file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:28:403
ccallFunc@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:5:8402
file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/viz-0.3/viz.js:47:42
renderValue@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/grViz-binding-0.8.3/grViz.js:38:27
file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/htmlwidgets-0.6/htmlwidgets.js:610:30
forEach@[native code]
forEach@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/htmlwidgets-0.6/htmlwidgets.js:55:21
file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/htmlwidgets-0.6/htmlwidgets.js:542:14
forEach@[native code]
forEach@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/htmlwidgets-0.6/htmlwidgets.js:55:21
staticRender@file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/htmlwidgets-0.6/htmlwidgets.js:540:12
file:///var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpaEbHgU/viewhtmld875172461f/lib/htmlwidgets-0.6/htmlwidgets.js:623:38
</pre>

**Comment by rich-iannone** [comment]
I am experiencing the same error. Seems like it could be a bug in the version of *Graphviz* that *viz.js* is using. It's hard to pin down what's causing the error. Using `{rank = same; qtl X}` instead of `{rank = same; qtl X Y}` shows the drawing (of course `qtl`, `X`, and `Y` are no longer in the same rank because of this). Also, removing the label statement from `X -> Y [dir=both, label="-0.8"]` makes the drawing render. Could be the error is thrown from too many arrow/label elements being drawn to closely.

Perhaps a solution is to increase the minimum length of the arrows? I'll have to test this out a bit.

**Comment by tbates** [comment]
Thanks for looking into this. Here's another one if it helps to compare.

Pretty basic SEM model (from umx package) which renders in graphviz on mac (Version 2.39 (2.39.20141129.0545)), but fails in the viz.js library in browser render.

[AQ.txt](https://github.com/rich-iannone/DiagrammeR/files/237631/AQ.txt)
