### ISSUE TITLE
Tooltip doesn't Export to webpage

### ISSUE THREAD

**Issue by CW214** [rich-iannone/DiagrammeR#181]
First, this is a fantastic package.

When using tooltip (I want to show additional data than the node name within the shape) it works on the diagram within RStudio.  When I export (Save as Webpage in RStudio), the diagram is exported but the tooltip is now only the title in the shape, thus the node name.

**Comment by CW214** [comment]
Looked into it further. It seems to work on Chrome Version 50.0.2661.102. But not IE11 or Edge 25

**Comment by rich-iannone** [comment]
There seems to be a persistent issue where Chrome renders everything nicely but other browsers do not. I'll look into this.
