### ISSUE TITLE
Title on graph

### ISSUE THREAD

**Issue by CW214** [rich-iannone/DiagrammeR#182]
I would like to add a visible title to the diagram.  I have tried a number of different things. It could just be me but I could not find a solution after searching the different sources.

If this is already possible, could this be put into the documentation on the website. 

I want to make multiple diagrams in one go and a title on each of them would be helpful.

**Comment by GegznaV** [comment]
Are you searching for this?:

```
digraph with_title {
    graph [label = "Title of my graph"]
     A -> C;
```

}

![rplot03](https://cloud.githubusercontent.com/assets/12725868/17705777/46bade38-63e2-11e6-984c-72b13ef127a1.jpeg)

**Comment by rich-iannone** [comment]
@CW214 @GegznaV I was thinking of having this as an option in `render_graph()`. Perhaps I'll build that in very soon with some basic styling options.

**Comment by CW214** [comment]
That would be good thanks.

**Comment by rich-iannone** [comment]
@CW214 The option to add in a graph title has been implemented. Here is an example:

```R
library(DiagrammeR)

graph <- 
  create_graph() %>%
  add_n_nodes(2) %>%
  add_edge(1, 2)

graph %>% render_graph(title = "The Graph Title")
```

The graph output:

![graph with title](https://cloud.githubusercontent.com/assets/5612024/18318260/e68fa3e0-74d5-11e6-8dbb-08300114de04.png)

I will perhaps add in some options for styling and placement of the text but this is pretty good for now.

**Comment by vnijs** [comment]
Nice. Is something like this also possible for mermaid plots?

**Comment by JiaxiangBU** [comment]
Hi, @GegznaV , thanks for your minimal example.

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(DiagrammeR)
grViz("
digraph with_title {

graph [layout = dot,
       title = 'It isi a title']


node [shape = egg,
      style = filled,
      color = black,
      fontsize = 12,
      fontname = Helvetica,
      fontcolor = white,
      # label = ''
]

A -> C

}")
```

![image](https://user-images.githubusercontent.com/15884785/54907884-942cf480-4f21-11e9-8bcc-9f3728f395a3.png)


I just get this one. How can I edit it? Unfortunately, it shows that I just ask a question without thinking. But actuallly, I cannot find some tutorials on it.

**Comment by Nodeswitch** [comment]
@JiaxiangBU If you change to below, you'll get a title at the bottom. 

`graph [layout = dot,
       label = 'It isi a title']`

You'll get a title at the bottom. I'm unable to get it to appear at the top, however.

**Comment by JiaxiangBU** [comment]
Hi @Nodeswitch thanks for your reply, I find my code is wrong, the correct argument is `label` instead of `title`.

**Comment by DanielReedOcean** [comment]
@Nodeswitch This is a very late response, but `labelloc = t` places the title at the top.
