### ISSUE TITLE
grViz html widget does not work in Rcloud

### ISSUE THREAD

**Issue by gaborcsardi** [rich-iannone/DiagrammeR#183]
We have added htmlwidgets support to Rcloud, but unfortunately `grViz` does not work, because it suppresses the viewer.

Looks like the intent was to avoid some old RStudio versions, but the current way also avoids other viewers, like the one we defined for Rcloud. 

Would you be open to incorporate a simple fix that results the same behaviour is RStudio, but allows other viewers? E.g. something like 

```r
  viewer.suppress <- rstudioapi::isAvailable() && !rstudioapi::isAvailable("0.99.120")
```

here:
https://github.com/rich-iannone/DiagrammeR/blob/fdb32e80b1a635b2e260beabca7e23679739a860/R/grViz.R#L58

The original Rcloud issue for reference: https://github.com/att/rcloud/issues/2169#issuecomment-231205226

I can submit a small PR of course. Thanks!

**Comment by rich-iannone** [comment]
Gábor,

Good to hear from you! I’d love for the Graphviz-based visualizations in DiagrammeR to work with Rcloud.

Would you be able to send a quick PR with the change? It’s not so much that I’m lazy to do this, it’s more that I’d like to make sure it works without problems and, more importantly, I’d be honoured to have you in my list of contributors!

**Comment by gaborcsardi** [comment]
Haha, thanks, submitted a PR!
