### ISSUE TITLE
Drawing Bayesian Factor Graphs

### ISSUE THREAD

**Issue by Emaasit** [rich-iannone/DiagrammeR#185]
Is there functionality for drawing Bayesian Factor Graphs like those shown in the attached figures. There's a latex package that does that here: https://github.com/jluttine/tikz-bayesnet
![](https://camo.githubusercontent.com/fbf4d440a074ade5e339688cc84f942a38f01f23/687474703a2f2f692e696d6775722e636f6d2f43425a714c2e706e67)

**Comment by rich-iannone** [comment]
@Emaasit It's entirely possible to produce the above example graph with the package but there's no framework specific to Bayesian Factor graphs. It's seems like a good idea for you to begin an R package that can help with making these graphs. Now that Unicode support enabled in **DiagrammeR**, the math symbols won't pose a problem.
