### ISSUE TITLE
Incorrect international symbols: parameter `encoding = "UTF-8"` in `grViz` is needed

### ISSUE THREAD

**Issue by GegznaV** [rich-iannone/DiagrammeR#187]
I use international symbols in my DiagrammeR plots. Function `grViz` internally uses `readLines`. Unfortunately, there is no possibility to pass parameter `encoding`  to `readLines` via `grViz`. This leads to incorrect international symbols in my diagrams. I'd like to ask to **add parameter `encoding`** (or equivalent) **with default value set to ` "UTF-8"`** to function `grViz`.

_The illustration of my problem._

Contents of file "analysis_main.gv":
```
digraph International_symbols {
      A  [label = "Ąą Čč Ęę Ėė Įį"]
      C  [label = "Šš Ųų Ūū Žž"]
     A -> C;
 }
```
When I press _"Preview"_ button in RStudio, the international symbols are displayed incorrectly:  
![rplot01](https://cloud.githubusercontent.com/assets/12725868/17703928/fbf0599c-63db-11e6-86bb-8a061fa1fcbc.jpeg)

When I use following code, the result is also incorrect:
```
library(magrittr)

#  >>> INCORRECT RESULT <<< :(
"analysis_main.gv"     %>% 
DiagrammeR::grViz()

#  >>> INCORRECT RESULT <<< :(
"analysis_main.gv"     %>%
    readLines()                   %>%
    paste0(collapse = "\n")       %>% 
    DiagrammeR::grViz()
```
But when I add `encoding = "UTF-8"` the problem is **solved**:
```
#  >>> CORRECT RESULT <<< :)
"analysis_main.gv"     %>%
    readLines(encoding = "UTF-8") %>%
    paste0(collapse = "\n")       %>% 
    DiagrammeR::grViz()

```

![rplot02](https://cloud.githubusercontent.com/assets/12725868/17704023/53aef7ba-63dc-11e6-871b-15bb80a7d5c0.jpeg)

**Comment by GegznaV** [comment]
I think, the same applies to function `mermaid` which also lacks parameter `encoding`.

**Comment by rich-iannone** [comment]
@GegznaV Thanks for creating an issue for this and proposing the solution. It's now implemented internally. Any unicode symbols work now with no problem. Please test and let me know if there is still a problem with this.

**Comment by rich-iannone** [comment]
Will try to implement with `mermaid` next.

**Comment by rich-iannone** [comment]
@GegznaV Now implemented for `mermaid`. Thanks again for pointing this out.

**Comment by GegznaV** [comment]
Now encoding is correct using both `grViz` and `mermaid`. 
Thank you for quick response :+1:
