### ISSUE TITLE
2-digit footnote doesn't work?

### ISSUE THREAD

**Issue by pm0kjp** [rich-iannone/DiagrammeR#188]
Using 0.8.4 aka the CRAN version.

Using "crying baby decision tree" to illustrate some concepts.   When I have >9 nodes and want to label using @@ replacement, I get the following error.

```
Error in parse(text = split_references[i]) : <text>:1:1: unexpected '['
1: [
    ^
```

To reproduce:  code block below gives error .  Remove only the last footnote and it works (albeit without the right label on one of my nodes).  LMK if I can help by giving more information or sharing the coding effort.

Joy

```
grViz("
digraph myfirst {

node []
hungry [label = '@@1']
poopy [label = '@@2']
burp [label = '@@3']
wet [label = '@@4']
afraid [label= '@@10']

node [shape=Rhombus]
meal [label = '@@5']
grimacing [label = '@@6']
diaper [label = '@@7']
smell [label = '@@8']
noise [label = '@@9']

meal->hungry 
meal->grimacing 
grimacing->smell 
smell->poopy 
smell->burp
grimacing->diaper 
diaper->wet 
diaper->noise
noise->afraid

}
[1]: 'Hunger'
[2]: 'Poopy Diaper'
[3]: 'Needs a Burp'
[4]: 'Wet Diaper'
[5]: 'Time since last meal >=  3h?'
[6]: 'Grimacing?'
[7]: 'Time since last diaper change >= 3h?'
[8]: 'Bad smell?'
[9]: 'Loud Noise?'
[10]: 'Afraid'
")
```

**Comment by rich-iannone** [comment]
@pm0kjp Thanks for raising this issue, the code was indeed not parsing anything in the double digits. This is now fixed in the GitHub version of DiagrammeR. Would you be able to install that and then retry your code?

To install DiagrammeR from GitHub:
```r
install.packages('devtools')
devtools::install_github('rich-iannone/DiagrammeR')
```

Let me know if this still doesn't work after your testing. Thanks!

**Comment by daniclaar** [comment]
Hi,
I have just started using DiagrammeR, and am excited to try to use it for a couple of my current projects. Unfortunately, I'm having what appears to be the same problem as above, and I've tried your solution above, and it did not fix the problem.

I'm using R version 3.3.1 in RStudio Version 0.99.902 on OS X El Capitan 10.11.6. This code is within a RMarkdown file, but right now I'm just running the chunk independently.

When I try to use 2-digit footnotes in the standard download using the DiagrammeR version using install.packages, I get the same error as mentioned above:
```
Error in parse(text = split_references[i]) : <text>:1:1: unexpected '['  
1: [  
    ^
```

My code block is as follows:
```
grViz("
digraph boxes_and_circles {

# add node statements
node [shape=rectangle
      fontname=TimesNewRoman
      penwidth=2.0]
@@1; @@2; @@3; @@4; @@5; @@6; @@7; @@8; @@9; @@10

# add edge statements
@@1->@@2; @@2->@@3; @@3->@@4; @@4->@@5; @@5->@@6; @@6->@@7; @@7->@@8; @@8->@@9; @@9->@@10
[label='label!',
fontname=TimesNewRoman]

# add a graph statment 
graph [nodesep = 0.1]

}

[1]: NTotal_all
[2]: NTotal_CanAccess
[3]: NTotal_PossRel
[4]: NTotal_CoralResp
[5]: NTotal_CompENSO
[6]: NTotal_HasNandSD
[7]: NTotal_NoRevMA
[8]: NTotal_PrLit
[9]: NTotal_NoPseudo
[10]: NTotal_HasExtDat

")
```

All of the footnotes are defined previously by functions (and I have checked each of them to make sure that their outputs are as expected).

Next, I tried your suggestion to install the dev version from GitHub. However, once I restart RStudio and try to run the same code again, it just appears to be running, but nothing happens (no error message, no figure produced, etc) even after 10 minutes. This is true for both the exact code chunk above and if I remove footnote 10 (and all references to @@10). I had to force RStudio to Stop running the code both times.

Do you have any other suggestions that I can try on my end?

Thanks in advance!!
Danielle

**Comment by jpinero** [comment]
Hi! I also keep having this issue of 2-digit footnotes not working. I installed the version you suggested. Is it possible that it will be fixed ? Thanks
