### ISSUE TITLE
[FEATURE] automatic replacement of \n by <br />

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#19]
People working on R have not to care to what tech is used to render their graph.
In a diagram you may have several lines, they will usually be separated by \n.
Unfortunately Mermaid doesn't care of \n but takes <br /> into account.
May be it would be good to make this transformation by the R plugin.

Moreover I don't see any reason why someone would want to keep \n in the text of its diagram.

Best of all, it should take 1mn to implement the function.

**Comment by timelyportfolio** [comment]
Perhaps a reproducible example would clear up some of my confusion.  Would that be possible?  One other concern I have is that labeling appears likely to change based on https://github.com/knsv/mermaid/issues/58.

**Comment by pommedeterresautee** [comment]
I am thiking to something very simple like that:
```R
> library(stringr)
> "toto\ntata" %>% str_replace_all("\n", "<br/>")
[1] "toto<br/>tata"
```
I do it for my own code.
