### ISSUE TITLE
Keep character nodes after combine_nodes() 

### ISSUE THREAD

**Issue by iwi** [rich-iannone/DiagrammeR#190]
The last bit of the `combine_nodes()` function

```R
df_new[, 1] <-
  as.integer(df_new[, 1])
```

if the _nodes_ are characters (e.g. "z", "a", "b") they become integers (e.g. "3", "1", "2"). 

As a consequence the following `add_edge_df()` after `add_node_df()` example fails:

```R
library(DiagrammeR)
library(magrittr)

create_nodes(
  nodes = c(
    "a", "b"
  ),
  label = c(
    "A", "B"
  )
) -> nodes

create_graph(
  nodes_df = nodes
) -> g0

# check the nodes
g0$nodes_df

g0 %>%
  add_node_df(
    node_df = create_nodes(
      nodes = "c",
      label = "C"
    )
  ) -> g1

# check the nodes
g1$nodes_df  # the nodes identifiers have changed to integers

# then it fails
g1 %>%
  add_edge_df(
    edge_df = create_edges(
      from = "a",
      to = "b"
    )
  ) ->  g2
```

Would you want to:
- add a condition for the `as.integer(df_new[, 1])` so in case one of the dataframes nodes are character then do `as.character(df_new[, 1])`

- or you think that nodes should only be integers?

- or something else?

Happy to make the change and send you a pull request if that'd be helpful.

Thanks

**Comment by rich-iannone** [comment]
Hello,

The intent was to enforce the node ID to be integer only. Having this condition opens up a lot of possibilities for other aspects. However, this condition is not yet explicitly stated anywhere. For text labels and categories, the label and type attributes should be used. 

Let me know what you think of this change. 

Cheers,
Rich

**Comment by iwi** [comment]
hi,

Yes, the more I think about it the more it makes sense to keep it simple (integer). I suppose it also helps with compatibility when exporting to/importing from different graph formats.

Maybe worth stating it on the graph creation documentation or maybe forcing the _nodes_ type to be integer.

Thank you,
--
Iu

**Comment by rich-iannone** [comment]
Yes, a few good reasons were the compatibility/interchangeability with other formats and having more simplicity.

The goal is to restrict any setting of the node ID by the user (the IDs will essentially be auto-incrementing integers, and this occurs with some functions). The next step indeed is to change a few of the functions to remove the ability to manually set the ID values. 

Cheers,
Rich
