### ISSUE TITLE
Crashes when rendering graph

### ISSUE THREAD

**Issue by CianMurphy** [rich-iannone/DiagrammeR#195]
I have attached the objects I pass to create_graph. When I render it, I get the error appended to this file. It does resolve when I use a shorter label, eg 1 character. But this is not very useful. Ideally, I would have labels of upto around 100 characters with dataframes that may have more nodes and edges than this one too. Is this a RAM limit perhaps? My laptop has 8gb. 

[DiagrammerQuery.txt](https://github.com/rich-iannone/DiagrammeR/files/574019/DiagrammerQuery.txt)

**Comment by CianMurphy** [comment]
Hi Rich. Any progress on this?

**Comment by rich-iannone** [comment]
@CianMurphy Use the `create_node_df()` and the `create_edge_df()` functions to generate these data frame before using `create_graph().
