### ISSUE TITLE
DiagrammeR not rendering in RPresentation?

### ISSUE THREAD

**Issue by janvydra** [rich-iannone/DiagrammeR#199]
Simple diagram renders correctly in RMarkdown file, but when included in RPresentation it gives error "Error in file(con, "rb") : cannot open the connection".
Is it possible to include DiagrammeR in RPresentation?

```{r}
  DiagrammeR("
      graph LR
        A-->B
    "
  )
```

**Comment by rich-iannone** [comment]
@janvydra 

Sorry for getting back to you late. It seems that RPresentations don't like to display anything from the Viewer pane, even with the `webshot` package available. Here is a workaround (if you're willing to use graph objects):

```r
My Great Presentation
========================================================
author: your name
date: 2017-01-16
autosize: true

Slide With Graph
========================================================

```{r, include=FALSE}
library(DiagrammeR)

# Create a graph and save as a PNG file
create_graph() %>%
  add_n_nodes(5) %>%
  add_star(7) %>%
  export_graph("graph.png")

```

Here is a graph:

![A DiagrammeR graph](graph.png)
```

This allows you to generate a graph, saving it to disk as a PNG, and then simply displaying the image via Markdown.

**Comment by janvydra** [comment]
Thanks
