### ISSUE TITLE
add gh-pages branch for possible showcase?

### ISSUE THREAD

**Issue by timelyportfolio** [rich-iannone/DiagrammeR#20]
See https://github.com/hrbrmstr/metricsgraphics/issues/12#issuecomment-69330893.  @jjallaire, would `DiagrammeR` be ok for the showcase?  Thanks to the resolve of @rich-iannone it was accepted to CRAN today.  He also did a nice job documenting and adding examples.  I would think adding gh-pages using existing stuff or just the vignette would be relatively easy.  I just posted [this](http://www.buildingwidgets.com/blog/2015/1/8/week-01-easy-flowcharts-and-diagrams-diagrammer) with a couple more examples.

**Comment by jjallaire** [comment]
Looks really cool! I'd definitely consider adding that to the list if it
had a nice set of gh-pages docs.

**Comment by rich-iannone** [comment]
Well, I think we'll get on making those gh-pages docs then! They will contain lots of examples.

**Comment by jjallaire** [comment]
Great! Let me know when it's ready and I'll add you to the showcase.

**Comment by rich-iannone** [comment]
@timelyportfolio thanks again for the help with git and with adding the files for the skeleton boilerplate. I'll have to begin work on putting together the basic sections in that branch. Then, content!
