### ISSUE TITLE
set height/width for renderDiagrammeR?

### ISSUE THREAD

**Issue by vnijs** [rich-iannone/DiagrammeR#200]
Is there a way to adjust the height for a graph when using `renderDiagrammeR`? I looked at the source code on GitHub and I see that `renderDiagrammeR` uses `DiagrammeROutput`. `DiagrammeROutput` has a height parameter set to 400px by default.

I tried creating a new function (see below). This worked but resulted in non-unique outputId values so I can't use it when there are multiple graphs. Ideally, I'd like the height to be adjusted based on the characteristics of the graph. Any suggestions?

```r
render.DiagrammeR <- function(object, ...) {

	## works when you only need one plot
	DiagrammeROutput <- function(outputId, width = '100%', height = 'auto') {
	     htmlwidgets::shinyWidgetOutput(outputId, 'DiagrammeR', width, height,
	                                                           package = 'DiagrammeR')
        }
        
        htmlwidgets::shinyRenderWidget(substitute(object), DiagrammeROutput,
                                 parent.frame(), quoted = TRUE)
}
```

**Comment by vnijs** [comment]
Would setting `height = 'auto'` be an option for `DiagrammeR::DiagrammeROutput`?

**Comment by rich-iannone** [comment]
It might be an option. Want me to set it as that and see if it works out? You could send me a PR also and I can quickly accept it.

**Comment by vnijs** [comment]
Works great in my application. PR created. Thanks!

**Comment by rich-iannone** [comment]
All done! If you have any more PRs like this in the future, don't hesitate to send them.
