### ISSUE TITLE
create_nodes() missing

### ISSUE THREAD

**Issue by wamserma** [rich-iannone/DiagrammeR#202]
create_nodes() has been removed in v0.9.0 breaking a few dependent packages on CRAN.

Please re-introduce (and probably add a deprecation warning along with a transition guide).

offending commit:
https://github.com/rich-iannone/DiagrammeR/commit/9b952eaa2418af020d2cd629640b48760c50024e

fallout (as of 2017-01-05):
https://cran.r-project.org/web/checks/check_results_GeneralTree.html
https://cran.r-project.org/web/checks/check_results_Wmisc.html
https://cran.r-project.org/web/checks/check_results_xgboost.html

please do revdep() checks: http://r-pkgs.had.co.nz/release.html#release-deps

**Comment by wamserma** [comment]
also: the README in the CRAN package and on master is outdated, referring to 0.8.4 being on CRAN instead of 0.9.0.

**Comment by rich-iannone** [comment]
@wamserma the README.md has been fixed (removed version number for CRAN package). Unfortunately, I cannot bring back the previous `create_nodes()` function or equivalent functionality. For your package, you could replace your use of `create_nodes()` with `create_node_df()` with only a few additional changes.

**Comment by wamserma** [comment]
Well, I think I got the creation of the graph structure working again, but the rendered graphs are still quite different from what I had before. Please have a look at https://github.com/wamserma/R-wmisc/tree/fixDgR
Just run the code from the tests and compare with what `readRDS("automat-visual-1.rds")` produces. With the new version the node "go" is not rendered and so on. I'd like to get the update for my package on CRAN as soon as possible, but with the current state of affairs, it looks like I have to remove DiagrammeR support.

**Comment by wamserma** [comment]
Ok, with the new `id`scheme one can no longer rbind node data frames. https://github.com/rich-iannone/DiagrammeR/issues/214

**Comment by wamserma** [comment]
And the different layout mentioned in https://github.com/rich-iannone/DiagrammeR/issues/202#issuecomment-277870532 was due to https://github.com/rich-iannone/DiagrammeR/issues/215
Workarounds implemented, please no more surprises.

**Comment by iainmwallace** [comment]
Awesome package -
Just an FYI, the create_nodes function is used a lot in the very beginner friendly documentation 
http://rich-iannone.github.io/DiagrammeR/ndfs_edfs.html
http://rich-iannone.github.io/DiagrammeR/graph_creation.html

It would be great if the documentation could be updated to reflect the current approach to building a graph.

**Comment by wamserma** [comment]
@iainmwallace There is already an issue open for that: https://github.com/rich-iannone/DiagrammeR/issues/208
