### ISSUE TITLE
Global attributes not working for DOT

### ISSUE THREAD

**Issue by Enchufa2** [rich-iannone/DiagrammeR#204]
With DiagrammeR 0.9.0 (CRAN version):

```r
create_node_df(1, label=c("this is a test")) %>%
  create_graph() %>%
  set_global_graph_attrs("layout", "dot", "graph") %>%
  set_global_graph_attrs("fontname", "sans-serif", "node") %>%
  set_global_graph_attrs("width", 3, "node") %>%
  render_graph()
```

![rplot1](https://cloud.githubusercontent.com/assets/4542928/21742885/471da20c-d4f8-11e6-9f7f-f3c4f2277a14.png)

As you can see, attributes `fontname` and `width` had no effect. But this works:

```r
create_node_df(1, label=c("this is a test"), fontname="sans-serif", width=3) %>%
  create_graph() %>%
  set_global_graph_attrs("layout", "dot", "graph") %>%
  render_graph()
```

![rplot2](https://cloud.githubusercontent.com/assets/4542928/21742896/70ee1594-d4f8-11e6-93c1-d5cd1ff59fc9.png)

**Comment by rich-iannone** [comment]
Ah, I see the problem. Try using `set_global_graph_attrs()` for the first setting (this wipes out defaults and replaces with a single attribute, then, use `add_global_graph_attrs()` for the rest.

**Comment by Enchufa2** [comment]
Thanks, your suggestion works. But I have to say that this is a bit counterintuitive for me for various reasons:

- The manual page for `set_global_graph_attrs()` does not mention that its invocation wipes out the defaults.
- It does not mention the existence of `add_global_graph_attrs()` either.
- From a `set_something()` function, I would expect just that: modify it with the provided value if exists or create it if does not exist.
- You can apply `set_global_graph_attrs()` or `add_global_graph_attrs()` without result and without getting any kind of warning.

I would suggest to

- add the functionality of `add_global_graph_attrs()` into `set_global_graph_attrs()` (without wiping anything).
- remove `add_global_graph_attrs()`.
- create a new function exclusively for wiping out the attribute table. For instance, `remove_global_graph_attrs(graph, attr=NULL, attr_type=NULL)`, which would remove all attributes by default or a specific one if it is specified.

Otherwise, if this design responds to a good reason that I don't see, then I would suggest at least to 

- document the behaviour.
- show a warning if a certain invocation does nothing.

**Comment by Enchufa2** [comment]
BTW, having two functions (set, add) for the same task may be problematic for adding attributes programmatically (in a loop or if you need to provide a callback for the task, for instance). This is the problem of #206 if I'm not mistaken.

**Comment by rich-iannone** [comment]
I really appreciate these recommendations and I will implement them. Agree that it is currently confusing, not well-documented, and otherwise not ideal for programmatic setting of attributes. I'll close the issue after modifying the package.

**Comment by guiastrennec** [comment]
I just noticed that the behavior of `set_global_graph_attrs()` (i.e clear previous attributes) is already creating issues in v0.9.1:

In this first example I can use the `rankdir`attr as expected:
``` r
create_random_graph(3, 2, set_seed = 2212) %>% 
  set_global_graph_attrs('layout', 'dot', 'graph') %>% 
  add_global_graph_attrs('rankdir', 'LR', 'graph') %>% 
  render_graph()
```
![screen shot 2017-03-09 at 13 16 40](https://cloud.githubusercontent.com/assets/7304883/23749901/c0da742e-04ca-11e7-9cf5-849c080ae8f0.png)

In this second example the attributes I had defined are ignored due to the internal use of `set_global_graph_attrs()` by `render_graph()` when a title is present. Furthermore, note that the title is not outputted.
```r
create_random_graph(3, 2, set_seed = 2212) %>% 
  set_global_graph_attrs('layout', 'dot', 'graph') %>% 
  add_global_graph_attrs('rankdir', 'LR', 'graph') %>% 
  render_graph(title = 'Hello world')
```
![screen shot 2017-03-09 at 13 16 26](https://cloud.githubusercontent.com/assets/7304883/23749889/afd7b6aa-04ca-11e7-989d-828056b2292d.png)

**Comment by rich-iannone** [comment]
@guiastrennec I've just fixed the issue above. Please test and let me know if there are still issues with the title.

I will now work toward implementing @Enchufa2 's suggestions for simplifying the addition / deletion of these attributes.

**Comment by guiastrennec** [comment]
@rich-iannone, the titles works perfectly for me with the latest fix. Thanks for that !
