### ISSUE TITLE
http://rich-iannone.github.io/DiagrammeR/graph_creation.html

### ISSUE THREAD

**Issue by jakubkuzilek** [rich-iannone/DiagrammeR#208]
The examples found on the page (http://rich-iannone.github.io/DiagrammeR/graph_creation.html) are not really working. For example, function create_nodes does not exist in the package (installed version 0.9.1 from Github).

**Comment by dmpe** [comment]
Hi @rich-iannone, 
the
code in 
```
###
# Create a simple graph
# and display it
###
```
should be 
```
library(DiagrammeR)

# Create a simple NDF
nodes <-
  create_node_df(
    n = 4,
    type = "number")

# Create a simple EDF
edges <-
  create_edge_df(
    from = c(1, 1, 3, 1),
    to = c(2, 3, 4, 4),
    rel = "related")

# Create the graph object,
# incorporating the NDF and
# the EDF, and, providing
# some global attributes
graph <-
  create_graph(
    nodes_df = nodes,
    edges_df = edges)

# View the graph
render_graph(graph)
```
I guess

**Comment by dani-too** [comment]
Hi all,

Does anyone know if there is a way to set the direction that nodes flow?

**Comment by olivroy** [comment]
This was fixed. Indeed, the function to use is `create_node_df()` to create nodes. Feel free to reopen a new issue if something can be improved.
