### ISSUE TITLE
Renamed functions?

### ISSUE THREAD

**Issue by jmgerson** [rich-iannone/DiagrammeR#209]
`library(DiagrammeR)
library(lavaan)

semPaths(fit3, intercept = FALSE, whatLabel = "est",
         residuals = FALSE, exoCov = FALSE)

fit3 %>% parameterestimates %>% sample_n(5)

paths <- fit3 %>%
  parameterestimates %>%
  select(lhs, op, rhs, est)
latent <- paths %>%
  filter(op == "=~") %>%
  select(nodes = lhs) %>%
  distinct %>%
  mutate(shape = "circle")
latent

`%not_in%` <- Negate(`%in%`)
manifest <- paths %>%
  filter(op != "~1", lhs %not_in% latent$nodes) %>%
  select(nodes = lhs) %>%
  distinct %>%
  mutate(shape = "square")
node_set <- combine_nodes(latent, manifest) ##### not working???
node_set

all_paths <- paths %>%
  filter(op != "~1") %>%
  mutate(label = round(est, 2)) %>%
  select(-est)
loadings <- all_paths %>%
  filter(op == "=~") %>%
  mutate(edge_from = lhs, edge_to = rhs, style = "dashed") %>%
  select(edge_from, edge_to, style, label)
loadings

regressions <- all_paths %>%
  filter(op == "~") %>%
  rename(edge_to = lhs, edge_from = rhs) %>%
  mutate(style = "solid") %>%
  select(edge_from, edge_to, style, label)

edge_set <- combine_edges(loadings, regressions) ### Combine edges also not working
edge_set

my_graph <- create_graph(
  nodes = node_set,
  edges_df = edge_set,
  graph_attrs = c("ranksep = 1"))

render_graph(my_graph)`

I'm trying to use the above code to create SEM diagrams. Most of the code works, however I think some of the functions have been renamed. I had to change `graphviz_graph` to `create_graph`and `graphviz_render` to `render_graph`. When I run the above code, I get "could not find function" error messages from `combine_nodes` and `combine_edges`. Does anyone know if these functions have also been renamed, and if so, what they have been changed to? I've not been able to find this information on the DiagrammeR website.

**Comment by rich-iannone** [comment]
Some functions have been renamed:

`combine_nodes` -> `combine_ndfs`
`combine_edges` -> `combine_edfs`

The website documentation has indeed fallen a bit behind (and I will address this). In the meantime, the in-package documentation is the best place for explanations and working examples.

**Comment by jmgerson** [comment]
Brilliant! Thanks so much!
