### ISSUE TITLE
edge_present() should support labels and fail gracefully

### ISSUE THREAD

**Issue by wamserma** [rich-iannone/DiagrammeR#212]
`edge_present(g,"foo"."bar")` should look up nodes by labels. This would be much better than the current

```r
# a huge set of labels
lab1 <- "foo"
lab2<- "bar"

# some code

cond1 <- paste0("label == \'",lab1,"\'")
cond2 <- paste0("label == \'",lab2,"\'")
from<-get_node_ids(graph, conditions = cond1)
to<-get_node_ids(graph, conditions = cond2)
edge_present(g,from,to)

> F
```
There is not much difference in using `mk_cond()` for paste0.

Also it should not fail with a stop when nodes are not present, but rather return `FALSE`. The stop-behaviour is not documented and counter-intuitive.

**Comment by rich-iannone** [comment]
@wamserma it took awhile but I managed to update this function (`edge_present()`) to accept node labels. There are no stopping conditions when node IDs or labels are not in the graph (results in `FALSE`). This is currently in the dev version of the package. I also rewrote `node_present()` to behave similarly.

Closing issue but do reopen if there are problems here.

**Comment by wamserma** [comment]
Please ping when this has matured to CRAN. I have to keep the workaround (changed to quosures) until then to avoid issues with my package on CRAN.
