### ISSUE TITLE
Problem in create_graph()

### ISSUE THREAD

**Issue by nicolassoarespinto** [rich-iannone/DiagrammeR#213]
The documentation for `create_graph` states that is possible to create a graph using `create_graph(nodes_df = df)`  where `df` is a data.frame with only  one column, named `nodes`.  

This doesnt work anymore in version  `0.9.0`, reproducible example below:

```
nd<- data.frame(nodes = c("A","B"))
ed<- data.frame(from = "A", to = "B")

create_graph(nd, ed) %>% render_graph()
```

I get an error:

`Error in '[.data.frame'(nodes_df, , i) : undefined columns selected`

In version `0.8.5` would result in:

![graph_a_b](https://cloud.githubusercontent.com/assets/10147479/22747165/61fa9dcc-ee0d-11e6-95dd-b75162694770.png)

I didn't find any notes about changes in this functionality in the new version release, am i missing something?

**Comment by rich-iannone** [comment]
The best documentation is currently in the R help pages for each function. The GitHub version of the package for now is probably the way to go until I submit a new version to CRAN.

The data frames that are acceptable to `create_graph()` are now different with `0.9.0`. I'd suggest using the `create_node_df()` and `create_edge_df()` functions, or, generating graph nodes and edges using `add_node()`/`add_n_nodes()` and `add_edge()`/`add_edges_w_string()`.

**Comment by bschneidr** [comment]
It seems that the R documentation for each function is no longer up-to-date (on either the CRAN or GitHub versions). According to the documentation, the following code has all the minimum columns. However, as you can see in the reprex, it fails with a kind of opaque error. Could the documentation be updated to specify the new minimum columns and formats for `node_df` and `edge_df`?

``` r
library(DiagrammeR)

nodes <- data.frame(id = 1L:2L,
                    label = c('a', 'b'))

edges <- data.frame(id = 1L,
                    from = 1L,
                    to = 2L)

create_graph(nodes, edges)
#> Error in `[.data.frame`(nodes_df, , i): undefined columns selected
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.1 (2017-06-30)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/New_York            
#>  date     2017-09-07
#> Packages -----------------------------------------------------------------
#>  package      * version  date       source        
#>  assertthat     0.2.0    2017-04-11 CRAN (R 3.3.3)
#>  backports      1.1.0    2017-05-22 CRAN (R 3.4.0)
#>  base         * 3.4.1    2017-06-30 local         
#>  bindr          0.1      2016-11-13 CRAN (R 3.3.2)
#>  bindrcpp       0.2      2017-06-17 CRAN (R 3.4.0)
#>  brew           1.0-6    2011-04-13 CRAN (R 3.3.2)
#>  colorspace     1.3-2    2016-12-14 CRAN (R 3.3.2)
#>  compiler       3.4.1    2017-06-30 local         
#>  datasets     * 3.4.1    2017-06-30 local         
#>  devtools       1.13.3   2017-08-02 CRAN (R 3.4.1)
#>  DiagrammeR   * 0.9.2    2017-09-06 CRAN (R 3.4.1)
#>  digest         0.6.12   2017-01-27 CRAN (R 3.3.2)
#>  downloader     0.4      2015-07-09 CRAN (R 3.4.1)
#>  dplyr          0.7.2    2017-07-20 CRAN (R 3.4.1)
#>  evaluate       0.10.1   2017-06-24 CRAN (R 3.4.0)
#>  ggplot2        2.2.1    2016-12-30 CRAN (R 3.4.0)
#>  glue           1.1.1    2017-06-21 CRAN (R 3.4.0)
#>  graphics     * 3.4.1    2017-06-30 local         
#>  grDevices    * 3.4.1    2017-06-30 local         
#>  grid           3.4.1    2017-06-30 local         
#>  gridExtra      2.2.1    2016-02-29 CRAN (R 3.3.0)
#>  gtable         0.2.0    2016-02-26 CRAN (R 3.3.1)
#>  hms            0.3      2016-11-22 CRAN (R 3.3.2)
#>  htmltools      0.3.6    2017-04-28 CRAN (R 3.4.0)
#>  htmlwidgets    0.9      2017-07-10 CRAN (R 3.4.1)
#>  igraph         1.1.2    2017-07-21 CRAN (R 3.4.1)
#>  influenceR     0.1.0    2015-09-03 CRAN (R 3.3.1)
#>  jsonlite       1.5      2017-06-01 CRAN (R 3.4.0)
#>  knitr          1.17     2017-08-10 CRAN (R 3.4.1)
#>  lazyeval       0.2.0    2016-06-12 CRAN (R 3.3.2)
#>  magrittr       1.5      2014-11-22 CRAN (R 3.3.1)
#>  memoise        1.1.0    2017-04-21 CRAN (R 3.3.3)
#>  methods      * 3.4.1    2017-06-30 local         
#>  munsell        0.4.3    2016-02-13 CRAN (R 3.3.1)
#>  pkgconfig      2.0.1    2017-03-21 CRAN (R 3.4.0)
#>  plyr           1.8.4    2016-06-08 CRAN (R 3.3.0)
#>  purrr          0.2.3    2017-08-02 CRAN (R 3.4.1)
#>  R6             2.2.2    2017-06-17 CRAN (R 3.4.0)
#>  RColorBrewer   1.1-2    2014-12-07 CRAN (R 3.3.1)
#>  Rcpp           0.12.12  2017-07-15 CRAN (R 3.4.1)
#>  readr          1.1.1    2017-05-16 CRAN (R 3.4.0)
#>  rgexf          0.15.3   2015-03-24 CRAN (R 3.3.2)
#>  rlang          0.1.2    2017-08-09 CRAN (R 3.4.1)
#>  rmarkdown      1.6      2017-06-15 CRAN (R 3.4.0)
#>  Rook           1.1-1    2014-10-20 CRAN (R 3.3.2)
#>  rprojroot      1.2      2017-01-16 CRAN (R 3.3.2)
#>  rstudioapi     0.6      2016-06-27 CRAN (R 3.3.1)
#>  scales         0.5.0    2017-08-24 CRAN (R 3.4.1)
#>  stats        * 3.4.1    2017-06-30 local         
#>  stringi        1.1.5    2017-04-07 CRAN (R 3.3.3)
#>  stringr        1.2.0    2017-02-18 CRAN (R 3.3.2)
#>  tibble         1.3.4    2017-08-22 CRAN (R 3.4.1)
#>  tidyr          0.7.1    2017-09-01 CRAN (R 3.4.1)
#>  tools          3.4.1    2017-06-30 local         
#>  utils        * 3.4.1    2017-06-30 local         
#>  viridis        0.4.0    2017-03-27 CRAN (R 3.3.3)
#>  viridisLite    0.2.0    2017-03-24 CRAN (R 3.3.3)
#>  visNetwork     2.0.1    2017-07-30 CRAN (R 3.4.1)
#>  withr          2.0.0    2017-07-28 CRAN (R 3.4.1)
#>  XML            3.98-1.9 2017-06-19 CRAN (R 3.4.0)
#>  yaml           2.1.14   2016-11-12 CRAN (R 3.3.2)
```

</details>

**Comment by rich-iannone** [comment]
Thanks for calling attention to this. It is the `type` column that is missing from the ndf. I will update the documentation and provide the updated specifications for these data frames. 

I'll also relax the requirements a little. For instance, I will make tibbles and data tables work. Plus, I should not be so strict on the column order.

**Comment by bschneidr** [comment]
Ahh, ok. That would be great! In the meantime, thanks for telling me what I was missing (the `type` column).

**Comment by rich-iannone** [comment]
@bschneidr I've updated the internal documentation for `create_node_df()` and `create_edge_df()`. It now states which columns are necessary (and which column classes they should have).

I will get onto the second part (accepting tibble / data table objects as ndfs/edfs) very soon. Closing this issue now, however, as the second task is covered in another issue. Please re-open if there are still problems with the first task.

**Comment by Maddocent** [comment]
For those that are running into this: I just noticed that the edge_df needs a column called `rel` indicating the relationship (type?). There is no need for a type column as far as I noticed. I am on version of DiagrammeR: DiagrammeR_1.0.9.9000

As far as I can see with running `?create_graph`, this is not included in the documentation.
