### ISSUE TITLE
Setting of graph layout is ambiguous

### ISSUE THREAD

**Issue by wamserma** [rich-iannone/DiagrammeR#215]
`render_graph()` has an argument `layout` that is only used for `vivagraph`. The layout for graphviz needs to be set with something like 
```r
 g <-
   g %>%DiagrammeR::set_global_graph_attrs("layout","dot",attr_type = "graph")
```
Yet, the value of `layout` is available when `render_graph` calls `generate_dot()` (https://github.com/rich-iannone/DiagrammeR/blob/master/R/render_graph.R#L120). The layout should be passed and override any layout set in the graph object. 

Furthermore `create_graph()` should set a default layout of `dot` instead of `neato` for directed graphs. This is what a user expects when no layout is given and corresponds to behaviour pre-DiagrammeR-0.9
As http://graphviz.org/ says:
> ***dot*** - "hierarchical" or layered drawings of directed graphs. This is the default tool to use if edges have directionality.

**Comment by rich-iannone** [comment]
Removed Vivagraph and any settings required for it. The `layout` argument for `render_graph()` has been removed.

**Comment by skanskan** [comment]
Then how can we force Diagrammer to use a certain layout?
For example I would like to have all nodes aligned along a straight line.
such as this:

![untitled](https://user-images.githubusercontent.com/4120283/31080685-b52c5d6a-a789-11e7-9913-05cee50f56f9.png)

**Comment by wamserma** [comment]
@skanskan `layout` was only passed to Vivagraph (support has been removed). The layout needs to be adjusted by setting the graph attributes using a value that is supported by the chosen rendering tool. DiagrammeR itself does not render the graph, it hands off this task.
With other words: You might have to provide your own layout engine for graphviz and then put that name into the graph attributes.

**Comment by skanskan** [comment]
Could you please tell me how to create this simple graph:
https://stackoverflow.com/questions/46524490/how-to-create-a-directed-network-graph-with-aligned-nodes-in-r
nobody has provided any solution with diagrammer.

library(DiagrammeR)
library(visNetwork)

```
from=c("A","A","A","A","B","B","B","C","C","D")
to=c("B","C","D","E","C","D","E","D","E","E")
nodesd=c("A","B","C","D","E")
nodes <- create_node_df(  n=length(nodesd), label=nodesd,  width=0.3) 
edges <- create_edge_df(from = factor(from, levels=nodesd), to = factor(to, levels=nodesd), rel = "leading_to")   
graph <- create_graph(nodes_df = nodes, edges_df = edges)
render_graph(graph)
```

**Comment by wamserma** [comment]
@skanskan This is currently not possible with DiagrammeR. You may get something close if you find a way to assign ranks to the nodes that are then used in the dot output (see http://graphviz.org/pdf/dotguide.pdf).
Computing and assigning the ranks can be done in a custom wrapper of `render_graph()`, e.g. by calling `DiagrammeR::get_min_spanning_tree()` and properly traversing the result.
Alternatively you can directly hand over positional data that should be used in generating the dot code: https://github.com/rich-iannone/DiagrammeR/blob/67cf57ad6a67eb911ac6937c725cc40e4866ff6f/R/generate_dot.R#L254-L255

**Comment by rich-iannone** [comment]
@skanskan would something like this work for you?

```r
create_graph() %>%
  add_node(x = 0, y = 0) %>%
  add_node(x = 1, y = -1) %>%
  add_node(x = 2, y = -2) %>%
  add_node(x = 3, y = -3) %>%
  add_node(x = 4, y = -4) %>%
  add_edge(1, 2) %>%
  add_edge(1, 3) %>%
  add_edge(2, 3) %>%
  add_edge(2, 4) %>%
  add_edge(2, 5) %>%
  add_edge(2, 5) %>%
  add_edge(2, 5) %>%
  add_edge(4, 5) %>%
  add_edge(3, 5) %>%
  select_edges() %>%
  add_global_graph_attrs(
    attr = "splines",
    value = "spline",
    attr_type = "graph") %>%
  render_graph()
```

It makes this:

<img width="538" alt="screen shot 2017-10-10 at 3 56 52 pm" src="https://user-images.githubusercontent.com/5612024/31414620-ab0d3eee-add3-11e7-8f70-0a6793da4507.png">


Another option is to replace `value = "spline"` with `value = "ortho"`:

<img width="537" alt="screen shot 2017-10-10 at 3 58 00 pm" src="https://user-images.githubusercontent.com/5612024/31414647-d1f12a8e-add3-11e7-8eb7-d5d2410cf89b.png">

I tried forcing the length/curvature of the lines to be different but no success there.

**Comment by skanskan** [comment]
Yes, thank you very much.  In the meantime I did it with tikz, now I must decide what methodology is better. Regards.
