### ISSUE TITLE
Add option gradientangle

### ISSUE THREAD

**Issue by guiastrennec** [rich-iannone/DiagrammeR#221]
Hi,

The option `gradientangle` for nodes filling is currently ignored by DiagrammeR would it be possible to add it to the list of supported node options?

Example:
```r
library(DiagrammeR)
ndf   <- create_node_df(n = 1, fillcolor = 'orange:blue', gradientangle = 90)
graph <- create_graph(nodes_df = ndf)
cat(generate_dot(graph)) # Does not contain gradientangle
```

**Comment by rich-iannone** [comment]
@guiastrennec Just pushed the change that supports `gradientangle` as a node attribute.

**Comment by guiastrennec** [comment]
Thank you for the super fast response to my issue :-) Works great !

**Comment by rich-iannone** [comment]
@guiastrennec haha, yeah, I guess you can say I knew where the problem was!
