### ISSUE TITLE
add vignette for sequence diagram

### ISSUE THREAD

**Issue by timelyportfolio** [rich-iannone/DiagrammeR#23]
With pull #22 we add an example of a sequence diagram, but I also think it would be nice to have a dedicated vignette to offer some discussion and examples of sequence diagrams.

**Comment by rich-iannone** [comment]
I think that's a good idea. Want me to take a stab at the vignette?

**Comment by timelyportfolio** [comment]
For now, I think a showcase vignette would be more important.  Think we have enough examples already to put together.

**Comment by rich-iannone** [comment]
@timelyportfolio not sure if this can be sufficiently handled by documentation on the DiagrammeR website. The vignette in the package is looking a little stale right now. Would it be wise to discontinue the vignettes in favor of docs on the website?
