### ISSUE TITLE
Import warning when building in DiagrammeR on R 3.4.1

### ISSUE THREAD

**Issue by vnijs** [rich-iannone/DiagrammeR#235]
FYI When building a package that imports `DiagrammeR` I'm getting the warning below. To check if this was an issue in my own code I cloned the latest version of `DiagrammeR` from GitHub, built the package, and got the same warning message in R 3.4.1 on Mac (El-Capitan)

```r
Warning: replacing previous import ‘scales::viridis_pal’ by ‘viridis::viridis_pal’ when loading ‘DiagrammeR’
```

**Comment by rich-iannone** [comment]
@vnijs I think I know what the problem is here and I'm pretty sure I can fix this.
