### ISSUE TITLE
Support for Clusters?

### ISSUE THREAD

**Issue by sb3rg** [rich-iannone/DiagrammeR#236]
Are there plans for introducing rendering of clusters/subgraphs functionality as is present in DOT?  I feel like this is a native feature in DOT and it's curious that your documentation mentions nothing of generating nested graphs within nodes, especially with some of the newest changes to the API.  You used to have a create_subgraph function, now that's missing/not available.

**Comment by nicholaelaw** [comment]
Do you mean [this](http://rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html#examples)? (Scroll down a bit, to the 'R and RStudio information' graph).

**Comment by rich-iannone** [comment]
@sb3rg @nicholaelaw It's in there! Should I close the issue?

**Comment by nicholaelaw** [comment]
Sure. If there are no more questions, please close.

**Comment by Enchufa2** [comment]
And is this possible programmatically? I mean, using `create_graph` from nodes&edges data frames.
