### ISSUE TITLE
Updates to scales package will cause warning in DiagrammeR installation

### ISSUE THREAD

**Issue by karawoo** [rich-iannone/DiagrammeR#237]
The next release of the [scales](https://github.com/hadley/scales) package contains a function called `viridis_pal()`. This will cause a warning when DiagrammeR is installed, because DiagrammeR imports both `scales` and `viridis` (which also has a `virids_pal()` function). Just wanted to give a heads up that DiagrammeR may need to be more explicit about which functions it imports from these packages to avoid this warning.

**Comment by rich-iannone** [comment]
Thanks for this early warning! Will fix this shortly.

**Comment by karawoo** [comment]
👍  Just so you know, we're planning to submit the next scales release on August 21.

**Comment by rich-iannone** [comment]
@karawoo thanks for sharing the submission date. Currently working towards getting the package to build with no errors/warnings... it's taking a bit more time than I'd like but I think I should be able to submit to CRAN by the scales submission date.

**Comment by rich-iannone** [comment]
...and, forgot to mention, the fix in question has been implemented in the dev version.
