### ISSUE TITLE
v0.9.1 no longer compatible with R-oldrel (3.3.3)

### ISSUE THREAD

**Issue by achubaty** [rich-iannone/DiagrammeR#240]
The latest `DiagrammeR` version depends on `grDevices >= 3.4.0`. Since this is a base package, you really should be defining the dependency against the R version instead (R >= 3.4.0) to prevent errors on earlier R versions.

For example, `DiagrammeR` fails to install on R-oldrel (3.3.3):

```r
* installing *source* package ‘DiagrammeR’ ...
** package ‘DiagrammeR’ successfully unpacked and MD5 sums checked
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘grDevices’ 3.3.3 is already loaded, but >= 3.4.0 is required
ERROR: lazy loading failed for package ‘DiagrammeR’
* removing ‘/usr/local/lib/R/site-library/DiagrammeR’
```

See also a recent [r-pkg-devel thread](https://stat.ethz.ch/pipermail/r-package-devel/2017q3/001753.html).

**Comment by achubaty** [comment]
Furthermore, the fact that this package is no longer available for R 3.3.3 is problematic (and didn't CRAN complain to you about this?).

I'm not sure what specifically you use in `grDevices` 3.4.0, but can this be changed to be backward compatible with 3.3.3? Perhaps make that code conditional on the `grDevices` version available?

**Comment by Enchufa2** [comment]
This is causing problems to other depending packages. Moreover, DiagrammeR is using only two functions from `grDevices` (`colors` and `col2rgb`), and none of them have been recently changed (there is no mention to them in the R v3.4.0 release notes). So I think the v3.4.0 requirement should be dropped and this change should make it to CRAN ASAP.

**Comment by Enchufa2** [comment]
There is a function [here](https://stackoverflow.com/a/38687310/6788081) to check the minimum R version required by your dependencies. According to it, 

```r
min_r_version("DiagrammeR")
# [1] "3.2.0"
```

So it should be safe to declare `Depends: R (>= 3.2.0)`.

**Comment by rich-iannone** [comment]
Sorry for the delay in this. So, I will set R > 3.3 and remove the minimum version requirement for grDevices. This should restore backward compatibility for most people. 

Thanks for the advice on this and I apologize for the delay and issues this unexpected change has caused. I will push again to CRAN shortly. 

Let me know if there are other changes I should make.

**Comment by rich-iannone** [comment]
@Enchufa2 just saw your comment. I will drop the R requirement to 3.2.0.

**Comment by Enchufa2** [comment]
Great, thanks!

**Comment by rich-iannone** [comment]
Just made the change. Next thing is submit to CRAN right away.

**Comment by Enchufa2** [comment]
As a suggestion, and just to be safe in the future, TravisCI allows us to check the package against R oldrel, release and devel by adding the following to the .travis.yml file:

```
r:
  - oldrel
  - release
  - devel
```

Example [here](https://github.com/r-simmer/simmer/blob/master/.travis.yml).

**Comment by rich-iannone** [comment]
That's great, thanks! I will add this to the Travis YML file.

**Comment by rich-iannone** [comment]
The package has been submitted to CRAN. I'll close this issue once it is accepted.

**Comment by rich-iannone** [comment]
The package (v0.9.2) is now on CRAN.
