### ISSUE TITLE
Rstudio Doesn't help in Gantt chart

### ISSUE THREAD

**Issue by vikram-rawat** [rich-iannone/DiagrammeR#242]
when we save an MMD file. Rstudio highlights the text only when are trying to build a flow diagramme but for a Gantt chart it doesn't highlight anything. Kindly look into it. Please

**Comment by Enchufa2** [comment]
DiagrammeR does not control what RStudio highlights or not. You should redirect this feature request to RStudio instead.

**Comment by rich-iannone** [comment]
Quite a while back, JJ Allaire had the RStudio dev team put some engineering effort into highlighting Mermaid and Graphviz dot graph specifications. 

As the Gantt charting is a less developed feature, I don't think it's worth their time to address its code coloring.
