### ISSUE TITLE
Left dot label centering

### ISSUE THREAD

**Issue by instantkaffee** [rich-iannone/DiagrammeR#244]
```
digraph example{

  node1 -> node2 [label= "very long line1\lshort line2", labeljust="l"]
  
}
```
creates incorrect horizontal edge label centering  

![so_left](https://user-images.githubusercontent.com/3050723/29997131-ba8d2220-900b-11e7-8a8f-19525c86ee32.png)

**Comment by Enchufa2** [comment]
See [here](http://www.graphviz.org/doc/info/attrs.html#a:labeljust): labeljust only applies to "GC" (graph, cluster), not edges.
