### ISSUE TITLE
Documentation references render_graph( ... , output = "DOT") which is no longer supported

### ISSUE THREAD

**Issue by hennerw** [rich-iannone/DiagrammeR#246]
The graph creation tutorial page, "Viewing a Graph Object" section is out of date: http://rich-iannone.github.io/DiagrammeR/graph_creation.html

"If you'd like to return the Graphviz DOT code (to, perhaps, share it or use it directly with the Graphviz command-line utility), just use output = "DOT" in the render_graph() function. Here's a simple example: ..."

The function is now generate_dot, but as a new user it took me quite a bit of time to find that function.

**Comment by magjac** [comment]
This is still a problem in http://rich-iannone.github.io/DiagrammeR/graph_creation.html
