### ISSUE TITLE
Export mermaid graphics as SVG files?

### ISSUE THREAD

**Issue by Yatros** [rich-iannone/DiagrammeR#248]
Hello,

I know that exporting mermaid graphics as SVG files was an issue at some point: <https://github.com/rich-iannone/DiagrammeR/issues/174>

The thing now is that I cannot find if this feature was ever implemented and I am unable to export a Gannt graphic that I performed with the mermaid DiagrammeR function into SVG format.

Is there any way of exporting these type of objects into SVG format? Will this be an option in the near future?

Thank you very much,

Best,

Yatros

**Comment by rich-iannone** [comment]
I don't think that **mermaid** makes it easy to export SVG like **Graphviz** does. So, it was never implemented. Would be good to have this in the future... I'll keep an eye on **mermaid**'s development for examples on how this could be implemented. Closing for now though.

**Comment by vnijs** [comment]
FYI The [mermaid editor](https://mermaidjs.github.io/mermaid-live-editor/) now has an option to download SVG. Not sure how this is done but it sure would be a nice feature.
