### ISSUE TITLE
Edge width ?

### ISSUE THREAD

**Issue by skanskan** [rich-iannone/DiagrammeR#250]
Hoe can I link the edge width to the value of a variable?
create_edges() doesn't seem to have any option for that.

**Comment by rich-iannone** [comment]
Try this for creating a `width` node attribute based on scaling another variable:

```r
graph <-
  create_graph() %>%
  add_path(
    n = 4,
    data = 1:4) %>%
  rescale_node_attrs(
    node_attr_from = data,
    to_lower_bound = 0.25,
    to_upper_bound = 1.00,
    node_attr_to = width)

graph %>% render_graph()
```

If you have exactly what you need for the width in another variable, then you could copy that variable to the `width` attribute.

```r
graph_2 <-
  create_graph() %>%
  add_path(
    n = 4,
    data = c(0.25, 0.5, 0.6, 0.75)) %>%
  copy_node_attrs(
    node_attr_from = data,
    node_attr_to = width)

graph_2 %>% render_graph()
```

<img width="444" alt="screen shot 2017-10-17 at 9 16 16 am" src="https://user-images.githubusercontent.com/5612024/31664463-e23ff382-b31b-11e7-8cfe-c5f91029945a.png">

**Comment by skanskan** [comment]
But I want to change the width of the edges, not the width of the nodes.

**Comment by rich-iannone** [comment]
Ah, of course... I have another example that addresses the edge width:

```r
graph <-
  create_graph() %>%
  add_path(n = 4) %>%
  select_edges() %>%
  set_edge_attrs_ws(
    edge_attr = value,
    value = c(0.7, 1.3, 3.0)) %>%
  copy_edge_attrs(
    edge_attr_from = value,
    edge_attr_to = penwidth)

graph %>% render_graph()
```

That produces this graph:

<img width="437" alt="screen shot 2017-10-17 at 4 43 59 pm" src="https://user-images.githubusercontent.com/5612024/31685770-89cedec2-b35a-11e7-8a78-1e258b6c8895.png">

**Comment by skanskan** [comment]
OK, thank you, I'll try with my data.
Is it also possible to add a label to each edge?

**Comment by rich-iannone** [comment]
@skanskan yeah! Simple add the `label` attribute to the edf. Here's an example:

```r
# Edge -- label, color
graph <-
  create_graph() %>%
  add_path(
    n = 2,
    edge_aes = edge_aes(
      headlabel = "front",
      label = "mid",
      taillabel = "back",
      color = "hotpink")) 

graph %>% render_graph()
```

That produces this graph:

<img width="793" alt="graph_with_labels" src="https://user-images.githubusercontent.com/5612024/32426807-cd37d36e-c271-11e7-9c2e-7841b3cce1e1.png">

**Comment by rich-iannone** [comment]
Another way, through extension of the previous example, is to copy an existing edge attribute's values to a new `label` edge attribute.

```r
graph <-
  create_graph() %>%
  add_path(n = 4) %>%
  select_edges() %>%
  set_edge_attrs_ws(
    edge_attr = value,
    value = c(0.7, 1.3, 3.0)) %>%
  copy_edge_attrs(
    edge_attr_from = value,
    edge_attr_to = penwidth) %>%
  copy_edge_attrs(
    edge_attr_from = value,
    edge_attr_to = label)

graph %>% render_graph()
```

Giving you this:

<img width="790" alt="graph_labels_numeric_values" src="https://user-images.githubusercontent.com/5612024/32426921-4babe24e-c272-11e7-972b-4f05710e3705.png">

**Comment by rich-iannone** [comment]
Going to close this for now @skanskan but feel free to re-open if there are follow up questions.

**Comment by skanskan** [comment]
At the end I'm using Diagrammer to create my graphs, I can export them to svg or vectorial pdf.  But it has some disadvantages: It doesn't position the nodes well, and it doesn't position the labels well (quite often they olverlap with the edges or they mix with other).
Regards.
