### ISSUE TITLE
arrowhedad parameter

### ISSUE THREAD

**Issue by skanskan** [rich-iannone/DiagrammeR#255]
Hello.
I would like to draw the heads of my arrows with a smaller aperture angle,
I've labelangle but it doesn't seem to make any difference.
I've seen there is a  arrowhead parameter, by default  normal
What other values has this parameter?
What other things can I try.
I've also tried decorate and I'm not able to see any effect.

**Comment by rich-iannone** [comment]
@skanskan try the statement given below, it shows all the available types of arrowheads. Unfortunately, there are only a few arrowhead types and they are not very customizable. Graphviz has the option to use compounds arrowhead types (not formally supported in this package yet) but they won't really serve your needs.

```r

# Edge -- arrowhead, color
graph <-
  create_graph() %>%
  add_path(
    n = 5,
    edge_aes = edge_aes(
      arrowhead = c("normal", "vee", "tee", "dot"), 
      color = c("red", "blue", "orange", "purple"))) %>%
  add_path(
    n = 4,
    edge_aes = edge_aes(
      arrowhead = c("diamond", "curve", "icurve"), 
      color = c("steelblue", "purple", "gray65"))) %>%
  add_path(
    n = 4,
    edge_aes = edge_aes(
      arrowhead = c("inv", "crow", "none"), 
      color = c("forestgreen", "lightblue", "olivedrab"))) 

graph %>% render_graph(layout = "tree")
```
