### ISSUE TITLE
Could you uniform the git tag format?

### ISSUE THREAD

**Issue by twang2218** [rich-iannone/DiagrammeR#263]
Normally the git tag will be the form of `va.b.c`, I found there is an inconsistency in this project.

From version `0.1` to `0.5`, the git tag is in form of `a.b`. And from `0.6` there is a mix, most of them are `va.b.c`, however, `0.8.2` and `0.9.2` are in the form of `a.b.c`.

Which cost me some trouble to find the right version of the source code to view. I was looking for `v0.9.2`, and the last one is `v0.9.1` in the tag selection, so I thought you might forget tag this version, until I found the `0.9.2` tag.

<img width="767" alt="2018-01-05 09 28 15" src="https://user-images.githubusercontent.com/6299096/34587094-e1cf361a-f1fa-11e7-84a3-be64bd296407.png">

Could you uniform the git tag to `va.b.c` form? Thanks.

**Comment by rich-iannone** [comment]
This changes have now been made.
