### ISSUE TITLE
'add_edges_from_table()' cannot handle the node name with space in it.

### ISSUE THREAD

**Issue by twang2218** [rich-iannone/DiagrammeR#264]
I have struggled about this problem for several days. When I provided an edge table with 400 edges to `add_edges_from_table()`, I got only about 100 edges back if I call `get_edge_df()`, many edges are missing. I tried to manually add the missing edges by `add_edge()`, there is no problem. But whenever I use `add_edges_from_table()` there always many edges are missing.

After many try and fail, I decided to read the source code of `add_edges_from_table()` function, and then I found following undocumented behavior at <https://github.com/rich-iannone/DiagrammeR/blob/0.9.2/R/add_edges_from_table.R#L195-L203>:

```R
  # Expand the df to capture several space-delimited
  # values in the `to` column; drop NA values in the
  # `to_col` and the `from_col` columns
  csv <-
    csv %>%
    dplyr::mutate_(.dots = setNames(paste0("strsplit(", to_col, ", \" \")"), to_col)) %>%
    tidyr::unnest_(to_col) %>%
    tidyr::drop_na_(to_col) %>%
    tidyr::drop_na_(from_col)
```

Which basically says, if the content of `to` column contains `<SPACE>`, it will be treated as **space-delimited values** and be splitted and unnested. This behavior caused me the trouble, my node names contains space, which is valid for GraphViz.

Here is the demo code to show the problem:

```R
library(DiagrammeR)

cites <- data.frame(
  name = c("Sydney", "Los Angeles", "New York", "Beijing"),
  stringsAsFactors = F
)

paths <- data.frame(
  from  = c("Sydney", "Sydney", "Los Angeles", "Beijing"),
  to    = c("Beijing", "New York", "New York", "Los Angeles"),
  stringsAsFactors = F
)

p <- create_graph()
p <- add_nodes_from_table(p, cites, label_col = "name")
p <- add_edges_from_table(p, paths, from_col = "from", to_col = "to", ndf_mapping = "name")

print("str(paths):")
print(str(paths))
#  Output:
# [1] "str(paths):"
# 'data.frame':	4 obs. of  2 variables:
#  $ from: chr  "Sydney" "Sydney" "Los Angeles" "Beijing"
#  $ to  : chr  "Beijing" "New York" "New York" "Los Angeles"
# NULL

edge_df <- get_edge_df(p)
print("str(edge_df):")
print(str(edge_df))
# Output:
# [1] "str(edge_df):"
# 'data.frame':	1 obs. of  4 variables:
#  $ id  : int 1
#  $ from: int 1
#  $ to  : int 4
#  $ rel : chr NA
# NULL
```

As you can see, only `"Sydney" -> "Beijing"` remain, all other edges are missing.

**Comment by rich-iannone** [comment]
@twang2218 Sorry about this causing you some wasted time. I took that statement out awhile back in the dev version. Are you able to install from GitHub and try again? After that, these statements worked:

```r
#devtools::install_github("rich-iannone/DiagrammeR")
library(DiagrammeR)

cities <- 
  create_node_df(
    n = 4,
    label = c("Sydney", "Los Angeles", "New York", "Beijing"))

paths <- 
  tibble(
    from  = c("Sydney", "Sydney", "Los Angeles", "Beijing"),
    to    = c("Beijing", "New York", "New York", "Los Angeles"))

p <- 
  create_graph() %>%
  add_nodes_from_table(
    table = cities,
    label_col = label) %>%
  add_edges_from_table(
    table = paths,
    from_col = from,
    to_col = to,
    from_to_map = label) %>%
  drop_node_attrs(id_external)

p %>% get_node_df()
#>   id type       label
#> 1  1 <NA>      Sydney
#> 2  2 <NA> Los Angeles
#> 3  3 <NA>    New York
#> 4  4 <NA>     Beijing

p %>% get_edge_df()
#>   id from to  rel
#> 1  1    1  4 <NA>
#> 2  2    1  3 <NA>
#> 3  3    2  3 <NA>
#> 4  4    4  2 <NA>

p %>% render_graph()

```
<img width="678" alt="graph_diagram" src="https://user-images.githubusercontent.com/5612024/34634076-7ea1dd1e-f235-11e7-8462-da3876137d9f.png">

**Comment by twang2218** [comment]
Thank you for quick response. I installed the Github version, and changed the following part of the demo code:

```diff
-p <- add_edges_from_table(p, paths, from_col = "from", to_col = "to", ndf_mapping = "name")
+p <- add_edges_from_table(p, paths, from_col = "from", to_col = "to", from_to_map = "label")
```

This time, it's working now.

However, one behavior is changed in `add_nodes_from_table()`. Previously, the `label_col = "name"` will apply the value of `name` column to `label` column, and keep `name` column. But after I installed the Github master branch, the `name` column is removed.

```R
# 0.9.2
> get_node_df(p)
  id type      label       name
1  1 <NA>     Sydney     Sydney
2  2 <NA> Los Angles Los Angles
3  3 <NA>   New York   New York
4  4 <NA>    Beijing    Beijing
```

```R
# 0.9.3-master
> get_node_df(p)
  id type      label
1  1 <NA>     Sydney
2  2 <NA> Los Angles
3  3 <NA>   New York
4  4 <NA>    Beijing
```

Is this expected changes in the next version? I'm asking because I'm using the columns of `label_col`, `type_col`, `from_col`, `to_col` in the later attributes values, such as `tooltip`, and I wasn't expecting the column name changes. If it's expected, I think it should be documented as well.

I can only use CRAN packages in my working environment because the company's policy. But it's ok, I know the problem so I can walk around it for now until the next version is released. Thank you very much.
