### ISSUE TITLE
Issue with using DiagrammeR in Rmarkdown

### ISSUE THREAD

**Issue by pgok15** [rich-iannone/DiagrammeR#269]
When trying to use grViz in rmarkdown I run into the error message "Error: object 'cividis' is not exported by 'namespace:viridisLite' " This happens when I write my own code or use the example markdown code on the DiagrammeR website.

**Comment by rich-iannone** [comment]
@pgok15 could you provide an example of the code you used?

**Comment by pgok15** [comment]
@rich-iannone Here's what I have for the example markdown code:
---
title: "Untitled"
author: "pgok"
date: "February 8, 2018"
output: html_document
---

```{r, echo=F}
DiagrammeR::grViz("
                  digraph rmarkdown {
                  A -> B
                  }
                  ", height = 200)
```

And here is was I was initially using:
---
title: "Untitled"
author: "pgok"
date: "February 8, 2018"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=F}
DiagrammeR::grViz("
      digraph rmarkdown{
      graph [layout=neato]
      A [shape=box, label=Age]
      B [shape=box, label='Grey \nHair']
      A -> B [dir=both]
      }")

Thanks for the help, it's a neat package.

**Comment by pgok15** [comment]
@rich-iannone I think I managed to fix the issue. I removed DiagrammeR and viridisLite, then reinstalled viridisLite (with dep = T in the install command) and reinstalled DiagrammeR. It seems to work now. Thanks for looking at this.

**Comment by rich-iannone** [comment]
@pgok15 very glad you were able to resolve the issue! I will close the issue now.
