### ISSUE TITLE
Error: `UQ()` can only be used within a quasiquoted argument

### ISSUE THREAD

**Issue by Enchufa2** [rich-iannone/DiagrammeR#273]
`rlang` 0.2.0 is on CRAN, and `rlang::UQ` cannot be called directly anymore, which breaks `DiagrammeR`. All these calls must be substituted.

**Comment by rich-iannone** [comment]
@Enchufa2 I'm preparing DiagrammeR for a CRAN release and will be informing maintainers of dependent packages whether the candidate release raises issues R CMD check. Hoping to perform the revdep checks today and issue emails to the maintainers. Then there will be a 2 week window for the maintainers to resolve issues, after which I'll submit the package to CRAN.

In the meantime, the GitHub version of DiagrammeR does not produce these errors as invocations of `UQ()` were all modified.

I'll leave this issue open until the next CRAN release of DiagrammeR becomes available.

**Comment by Enchufa2** [comment]
I think that you should submit the new version ASAP: those packages depending on DiagrammeR **are already failing** on CRAN, so there's no need to wait 2 weeks.

In fact, I've already received a message from CRAN on a package of mine that states:

> Please correct before 2018-03-10 to safely retain your package on CRAN.

That's two weeks from now. So, please submit ASAP or we'll see our packages dropped from CRAN.

**Comment by rich-iannone** [comment]
@Enchufa2 Thanks for the advice. I've submitted the package to CRAN. I'll write a note here when it is available.

**Comment by Enchufa2** [comment]
Thanks, @rich-iannone.

**Comment by Enchufa2** [comment]
One question regarding the new version. What is the new way of setting the attributes? I found that `set_global_graph_attrs` is no longer available, but there is no guidelines about it in the NEWS file. Thanks in advance.

**Comment by Enchufa2** [comment]
Any news of what's happening on CRAN?

**Comment by rich-iannone** [comment]
I've mentioned to CRAN that I'm in communication with maintainers that are affected by the new release of DiagrammeR. CRAN indicated that the package would be published so long as such support is offered. I'm waiting for a response to that.

**Comment by rich-iannone** [comment]
@Enchufa2 It is now on CRAN (https://cran.r-project.org/web/packages/DiagrammeR/).
