### ISSUE TITLE
Are create_nodes() and create_edges() deprecated?

### ISSUE THREAD

**Issue by topspinj** [rich-iannone/DiagrammeR#284]
The [docs](http://rich-iannone.github.io/DiagrammeR/graphs.html) use create_nodes() and create_edges() but based on the code, these functions seem to be deprecated.

**Comment by Frank-Sw** [comment]
I have the same question as just used. Which functions have been used to replace these?

**Comment by timothytsai** [comment]
I'm seeing the same issue.  Perhaps `create_node_df()` and `create_edge_df()` are the intended replacement.

**Comment by reblake** [comment]
Same problem here. I'm trying to run the examples here http://rich-iannone.github.io/DiagrammeR/graph_creation.html and get the error "Error in create_nodes(nodes = 1:4, label = FALSE, type = "lower", style = "filled",  :   could not find function "create_nodes"".  If these functions have indeed been deprecated, the error should tell the user what the name of the new current function is.  As it is, this error is useless.

**Comment by tranktle** [comment]
# This simple example works for me using create_edge_df, create_edge_df and create_graph
# Create a simple NDF
nodes <-
  create_node_df(
    n=4, 
    nodes = 1:4,
    shape = c("circle", "circle", "rectangle", "rectangle"),
    type = "number")

# Create a simple EDF
edges <-
  create_edge_df(
    n=4, 
    from = c(1, 1, 3, 1),
    to = c(2, 3, 4, 4),
    rel = "leading_to"
    )

g <- create_graph(nodes_df=nodes, 
                  edges_df=edges)

render_graph(g)
