### ISSUE TITLE
object ‘cividis’ is not exported by 'namespace:viridisLite'

### ISSUE THREAD

**Issue by bgall** [rich-iannone/DiagrammeR#287]
Didn't see this in the issues, so reporting here. Receiving the error in the title. Looks like there is some issue with a dependency. Others have noted this here https://github.com/radiant-rstats/radiant.model/issues/3 and here https://github.com/rstudio/leaflet/issues/494

Here is a reproducible example:
```
install.packages("DiagrammeR")
library("DiagrammeR")

 DiagrammeR::mermaid(diagram = "graph TB
                                 1[Pre-Treatment Survey] --> 2[Production Task]
                                 2 --> 3[Information Treatment 1]
                                 3a(Random Inequality: <br/> High, Low) --> 3
                                 3b(Random Message: <br/> Person, Computer) --> 3
                                 3 --> 4[Guessing Task 1]
                                 4 --> 5[Post-Guessing Survey]
                                 5 --> 6[Information Treatment 2]
                                 6a(Random Inequality: <br/> High, Low) --> 6
                                 6b(Remaining message: Person, Computer) --> 6
                                 6 --> 7[Guessing Task 2]
                                 7 --> 8[Post-Guessing Survey]
                                 8 --> 9[Debriefing/Compensation]")
```

**Comment by zaindevel** [comment]
Error: object ‘cividis’ is not exported by 'namespace:viridisLite'
getting this error while running xgb.plot.multi.trees. Any help?

**Comment by bgall** [comment]
I found reinstalling viridis and viridisLite fixed things. I had only installed it as a dependency automatically but just do a install.packages("foo") to reinstall. Restart R and life should be good.
