### ISSUE TITLE
start version tagging in Github and add News.md

### ISSUE THREAD

**Issue by timelyportfolio** [rich-iannone/DiagrammeR#29]
I think this is developed enough to start version tagging on Github.  Also, adding a `News.md` (like [this](https://github.com/hadley/testthat/blob/master/NEWS.md)) will be helpful to track API changes, error fixes, and new features.

**Comment by rich-iannone** [comment]
Okay, just pushed a basic `NEWS.md` file. Have a look and feel free to add noteworthy items for the 0.1 (current) release. For versioning, I'll keep it simple with a *major.minor* versioning scheme.

**Comment by timelyportfolio** [comment]
great, guess I can close;  thanks

**Comment by timelyportfolio** [comment]
one other thing, can you tag on Github?

![image](https://cloud.githubusercontent.com/assets/837910/5722612/33203e94-9b03-11e4-9d43-b01b682fd203.png)

**Comment by rich-iannone** [comment]
Just tagged as v0.1. Description is a bit lacking and I may want to mirror what's in NEWS.md. I'll revise soon...

**Comment by rich-iannone** [comment]
Improved the descriptions for the releases.
