### ISSUE TITLE
`object 'set_global_graph_attrs' not found`

### ISSUE THREAD

**Issue by skanskan** [rich-iannone/DiagrammeR#291]
Some functions don't work anymore.

`set_global_graph_attrs(graph, "layout", "dot", "graph")`
`set_global_graph_attrs(graph, "splines","spline", "graph")`
`add_global_graph_attrs(graph, "rankdir", "TB", "graph")  `   

All the above lines cast this error:
`object 'set_global_graph_attrs' not found`

**Comment by skanskan** [comment]
I think I've found a solution.

replacing "set_global_graph_attrs" with "**add**_global_graph_attrs"

**Comment by overmar** [comment]
The primary side effect of this is that now any node that was resizing to fit the label is now of a fixed size. So far I haven't figured out a good way to change it back (node wrapping text) bc changing fixedsize = F, or fixedsize = shape do not render the same graphs.
