### ISSUE TITLE
Provide link from create_node_df to node_aes

### ISSUE THREAD

**Issue by jebyrnes** [rich-iannone/DiagrammeR#296]
In the help file for `create_node_df` (and I'm guessing for edges) there is a `...` for node attributes. Please link that to the helpfile for `node_aes` so that users don't spend a ton of time searching for what helpfile attributes are in. Makes our lives easier! And we can make more awesome graphs faster!

**Comment by rich-iannone** [comment]
This is a great idea, I'll do it!

**Comment by jebyrnes** [comment]
Awesome - should probably do the same for set_node_attrs, etc.
