### ISSUE TITLE
Install DiagrammeR on Ubuntu 18.04 - xml and rgexf error

### ISSUE THREAD

**Issue by kaktux** [rich-iannone/DiagrammeR#297]
Hi,

i am new to R (and RStudio) and trying to install DiagrammerR the "normal" way (via Rstudio) got me an error - xml and rgexf couldn't be installed.
I use Kubuntu 18.04 and the RStudio Server

To solve it i had to install the ubuntu package
r-cran-xml 
via terminal. xml is a dependency of rgexf - so this error disappeared afterwards

After this DiagrammeR could be installed in RStudio. 

Just in case someone has the same problem.

Edit:
this works for the R version included in the Ubuntu package repository.

If you use a newer version via cran-mirror you need to
sudo apt-get install libxml2-dev
to be able to install the missing xml dependency DiagrammR needs.

**Comment by TPei** [comment]
Nice, thanks!
