### ISSUE TITLE
DiagrammeR docs

### ISSUE THREAD

**Issue by Buyannemekh** [rich-iannone/DiagrammeR#309]
It seems to me that DiagrammeR docs is outdated and the [examples here ](http://rich-iannone.github.io/DiagrammeR/graphs.html)is not working. I am new to DiagrammeR and trying to a create a tree graph using `create_graph()` and `render_graph()` on the RStudio viewer. 
However, it looks like, for example, `create_nodes()` method has changed to `create_node_df()` and it takes different parameters than it is showing in the examples in the docs. Also, the `$dot_code` attribute is not there anymore?

**Comment by Buyannemekh** [comment]
also it does look like we can not create_graph() like following:

```# Create a graph object
graph <-
  create_graph(nodes_df = nodes,
               edges_df = edges,
               graph_attrs = "layout = neato",
               node_attrs = c("fontname = Helvetica",
                              "shape = circle"))
```

I want to create the graph using `layout = dot`, but it is not working.

**Comment by rich-iannone** [comment]
Try this site instead: http://visualizers.co/diagrammer/ (it’s at the top of the repo).

**Comment by Buyannemekh** [comment]
Thank you. But can I create a directed graph as hierarchies with DiagrammeR?

**Comment by Buyannemekh** [comment]
This was what I was looking for: 

```
f_graph <- 
  create_graph() %>% 
  add_balanced_tree(k=2, h=2) 

render_graph(f_graph, layout = "tree")
```

Now the layout attribute is not in `create_graph()`, but in `render_graph()`

**Comment by rich-iannone** [comment]
@Buyannemekh Thanks for finding that. I might put this layout information (since it's pretty important) in the pkg README.
