### ISSUE TITLE
Add example for use of external .mmd file as input to DiagrammeR function

### ISSUE THREAD

**Issue by rich-iannone** [rich-iannone/DiagrammeR#31]
Thanks @jjallaire for contributing the functionality for providing an external file (with the suggested .mmd extension) for input to the `DiagrammeR` function. It seems to work well enough now with the error notification. Question is whether to expose this functionality now in an example, or, wait to develop this further (and also wait for the syntax highlighting that an upcoming daily build of **RStudio** will offer)?

**Comment by jjallaire** [comment]
I'd say definitely yes expose it as an example as even without syntax highlighting I think a lot of users will appreciate being able to edit their diagram in external files (for both editing convenience and more easily re-using diagrams).

**Comment by rich-iannone** [comment]
@jjallaire okay thanks, just added in some explanatory text in the README.

**Comment by timelyportfolio** [comment]
do you plan to make the changes to the vignette also?

**Comment by rich-iannone** [comment]
Yes, that's right! I have to do that as well.

**Comment by rich-iannone** [comment]
This now has good examples and explanations, at least in the README file.

**Comment by timelyportfolio** [comment]
Was just looking at the Readme.md again, and I think on the `grViz` examples we can eliminate the `readLines(...)`. Not on machine to test though.

**Comment by rich-iannone** [comment]
I'll test that (much later tonight) and remove that statement if it's not necessary.

**Comment by timelyportfolio** [comment]
just checked and the bare string `""http://www.graphviz.org/Gallery/directed/fsm.gv.txt"` does not work nor should it since we check for connection.  `url("http://www.graphviz.org/Gallery/directed/fsm.gv.txt")` does work though.

**Comment by rich-iannone** [comment]
@timelyportfolio this is definitely not a priority so definitely don't worry about this one.
