### ISSUE TITLE
add support for html or R comments in .mmd files

### ISSUE THREAD

**Issue by Dripdrop12** [rich-iannone/DiagrammeR#315]
Here is a minimal example of what I want to be able to do:

Test.mmd
```
graph LR
  subgraph cleaning
    a[Raw text] --> b[clean text]
  end
  
  # This is an R comment
  <!--This is an html comment-->
```

**Comment by jmcastagnetto** [comment]
Second this request. Now that support for 7.0.0 has been merged in the main branch, it could be feasible.

I know you are implementing subgraphs/clusters for GraphViz too, and I guess it is not trivial. And, it would be nice to have also the mermaid "subgraph" command supported for flowcharts (see: https://mermaidjs.github.io/flowchart.html).

Ideally some code like the following:

```
Diagrammer::mermaid("
graph TD
A[Christmas] -->|Get money| B(Go shopping)
subgraph Nerve wracking
B --> C{Roll a dice}
end
subgraph Don't look
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  subgraph High Probability
    C-->|Three| G
    C-->|Four| G
    C-->|Five| G[A gift card]
  end
  subgraph Low Probability
    C -->|Six| F[fa:fa-car Car]
  end
end
")
```

Producing something similar to:

![screenshot_2018-12-12 online flowchart diagrams editor - mermaid live editor](https://user-images.githubusercontent.com/364668/49884250-6a344400-fe02-11e8-87cd-8d157ec4fa51.png)

(Edited online at: https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuc3ViZ3JhcGggTmVydmUgd3JhY2tpbmdcbkIgLS0-IEN7Um9sbCBhIGRpY2V9XG5lbmRcbnN1YmdyYXBoIERvbid0IGxvb2tcbiAgQyAtLT58T25lfCBEW0xhcHRvcF1cbiAgQyAtLT58VHdvfCBFW2lQaG9uZV1cbiAgc3ViZ3JhcGggSGlnaCBQcm9iYWJpbGl0eVxuICAgIEMtLT58VGhyZWV8IEdcbiAgICBDLS0-fEZvdXJ8IEdcbiAgICBDLS0-fEZpdmV8IEdbQSBnaWZ0IGNhcmRdXG4gIGVuZFxuICBzdWJncmFwaCBMb3cgUHJvYmFiaWxpdHlcbiAgICBDIC0tPnxTaXh8IEZbZmE6ZmEtY2FyIENhcl1cbiAgZW5kXG5lbmRcblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

**Comment by daauerbach** [comment]
@Dripdrop12 @jmcastagnetto Not sure whether it suits your needs but `%%` works to include comments within (at least flowchart) specification inline, in an .mmd and/or in the live editor. 

```r
DiagrammeR::DiagrammeR("
%% a comment

graph TD

%% another

id1(Start)-->id2(Stop)

    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5

%% and one more
")
```

Though note https://github.com/knsv/mermaid/issues/774

**Comment by Dripdrop12** [comment]
I was not aware of that solution! Thanks :) @jmcastagnetto feel free to re-open a different issue if yours is slightly different, but I'm going to close this out.
