### ISSUE TITLE
requireNamespace check makes no sense in export_graph.R?

### ISSUE THREAD

**Issue by Blackglade** [rich-iannone/DiagrammeR#341]
https://github.com/rich-iannone/DiagrammeR/blob/351d787af8982f3c221d91c06a5550408e56be5e/R/export_graph.R#L156

I don't understand this code here. If the user didn't have DiagrammeRsvg installed, the requireNamespace if statement would fail and thus it wouldn't execute any of the code inside the if statement, yet inside that if statement the following code is written:
```
 if (!("rsvg" %in%
          rownames(utils::installed.packages()))) {
```

This would never get triggered...

**Comment by rich-iannone** [comment]
Now solved with https://github.com/rich-iannone/DiagrammeR/pull/499
