### ISSUE TITLE
Get arrow to point in middle of another arrow

### ISSUE THREAD

**Issue by alapo** [rich-iannone/DiagrammeR#356]
This issue is slightly related to [Issue 349](https://github.com/rich-iannone/DiagrammeR/issues/349) 
I have been attempting to create an image similar to what is photoshopped below.

![img](https://i.imgur.com/YopdMut.png)

There are two main issues 

* Changing the text (highlighted in yellow)
* Having the arrow show up between nodes (highlighted in purple)

I was able to fix the font issue but it required me to use `HTML`. Hence I was unable to use the  `trav_out` function (which is coded in R)

**I have been unable to fix the arrow position.** 
To the best of my knowledge, If I switch to using `R` then I would be unable to change the font within a given box 

Below is the R code I used to try and make the figure

```{r}
library(DiagrammeR)

grViz("digraph prisma{
    node [shape=box, fontsize = 12];
    graph [splines=ortho, nodesep=1, dpi = 72]
    
    # Make the Labels which I will call during Edge definitions
    a [label = <Records identified through database searching<br></br>(n = 2167)<br></br><br></br><FONT POINT-SIZE='10'><i>PubMed (n = 135)<br></br>EMBASE (n = 14)</i></FONT>>];
    b [label = 'Additional records identified through other sources'];
    c [label = 'Records screened \n (n = 617)'];
    d [label = <Records excluded  <br></br> (n = 375)<br></br><FONT POINT-SIZE='10'><i>
    English (n = 15)<br></br> 
    Animal (n = 106) <br></br> 
    Not Simultaneous (n = 111)<br></br> 
    Review Paper (n = 86) <br></br>
    No Original Data (n = 26)
    </i></FONT>>]
    e [label = 'Full text articles assessed for eligibility \n (n = 238)']
    f [label = 'Full text articles excluded, with reasons \n (n = 67)']
    g [label = 'Studies included in qualitative synthesis \n (n = 171)']
    
    
    # Edge definitions
      # Connecting the top 2 boxes to 'Records Screened'
      a -> c
      b -> c
      # Other Connections
      c -> e
      d -> c
      e -> f
      f -> g
  }
")
```

**Comment by alapo** [comment]
After some more digging I was able to get the text to work but the position of the arrow is still a mystery

Here is the code
```{r}
grViz("digraph prisma{
    node [shape=box, fontsize = 12];
    graph [splines=ortho, nodesep=1, dpi = 72]
    
    a [label = <Records identified through database searching<br></br>(n = 2167)<br></br><br></br><FONT POINT-SIZE='10'><i>PubMed (n = 135)<br></br>EMBASE (n = 14)</i></FONT>>];
    b [label = 'Additional records identified through other sources'];
    c [label = 'Records screened \n (n = 617)'];
    d [label = <Records excluded  <br></br> (n = 375) <br></br> <FONT POINT-SIZE='10'><i> English (n=15) <br></br> Animal (n=106) <br></br> Not simultaneous (n=111)</i></FONT>>]
    # the top 2 boxes being recreated here
    
    # Edge definitions
      # Connecting the top 2 boxes to 'Records Screened'
      a -> c
      b -> c
      
      # Connecting 'Records Screened' to 'Number Excluded'
      c -> d
    
  }
") 

```


Here is the result

![img](https://i.imgur.com/URUsl4N.png)

**Comment by damien-dupre** [comment]
if that helps, you can create an empty point node where the arrow is starting from it 
`grViz("digraph prisma{
    node [shape=box, fontsize = 12];
    a; b; c; d; e; f; g
    node [shape = point, width = 0, height = 0]
    ''
    graph [splines=ortho, nodesep=1, dpi = 72]
    
    # Make the Labels which I will call during Edge definitions
    a [label = <Records identified through database searching<br></br>(n = 2167)<br></br><br></br><FONT POINT-SIZE='10'><i>PubMed (n = 135)<br></br>EMBASE (n = 14)</i></FONT>>];
    b [label = 'Additional records identified through other sources'];
    c [label = 'Records screened \n (n = 617)'];
    d [label = <Records excluded  <br></br> (n = 375)<br></br><FONT POINT-SIZE='10'><i>
    English (n = 15)<br></br> 
    Animal (n = 106) <br></br> 
    Not Simultaneous (n = 111)<br></br> 
    Review Paper (n = 86) <br></br>
    No Original Data (n = 26)
    </i></FONT>>]
    e [label = 'Full text articles assessed for eligibility \n (n = 238)']
    f [label = 'Full text articles excluded, with reasons \n (n = 67)']
    g [label = 'Studies included in qualitative synthesis \n (n = 171)']
    
    
    # Edge definitions
      # Connecting the top 2 boxes to 'Records Screened'
      a -> c
      b -> c
      
      # Other Connections
      c -> '' [arrowhead = none]
      '' -> e
      '' -> d
      e -> f
      f -> g
      
          subgraph {
      rank = same; d; '';
    }
  }
")`

**Comment by alapo** [comment]
Thanks I will give that a go.
