### ISSUE TITLE
endless loop in replace_in_spec

### ISSUE THREAD

**Issue by step-** [rich-iannone/DiagrammeR#357]
First, thank you for this awesome package and documentation piece!

I experienced an endless loop, which I traced down to `replace_in_spec`, precisely [here](https://github.com/rich-iannone/DiagrammeR/blob/4bf69537405d49e5cb24f05dc3cbf4cf8c9b5db2/R/spectools.R#L107).
I can see that the code attempts to replace `'@@<number>'` (mind the surrounding single quotes). If no replacement occurs, the while loop continues infinitely.

When I noticed the endless loop my graph definition was

```graphviz
digraph syntax {
...
node [ fontcolor = @@1 ]
...
[1]: global_fontcolor
}
```
I tried changing `@@1` to `"@@1"` but no joy, then I looked at the source code and discovered that the only valid syntax to affect the replacement is `'@@1'` (tested, works).  This [document](https://rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html#substitution) - section _Graphviz Substitution_ / _How It Works_ - makes no mention of the single quote requirement.

While this is an issue, users can easily work around it by ensuring surrounding single quotes for all `@@<number>` references.

Note: I didn't test `@@<number>-<index>` references.

**Comment by rich-iannone** [comment]
Thank you for finding and reporting this bug. This will be fixed shortly, I appreciate the detail you put into the issue!

**Comment by step-** [comment]
You're welcome. I need to add this actual use case, if you can support it:
```
The_Node [ label = "OVER\n@@4" ]
[4]: if (exists("name") name else "UNDER")
```
Thank you
