### ISSUE TITLE
Unable to find documentation on cluster graphs

### ISSUE THREAD

**Issue by Nevrage** [rich-iannone/DiagrammeR#359]
Hello,

I am trying to get any kind of clustering working and while a few issues mention it being done and functional the closest thing I can find to a documentation is the sample code in #257 

As soon as I add a "cluster" column in my NDF I get the `Error: replacement must be a character vector` when I try to render or export the graph.

What am I missing?

Thanks,

**Comment by egouldo** [comment]
#307 fixes this problem, but is only on the development version of the package, not the CRAN version.

For now, install the dev version: `devtools::install_github("rich-iannone/DiagrammeR")`

**Comment by Nevrage** [comment]
thanks!
