### ISSUE TITLE
Mermaid sequence diagrams broken

### ISSUE THREAD

**Issue by ViRb3** [rich-iannone/DiagrammeR#363]
# Example 1
## Code:
```
mermaid("
sequenceDiagram;
    B ->> A: C
    A ->> B: D
")
```

## DiagrammeR:
![image](https://user-images.githubusercontent.com/2650170/69749048-8fb87b80-1141-11ea-9a3f-452795a1ac97.png)

## mermaid.js:
![image](https://user-images.githubusercontent.com/2650170/69749086-a232b500-1141-11ea-9979-65f2af402fca.png)

# Example 2
## Code:
```{r}
mermaid("
sequenceDiagram;
    participant A
    A ->> B: C
")
```

## DiagrammeR:
![image](https://user-images.githubusercontent.com/2650170/69749270-0eadb400-1142-11ea-8a8f-6bb0606786a4.png)

## mermaid.js:
![image](https://user-images.githubusercontent.com/2650170/69749282-18371c00-1142-11ea-9424-90d46399774b.png)

**Comment by wligtenberg** [comment]
These issues seem fixed after the last update of the mermaid library.
Could you try again after installing the latest version from github using:

```devtools::install_github("rich-iannone/DiagrammeR")```

**Comment by Rey-ND** [comment]
Hi there @ViRb3 and  @wligtenberg .
I believe this issue is solved with possible a syntax/whitespace fix/work-around:

```
# Solution to first situation (notice the spacing of the '->>'
mermaid("
sequenceDiagram;
    B->>A: C
    A->>B: D
")

# Solution to the second situation (same '->>' solution)
mermaid("
sequenceDiagram;
    participant A
    A->>B: C
")
```
Thanks
