### ISSUE TITLE
Add razor-like syntax for substituting results of evaluated R expressions (provided in a Markdown-like style as footnotes)

### ISSUE THREAD

**Issue by rich-iannone** [rich-iannone/DiagrammeR#37]
Begun some preliminary work on this. The idea is to allow a marker (I've chosen the double ampersand, followed by a number) to be placed in the graph spec. As numbered footnotes, R expressions are to be provided. After some basic checking, the expressions would be evaluated and the results substituted in the proper locations in the graph spec. As this evolves a bit, I'll provide a workable example. I'd like to support expressions that produce vectors, as well. 

Why do this at all? Hoping that this separation of (very useful) calculation and graph specs will result in better readability and more simplicity for the user. Again, more details to come...

**Comment by rich-iannone** [comment]
Added an R script to the /inst folder to test out this functionality. @timelyportfolio would you like to test it out? It's sef-contained and seems to work well for me. Just wanted your input on ways to enhance and make more robust.

**Comment by timelyportfolio** [comment]
Cool, should be able to look at it in a little bit.

**Comment by timelyportfolio** [comment]
I'm at a big disadvantage here since I have never heard of `Razor` until now.  Should we implement on the Javascript side with something like [owinjs-razor](https://github.com/owinjs/owinjs-razor)?  Would something like `whisker`/`handlebars` with an existing `R` implementation be better to prevent ongoing maintenance/support?

**Comment by timelyportfolio** [comment]
I tried it out.  Is this the expected result?

![image](https://cloud.githubusercontent.com/assets/837910/5766608/8edd373e-9cc8-11e4-8a9d-99c80da88940.png)

Could you use `strsplit` instead to avoid another dependency?

```
digraph <-"
digraph G {
a -> '@@1'
'@@1' -> b
b -> c
b -> 'number: @@2'
c -> '@@1'
d -> '@@2'
d -> c
f -> d
d -> e
'@@1' -> c
a -> f
}

@@1: mean(c(
4, 7, 9, 1, 3, 9))
@@2: 2:5
"


replace_in_spec <- function(spec) {
  
  if (grepl("@@", spec)){
    
    # Extract the spec into several pieces: first being the body, 
    # subsequent pieces belonging the replacement references
    spec_body <- unlist(strsplit(x = spec, "\\n@@1"))[1]
    
    spec_references <- paste0("\\n@@1", unlist(strsplit(x = spec, "\\n@@1"))[2])
    
    
    # Split the references into a vector of R statements
    split_references <- 
    gsub("\\n", "",
         gsub("^ ", "",
              gsub("\\\\n@@1:", "",
                   unlist(strsplit(x = spec_references, "\\n@@[0-9*]:")))))
    
    # Evaluate the expressions and save into a list object
    for (i in 1:length(split_references)){
      
      if (i == 1){
        eval_expressions <- list()
      }
      
      eval_expressions <- c(eval_expressions,
                            list(eval(parse(text = split_references[i]))))
    }
    
    # Make replacements to the spec body
    for (i in 1:length(split_references)){
        
      spec_body <- gsub(paste0("@@", i), eval_expressions[[i]][1], spec_body)
      
    }
    
    
    # Return the updated spec with replacements evaluated  
    return(spec_body)
  }
  
}


spec <- replace_in_spec(digraph)

grViz(spec)

```

**Comment by rich-iannone** [comment]
I think I started off with strsplit but went for the quick win but I think too many dependencies is definitely not good. That is the intended result.

**Comment by rich-iannone** [comment]
There was something I wanted to implement, which is the evaluation leading to a vector result, and, the syntax in the diagram spec could allow for the selection of an index value. For example, we could have @@1 for subbing in a value that is part of an object of length 1 but @@2-1, @@2-2, @@2-3 to access values from indices 1, 2, and 3 from evaluated expression 2. We might even use the syntax @@2- several times in the spec to allow replacement in order.

**Comment by rich-iannone** [comment]
@timelyportfolio this looks good enough to include. Should it be part of the 0.3 (next) release to give it more weight? If you think so, could you incorporate into a pull request? I'll prepare some explanations in the README for when it gets added.

**Comment by timelyportfolio** [comment]
ok, I'm thinking this should be a helper function rather than in the `mermaid` or `grViz` functions.  Are you thinking the same thing?

**Comment by rich-iannone** [comment]
@timelyportfolio yes, definitely. I don't think it's very safe from a user standpoint to build it into either of those functions. (At least not at this early stage.)

**Comment by rich-iannone** [comment]
Here is a better place and another example of the output:

```R

spec <-
  "
digraph a_nice_graph {
node [fontname = Helvetica]
a [label = '@@1']
b [label = '@@2-1']
c [label = '@@2-2']
d [label = '@@2-3']
e [label = '@@2-4']
f [label = '@@2-5']
g [label = '@@2-6']
h [label = '@@2-7']
i [label = '@@2-8']
j [label = '@@2-9']
a -> { b c d e f g h i j}

}

[1]: 'top'
[2]: 10:20
"

replace_in_spec <- function(spec) {
  
  if (grepl("@@", spec)){
    
    # Extract the spec into several pieces: first being the body,
    # subsequent pieces belonging the replacement references
    
    spec_body <- unlist(strsplit(x = spec, "\\n\\[1\\]:"))[1]
    
    spec_references <- paste0("[1]:",
                              unlist(strsplit(x = spec, "\\n\\[1\\]:"))[2])
    
    # Split the references into a vector of R statements
    split_references <-
    gsub("\\[[0-9*]\\]:[ ]?", "",
         unlist(strsplit(x = spec_references, "\\n")))
    
    # Evaluate the expressions and save into a list object
    for (i in 1:length(split_references)){
      if (i == 1){
        eval_expressions <- list()
      }
      eval_expressions <- c(eval_expressions,
                            list(eval(parse(text = split_references[i]))))
    }
    
    # Make replacements to the spec body for each replacement that has
    # no hyphen
    for (i in 1:length(split_references)){
      
      while (grepl(paste0("@@", i, "'"), spec_body)){
        
        spec_body <- gsub(paste0("@@", i),
                          eval_expressions[[i]][1], spec_body)
        
      }
    }
    
    # If the replacement has a hyphen, then obtain the digit(s) immediately
    # following and return the value from that index
    for (i in 1:length(split_references)){
      while (grepl(paste0("@@", i, "-", "[0-9]+"), spec_body)){
        the_index <-
        as.numeric(gsub("^([0-9]+)(.*)", "\\1",
                        strsplit(spec_body,
                                 paste0("@@", i, "-"))[[1]][2]))
        
        if (the_index > length(eval_expressions[[i]])){
          spec_body <- gsub(paste0("@@", i, "-", the_index),
                            eval_expressions[[i]][length(eval_expressions[[i]])],
                            spec_body)
        } else {
          spec_body <- gsub(paste0("@@", i, "-", the_index),
                            eval_expressions[[i]][the_index], spec_body)
        }
        
      }
      
    }
    
    # Return the updated spec with replacements evaluated
    return(spec_body)
  }
}

spec <- replace_in_spec(spec)

grViz(spec)
```

![output](https://cloud.githubusercontent.com/assets/5612024/5931954/c856ce22-a659-11e4-8258-c79c53a966cf.png)

**Comment by timelyportfolio** [comment]
Seems pretty cool, and I think my ignorance of razor is preventing me from
seeing the full potential.  My opinion in terms of avoiding unintended
consequences is to make the function available separate from `grViz` and
document there.  Otherwise, the documentation would have to cover this case
also, and I'm afraid it could lead to confusion.  Do you want me to fold it
in?  If you are comfortable doing it, I would prefer you do it to get all
the glory and credit :)

Let me know when you get a chance to retest the reverted behavior to fix
Shiny.

Kent

**Comment by rich-iannone** [comment]
If you've got the time, it'd be cool if you could put it together in another PR, where this function is separate. I owe you big on the contribs page, that's for certain!

**Comment by rich-iannone** [comment]
And I'll definitely test tonight. Gearing up to finally submit to CRAN. Just wanted to get one last feature in.

**Comment by timelyportfolio** [comment]
Are you ok with `replace_in_spec`?  I'm wondering if we should choose a name more descriptive, such as `template_spec` or `spec_template`.  For some reason, I'm not very creative right now with my names.

**Comment by rich-iannone** [comment]
I like something clinical like `replace_in_spec`. Naming things can be tough, I definitely agree.

**Comment by timelyportfolio** [comment]
I found this as a potential reference for `Razor` syntax http://haacked.com/archive/2011/01/06/razor-syntax-quick-reference.aspx/

**Comment by rich-iannone** [comment]
That's pretty nice! There's quite a bit to razor.

**Comment by rich-iannone** [comment]
Okay, so since it's in I'll close this now.
