### ISSUE TITLE
Substitution labels error starting at number 10

### ISSUE THREAD

**Issue by fivetilkeys** [rich-iannone/DiagrammeR#372]
Hello - 

I have noticed that I am getting errors in my footnote interpretations over the last week or so. I tried updating to the latest version as well as the latest github download. I have also updated R and R studio to the latest versions. 

Starting with footnote 10, there is a misinterpretation of the previously outlined labels:

```
grViz("
digraph {
graph [layout = dot]
node [shape = box, fontname = Helvetica]
a [label = '@@1']
b [label = '@@2']
c [label = '@@3']
d [label = '@@4']
e [label = '@@5']
f [label = '@@6']
g [label = '@@7']
h [label = '@@8']
i [label = '@@9']
j [label = '@@10']
k [label = '@@11']
l [label = '@@12']
m [label = '@@13']
n [label = '@@14']
o [label = '@@15']
p [label = '@@16']

a -> {b c d}
b -> {e f}
c -> {g h}
d -> {i j}
e -> {k}
f -> {l}
g -> {m}
h -> {n}
i -> {o}
j -> {p}

}

[1]: 'hello'
[2]: 'there'
[3]: 'how'
[4]: 'are'
[5]: 'you'
[6]: 'today'
[7]: 7
[8]: 8
[9]: 9
[10]: 'this one is interpreted as @@1 + 0 rather than @@10'
[11]: 'this one is interpreted as @@1 + 1 rather than @@11'
[12]: 'etc'
[13]: 'etc'
[14]: 'etc'
[15]: 'etc'
[16]: 'etc'
")
```

<img width="620" alt="Screen Shot 2020-01-23 at 12 59 28 PM" src="https://user-images.githubusercontent.com/59181455/73010314-3470d580-3de0-11ea-8a84-eda7e39e9cde.png">

Thanks for your help!

**Comment by kb12344** [comment]
I'm also having the same issue.  I had an older version of DiagrammeR that worked with 15 footnotes in a project.  I updated the package and it is no longer working.
