### ISSUE TITLE
[Bug] - DiagrammeR not working with the Rmarkdown package

### ISSUE THREAD

**Issue by prdm0** [rich-iannone/DiagrammeR#375]
Dear,

I am noticing that the **rmarkdown** and **bookdown** packages are not working well with the **Diagrammer** package. It seems to me to be a recent problem, since the problem did not occur months ago.

The code below will compile without generating problems and the HTML will be generated. When I open it I realize that all the content is correct, including the diagram built by **Diagrammer**, however the generated page is erased (approaching a transparent tone).

Does anyone know why this problem?

**Minimum Example**:

```
---
title: "Untitled"
author: "Author"
date: "05/02/2020"
output: html_document
---


# SECTION

Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test.

```{r diagramafluxo, echo = FALSE}
library(DiagrammeR)
mermaid("
graph TD

A((fa:fa-database DADOS))-->B((R))
B-->C(ORGANIZACAO DOS DADOS)
D(ESCOLHA DAS METODOLOGIAS)
C-->|Implementar|E((R))
D-->|Implementar|E
E-->F(ORGANIZACAO DOS RESULTADOS)
F-->|Frequente|G((Documento))

style A fill:#ffe5cc
style B fill:#ffe5cc
style C fill:#ffe5cc
style D fill:#ffe5cc
style E fill:#ffe5cc
style F fill:#ffe5cc
style G fill:#ffe5cc
")

# NEW SECTION
```

This topic was also opened in the **rmarkdown** project. A member opposed the following:

"I am not sure why mermaid css as such a broad selector... FWIW, the changes happened in DiagrammR in the last update to mermaid components. See the diff. You'll see that in mermaid.css, opacity was set for .mermaid .section selector, that is now a broader .section selector.

I think it worth open an issue in DiagrammeR to see if the css could be improved or if they now why this changes happened."

See question [#1768](https://github.com/rstudio/rmarkdown/issues/1768).

Best regards,
prdm0

**Comment by cderv** [comment]
I am the "one member" 😉 

Here are the css rule I think is causing the opacity in the Rmd example above
https://github.com/rich-iannone/DiagrammeR/blob/662dc8ce7d1ea468f58fb3e7044c6c8b7a2475cf/inst/htmlwidgets/lib/mermaid/dist/mermaid.css#L174-L177

The selector here will apply to any object of class `section`, and it happens that Rmarkdown (or pandoc) creates a `div` of class `section` for the all content. Hence the opacity on all the document. 

I observe that before [update to mermaid 8.4.3](https://github.com/rich-iannone/DiagrammeR/commit/71b399f0b2ee2120fd6a07a4b597161b8ebb500f), the opacity was set for this rule
https://github.com/rich-iannone/DiagrammeR/blob/82bb7f9f46e64e6ea82ef03947332a494dc27f0e/inst/htmlwidgets/lib/mermaid/dist/mermaid.css#L93-L96

Hence I guess no issue before. I was wondering why those changes in mermaid to broader rules, and why the opacity on all node of class `section`

Hope it helps
