### ISSUE TITLE
Fully bake in support for other Graphviz engines other than DOT

### ISSUE THREAD

**Issue by rich-iannone** [rich-iannone/DiagrammeR#38]
Currently DOT is implemented and it renders SVG from a graph spec provided in dot syntax. Still need to incorporate the other styles such as neato, twopi, and the handful of others.

**Comment by timelyportfolio** [comment]
Will work on this.  Easy to implement and a little harder to test.

**Comment by timelyportfolio** [comment]
Think this is now working.  Added a bunch of examples in the examples.R.  Addresses #38

**Comment by rich-iannone** [comment]
I just got a chance to look at the examples with the different syntax. Looks really good! Will have to spend a good part of the documentation explaining what all of this could do. So, time to jump into creating the gh-pages docs.

**Comment by timelyportfolio** [comment]
will you bump version and re-roxygenize also?  let me know if I can help.

**Comment by rich-iannone** [comment]
@timelyportfolio Yes! I can do that. I need to figure out how to start the gh-pages branch.

**Comment by timelyportfolio** [comment]
Do you want to use Jekyll, or just manual build the files?  I always go with the latter, and if you choose this route, it is as simple as on command-line

```
git checkout -b gh-pages
```

and then add/copy a blank .nojekyll file into the top level directory.  Or if you want just make a blank branch, and I can submit a pull to that with some basic starting stuff.

**Comment by rich-iannone** [comment]
@timelyportfolio I'll start a blank branch and have you submit a pull request. I'd like to see how to start that sort of thing the right way...

**Comment by timelyportfolio** [comment]
Well, while my workflow works for me, I'm sure most would laugh at it.

**Comment by timelyportfolio** [comment]
for a complete example you can inspect the RStudio gh-pages or [`htmlwidgets`](https://github.com/ramnathv/htmlwidgets/tree/gh-pages).

**Comment by timelyportfolio** [comment]
This from https://raw.githubusercontent.com/christophergandrud/networkD3/gh-pages/index.Rmd might also be helpful.

**Comment by rich-iannone** [comment]
@timelyportfolio Thanks! New stuff to me, so, need the resources...

**Comment by timelyportfolio** [comment]
Ooooh, I forgot, you like `fullPage.js` right?  I could do something with it.

**Comment by rich-iannone** [comment]
@timelyportfolio yes!! that would be great. Just ran that command (`git checkout -b gh-pages`) in my local project dir. How to push that empty branch? Should I just `touch .nojekyll` and commit that? Then `git push remote`? Hmm....

**Comment by timelyportfolio** [comment]
Would delete everything in there.  Create `.nojekyll` and then do `git push origin gh-pages`.

**Comment by rich-iannone** [comment]
So delete all project files in my local 'DiagrammeR' folder? It's a bit confusing because after searching online I see differing opinions and generating an empty branch. Some involve using `orphan` and deleting inside the branch...

**Comment by timelyportfolio** [comment]
Yes, I'm sure lots of opinions.  Mine is to start simple and then build from that, but you can certainly choose from a number of routes.  I am as I said by no means even a novice at this.

**Comment by timelyportfolio** [comment]
I like this from @hafen https://github.com/hafen/buildDocs.

**Comment by rich-iannone** [comment]
That is nice. Pushed to `gh-pages` but it's unfortunately even with `master`

**Comment by timelyportfolio** [comment]
Did you delete and commit the delete with `git commit -A`?  Forgot the commit part :)

**Comment by timelyportfolio** [comment]
And if you have a Github client, you can use that also, so you don't have to command-line.

**Comment by rich-iannone** [comment]
I'm using a mix of both. How do you set to push to the remote branch of `gh-pages` in RStudio?

**Comment by timelyportfolio** [comment]
Forgot about that, maybe see https://support.rstudio.com/hc/communities/public/questions/200640128-It-seems-that-if-git-remote-was-specified-at-the-command-line-that-it-s-not-reflected-in-the-RStudio-UI

**Comment by timelyportfolio** [comment]
wouldn't worry too much about RStudio.  You can use it to commit and then just `git push origin gh-pages` at the command-line.

**Comment by rich-iannone** [comment]
Yeah, command line is the way to go. Finally pushed it to the `gh-pages` branch. Not totally clean but close enough (some dot files).

**Comment by rich-iannone** [comment]
I think I need a .gitignore in there

**Comment by timelyportfolio** [comment]
would just copy over one from master.  night

**Comment by rich-iannone** [comment]
Yeah, I'll do that now.

**Comment by rich-iannone** [comment]
Okay did it! And learning more about branch management. Damn, I always need more practice with that.

**Comment by timelyportfolio** [comment]
Now, that you had some fun learning.  How about `git push origin :gh-pages` to delete the remote branch and `git branch -d gh-pages` to remove the local branch?  Then can you start with a completely empty new `gh-pages` branch?

**Comment by timelyportfolio** [comment]
Then you I can submit a pull or you can just pull my `gh-pages` as a starter http://timelyportfolio.github.io/DiagrammeR/.

**Comment by rich-iannone** [comment]
Okay deleted the gh-pages branch. How do I checkout your gh-pages branch? Sorry...

**Comment by timelyportfolio** [comment]
I'll submit a pull.  I added an Example with `Skeleton` since I think  it will be easier to work with.

http://timelyportfolio.github.io/DiagrammeR/index_skeleton.html

**Comment by timelyportfolio** [comment]
First, if you don't mind, will you follow these steps to create and push an empty `gh-pages` branch? https://help.github.com/articles/creating-project-pages-manually/

**Comment by rich-iannone** [comment]
I can do that, thanks! I've stepped out for a bit, but, I can get this done in about 2 h from now.

**Comment by rich-iannone** [comment]
@timelyportfolio Okay! Finally done. That GitHub help page was very helpful.

**Comment by rich-iannone** [comment]
@timelyportfolio  the skeleton boilerplate is quite nice. Had a look at their site. I think I'll create a new issue to discuss gh-pages development and leave this thread alone.
