### ISSUE TITLE
Curve and arc like edge attributes?

### ISSUE THREAD

**Issue by opendatasurgeon** [rich-iannone/DiagrammeR#388]
Hi! Are you planning to add several edge attributes like you did for nodes? I would appreciate if we can have curves, and arcs (like those in arc graphs) for edges. 
Or, I can't see how I can implement them at least, I would love if someone can help out.

**Comment by almost-surely** [comment]
Hello, how did you solve this issue @opendatasurgeon ? I am wanting to draw something like [this](https://stackoverflow.com/questions/32432818/curve-some-edges-in-graphviz) but not sure how

**Comment by opendatasurgeon** [comment]
Hello @almost-surely ! Unfortunately, the person I was working for didn't go forward with the project that required this tool. So I closed this post. Have you heard of Bioconductor libraries before? They do have Rgraphviz package. Hopefully, you can use that...?! Sorry for not being able to help much.

Rgraphviz : https://www.youtube.com/watch?v=N8JjU3sFOMY

**Comment by almost-surely** [comment]
@opendatasurgeon Thank you so much for the quick reply and your help!
