### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by sayarshah** [rich-iannone/DiagrammeR#389]
when i type the command 
library(DiagrammeR)
> DiagrammeR::grViz("~/Document/Desktop/dot-graph.gv")
the programme responds 
Error: syntax error in line 1 near '~'
can any body solve my issue please
Thanks

**Comment by DarthHeizenberg** [comment]
Your GV file has an error. Recommend pasting the file contents here or in a forum that specializes in debugging gv-dot files

**Comment by magjac** [comment]
@sayarshah You can use the [Graphviz Visual Editor](http://magjac.com/graphviz-visual-editor/) to pinpoint errors or the [Graphviz Forum](https://forum.graphviz.org/) to ask for help
