### ISSUE TITLE
Diagramme not working in rmarkdown when document is regenerated

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#39]
When rendered as HTML it seems impossible to get more than on DiagrammeR.
I have tested only with cran version.

**Comment by timelyportfolio** [comment]
This should be fixed in the github version.  Could you test? @rich-iannone what are your plans for a CRAN resubmission?

**Comment by rich-iannone** [comment]
@pommedeterresautee thanks for bringing this up, and thanks @timelyportfolio for following up so quickly. It should definitely get fixed. Would you like to have a go at it, @timelyportfolio ? I'll test afterward. And, yes, an update submission should be made to CRAN shortly thereafter.

**Comment by pommedeterresautee** [comment]
Ok updated to Github version.
Super strange, the first time I tried with one Diagramme

```R
---
title: "Untitled"
author: "Taj"
date: "Thursday, January 15, 2015"
output: html_document
---

test

```{r}
require(DiagrammeR)
DiagrammeR("
   graph TB
   A-->B
   A-->C
   C-->E
   B-->D
   C-->D
   D-->F
   E-->F
")

```
Got a good result.

Restarted with ONE diagramme (changed nothing). And it doesn't work ! There is probably a kind of cache somewhere. In the generated document I have that :
'undefined' is not an object (evaluating 'n.minlen')

Need to restart to make it work (not just R but whole Rstudio).
Then it works again.

But there is a good news! When I put two diagramme (after a restart) it works.

So I change of bug: diagramme not working in rmarkdown  when document is regenerated.

**Comment by pommedeterresautee** [comment]
FYI when I send several time diagramme command in the console, no issue.

**Comment by timelyportfolio** [comment]
Just getting out of some meetings.  This sounds like as you say a problem with `cache`.  I've been so frustrated in the past that by default I start every .Rmd or knitr with this even thought it takes longer

```
knitr::opts_chunk$set(
  , cache = FALSE
)
```

See if this fixes it.

**Comment by pommedeterresautee** [comment]
Unfortunately avoiding the cache doesn't fix the issue.

**Comment by timelyportfolio** [comment]
did you also delete the cache directory that probably lingers from previous runs?

**Comment by pommedeterresautee** [comment]
Mmmmhhh I don't find the path of the cache. I have tried another strategy, using `opts_chunk$set(cache.path = "/path/..." )` and changed it several times.
It fixed nothing!

And I have the same issue on both Windows 8 and Ubuntu.

Kind regards,
Michael

**Comment by timelyportfolio** [comment]
This is strange , and I was able to recreate, but I'm not sure this is an issue with `DiagrammeR`.  Even with the error when I opened in Chrome it rendered fine.  I think this might be an issue with RStudio Viewer browser cache.  If you can isolate to `DiagrammeR`, then please let us know.


![image](https://cloud.githubusercontent.com/assets/837910/5766404/ce2c0066-9cc6-11e4-8bc4-286eae293916.png)

**Comment by pommedeterresautee** [comment]
Awesome it works for me too :-)

**Comment by pommedeterresautee** [comment]
Finally not so good.

It is not possible to print several plots in an Rmarkdown document when DiagrammeR is called from a for loop!!!

I have found that [link](https://groups.google.com/forum/#!msg/ggvis/HPhAaSttQzU/17mNeDdmVqwJ) but can't apply. May be there is an idea to workaround the bug.

**Comment by timelyportfolio** [comment]
Perhaps, and only perhaps a `lapply` and `tagList` will work here, so the structure would look like
```
library(htmltools)
tagList(lapply(
 1:length(diagrams)
 , function(d){
    DiagrammeR(d)
 }
)
```

**Comment by pommedeterresautee** [comment]
It just shows numbers (the counter of lapply)

**Comment by pommedeterresautee** [comment]
library(DiagrammeR)
library(htmltools)
d = "
  graph LR;
    A-->B;
    A-->C;
    C-->E;
    B-->D;
    C-->D;
    D-->F;
    E-->F;"

tagList(lapply(
 1:3
 , function(d){
    DiagrammeR(d)
 }
))

**Comment by timelyportfolio** [comment]
`lapply` will make `d` the number/counter.  If you intend to do this, change to 

```
tagList(lapply(
 1:3
 , function(x){
    DiagrammeR(d)
 }
))
```

**Comment by pommedeterresautee** [comment]
Loooool

Bad news: I am tired
Good news: it works
Question: I have plenty of other things to print in my loop. lapply can t work with it. Do you see a way to use your workaround (tag***) with for loop?

**Comment by timelyportfolio** [comment]
no, unfortunately not a quick and easy answer that I know of, but possibly `knitr` StackOverflow could help

**Comment by pommedeterresautee** [comment]
Thanks to your example and your pointer I make that work:
```R

library(DiagrammeR)
library(magrittr)
library(htmltools)
d = "
  graph LR;
    A-->B;
    A-->C;
    C-->E;
    B-->D;
    C-->D;
    D-->F;
    E-->F;"

l <- list()
for(i in 1:5){
  l <- c(l,tags$p(DiagrammeR(d)))
}
tagList(l)
```

**Comment by pommedeterresautee** [comment]
btw two behavior here should be documented:
- use of tagLine to have plenty of diagrams in knitr
- open page in Chrome when regenerating a document

**Comment by timelyportfolio** [comment]
I think @ramnathv is working on a composing `html` with multiple `htmlwidgets` vignette.  I think that would be very helpful.

**Comment by rich-iannone** [comment]
It looks like this issue could be closed, so I'm going to close it now. @pommedeterresautee and @timelyportfolio, thanks for working together to solve this issue.
