### ISSUE TITLE
Error: syntax error in line 5 near '('

### ISSUE THREAD

**Issue by nnb1994** [rich-iannone/DiagrammeR#417]
library(diagram)
library("readxl")
library("writexl")

st1<-read_excel("C:/projects/PSD/data/Station 1.xlsx")
my_label <- c(st1$descripton)
vec<-c(1,2,3,4)
DiagrammeR::grViz("
                  digraph graph2 {
                  graph [layout = dot]
                  node [shape = rectangle, width = 4, fillcolor = Biege]
                  for(j in 4)
                    vec[j] [label = '@@j']
                  for(k in 3)
                    vec[k] -> vec[k+1]
                  }
                  for(i in 4)
                    [i]: paste0('', my_label[i],' ')
                  ")

**Comment by nnb1994** [comment]
Want to create dynamic flowchart of nodes with labels directly fetched from excel elements

**Comment by trashbirdecology** [comment]
I am not a developer on this package, but the purpose of this issue is not clear. What is the problem? It looks like an error in your own personal code?
