### ISSUE TITLE
Documentation Issue: Example code error/update

### ISSUE THREAD

**Issue by davidgebr** [rich-iannone/DiagrammeR#418]
This page has been a very useful resource.  https://github.com/rich-iannone/DiagrammeR/issues/new.

The last example under 'Graphviz Substitution/Examples' has the following line:

         **[2]: paste0('RStudio version:\\n ', rstudioapi::versionInfo()[[1]])**

The reference to parameter '1' needs to be updated to '3'. I assume that the order of the parameters has changed since creating the example. 

This not reference at 
          **https://rstudio.github.io/rstudioapi/reference/versionInfo.html** 

but debug showed that the 'citation' was output first and changing the reference to 3 enabled the demo code to run correctly.

**Comment by olivroy** [comment]
Couldn't find this. I guess it must have been fixed. Feel free to reopen a new issue if you still see this.
