### ISSUE TITLE
Should the DiagrammeR function removed from examples?

### ISSUE THREAD

**Issue by rich-iannone** [rich-iannone/DiagrammeR#42]
As two distinct functions, should that original `DiagrammeR` function be removed from examples?

**Comment by pommedeterresautee** [comment]
Because the way to describe diagram in the two format are very different it doesn't make sense to me to have the same function for both. It would be different if both could be describe with markdown and just one argument change would choose the Js library.

**Comment by rich-iannone** [comment]
It's been recently modified to act as a wrapper function to both the `mermaid` and `grViz` functions (modified the question to clear this up). So, I'm thinking that calls to `DiagrammeR` in the README examples should be replaced with `mermaid` calls...

**Comment by rich-iannone** [comment]
Changed all of the examples and they work fine!
