### ISSUE TITLE
some other examples with graphviz `grViz`

### ISSUE THREAD

**Issue by timelyportfolio** [rich-iannone/DiagrammeR#44]
I discovered these posts tonight, and thought they would fit in nicely with `DiagrammeR`.

http://blog.nguyenvq.com/blog/2014/01/17/skeleton-to-create-fast-automatic-tree-diagrams-using-r-and-graphviz/

Combined with this one http://blog.nguyenvq.com/blog/2012/05/29/better-decision-tree-graphics-for-rpart-via-party-and-partykit/, I think it would be a interesting example.

**Comment by rich-iannone** [comment]
@timelyportfolio good finds. I'll take a look. We definitely have to include some examples from a range of use cases.

**Comment by rich-iannone** [comment]
@timelyportfolio as a point of etiquette, do we contact the original authors of code and ask them directly before using their examples (if we indeed do that), or is it fine to include code and just include attribution?

**Comment by timelyportfolio** [comment]
Generally for a blog post I try to notify the author through a comment and then attribute in both the diagram and the code to produce.  Looking at these again, I think I like my rpart/mermaid code better than this, so I will close this.
