### ISSUE TITLE
Mermaid does not generate like the live editor

### ISSUE THREAD

**Issue by ManyStrongWords** [rich-iannone/DiagrammeR#442]
I believe this is a two part problem, the first being that the flowcharts don't generated the chunks with the html embedded in them like they do on the live editor, and that either the option doesn't exist or I cant find it to set   "securityLevel": "loose" in R.

The example below I cannot get to generate in R:

https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBIC0tPiBCWzxhIGhyZWY9J2h0dHA6Ly9nb29nbGUuY29tJz5saW5rPC9hPl1cbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCIsXG4gIFwic2VjdXJpdHlMZXZlbFwiOiBcImxvb3NlXCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2UsImxvYWRlciI6eyJ0eXBlIjoiZ2lzdCIsImNvbmZpZyI6eyJ1cmwiOiJodHRwczovL2dpc3QuZ2l0aHViLmNvbS82MjY4YTIzZTY3M2E1MzNkY2IxOThmMjQxZmQ3MDEyYS80ZWIwMzg4N2U2YTQxMzk3ZTgwYmRjZGJmOTQwMTdjNDk4ZjhmMWUyIn19fQ

**Comment by notesofdabbler** [comment]
The following steps worked for me.
1. I replaced the file in the package library /DiagrammeR/htmlwidgets/lib/mermaid/dist/mermaid.slim.min.js with the file at the link https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js 
2. I used the following code which is a slight variation from the link you posted and seems to work:
```
mermaid('
  graph TD
  A-->B(link)
  click B "http://www.google.com"
')
```
My DiagrammeR version is 1.0.7
