### ISSUE TITLE
"Error: Layout was not done" when drawing dm objects

### ISSUE THREAD

**Issue by krlmlr** [rich-iannone/DiagrammeR#458]
```
library(dm)
dm_nycflights13() %>% dm_draw()
```

Introduced in https://github.com/rich-iannone/DiagrammeR/pull/419, CC @jefshe.

**Comment by rich-iannone** [comment]
@krlmlr I reverted the change in that PR. And now the diagram does appear. Will be making another change required by CRAN (different issue) and submitting soon.

**Comment by rich-iannone** [comment]
DiagrammeR v1.0.9 is now on CRAN and should fix this problem. Will close issue now.
