### ISSUE TITLE
Cup Reconstructions

### ISSUE THREAD

**Issue by pssguy** [rich-iannone/DiagrammeR#46]
Is it possible to construct say the Stanley Cup playoffs with DiagrammeR
something like 
   http://www.printyourbrackets.com/nhl-playoff-results/2012-nhl-playoff-bracket-results.jpg

So a basic 
    library(DiagrammeR)
    diagram <- "
    graph LR
    A(Semi)-->B[Final]
    B-->C{Winner}"

mermaid(diagram)

would get me the left hand side but if I try adding

 graph RL
    E(Semi)-->F[Final]
    F-->C{Winner}

I get parsing error

**Comment by rich-iannone** [comment]
@pssguy all of this:

```R
diagram <- "
graph LR
A(Semi)-->B[Final]
B-->C{Winner}"

DiagrammeR(diagram)
mermaid(diagram)

diagram <- "
graph RL
E(Semi)-->F[Final]
F-->C{Winner}
"

DiagrammeR(diagram)
mermaid(diagram)
```
works for me. Just to be sure, paste that into a script and test on your machine. To be extra sure, try the GitHub version of the package (if you're using the CRAN version).

**Comment by rich-iannone** [comment]
@pssguy Sorry, should have looked at the example you linked to. It's currently not possible to mix orientations in a single graph with `mermaid`. I'll see if I could reconstruct that diagram though. Might be easier with the `grViz` function.

**Comment by pssguy** [comment]
Cheers. I do need the mix

**Comment by pssguy** [comment]
So did you succeed or is it just not feasible?

**Comment by pssguy** [comment]
Annual+ request
