### ISSUE TITLE
error with node with name ending with "v"

### ISSUE THREAD

**Issue by romainfrancois** [rich-iannone/DiagrammeR#47]
e.g. : 

```
mermaid( "graph LR; Av -->B" )
```

produces a html file containing this: 

```
Parse error on line 1:
graph LR; Av -->B
-----------^
Expecting 'EOF', 'GRAPH', 'SPACE', 'DIR', 'TAGEND', 'TAGSTART', 'SEMI', 'NEWLINE', 'SQS', 'SQE', 'PS', 'PE', 'DIAMOND_START', 'DIAMOND_STOP', 'MINUS', '--', 'ARROW_POINT', 'ARROW_CIRCLE', 'ARROW_CROSS', 'ARROW_OPEN', 'PIPE', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PLUS', 'EQUALS', 'MULT', 'TAG_START', 'TAG_END', 'QUOTE', got 'DOWN'
```

where with a capital `V` it works fine; 

```
mermaid( "graph LR; AV -->B" )
```

gives me this: 

![mermaid](https://cloud.githubusercontent.com/assets/2625526/5819456/42f53818-a0be-11e4-972d-a884ee4a3db7.png)

**Comment by timelyportfolio** [comment]
Thanks so much.  I am able to reproduce.  The `mermaid.js` is improving but still a little delicate.  I'll check to make sure this is the `mermaid.js` parser and file an issue there.
