### ISSUE TITLE
Cannot use a pretty name for a mermaid subgraph

### ISSUE THREAD

**Issue by travis-leith** [rich-iannone/DiagrammeR#470]
The following mmd works fine on [this online editor](https://mermaid.live/edit#pako:eNo1jTEOwjAMRa9ieW4H1gxM5QSwYQY3NjSCuFWaDFXVuxMJsv0nPb2_o59F0eEr8TLBbSBby_gDPt3jBg0fZAx9f4aRTE0aeewwaoocpFZ2MgDCPGlUQlencHoTkh3VK4tw1ouEPCd0T_6s2iGXPF838-hyKtqkIXB9jX_r-AJY4jjK)

```R
sample = "graph TD
subgraph a1[my subgraph]
a --> b
end
a --> c"

sample |> mermaid()
```

but running it in R does not work. The output is just the input text rendered plainly.

---
I am using R 4.2.0, DiagrammeR 1.0.9

**Comment by rich-iannone** [comment]
Closing this in favor of https://github.com/rich-iannone/DiagrammeR/issues/475.
