### ISSUE TITLE
Mermaid in Markdown. Arrow length supported?

### ISSUE THREAD

**Issue by PStaus** [rich-iannone/DiagrammeR#473]
Following R notebook is not creating correct figure. If arrows are standard it works. 
Is there a way to make this work? Thank you!
(DiagrammR Version 1.0.9)

```
---
title: "Mermaid"
output: html_notebook
---

```{r}
library(DiagrammeR)
mermaid("     
graph LR;
A-->B
A--->C")
```
```

This syntax works normally when using mermaid in Joplin and also on Github
```
```mermaid
graph LR;
A-->B;
A--->C;
```
```

**Comment by rich-iannone** [comment]
Closing this in favor of https://github.com/rich-iannone/DiagrammeR/issues/475.
