### ISSUE TITLE
Mermaid version used in DiagrammeR

### ISSUE THREAD

**Issue by YangTSY** [rich-iannone/DiagrammeR#480]
A simple question: Does DiagrammeR automatically use the latest Mermaid version?

I was trying to run a simple flowchart in R,  

The version in Mermaid Live Editor (version 9.2.2) is [here](https://mermaid.live/edit#pako:eNoljsEKwjAQRH9l2XPzA0GEqkf1oNdc1mRjC00i6QYrbf_daOc0bxiGmdEmx6jRD-ltO8oC55uJUEWQlErQbvSAnVJ7OGxkYVJqguXaLkcTscHAOVDv6tD8axiUjgMb1NU69lQGMWjiWqtUJN0_0aKWXLjB8nIkfOrpmSmg9jSMNWXXS8qX7dz_4_oFdK02NA)

```
flowchart LR
    a o--o A
    b <--> B
    c x--x |NA|C
```

When I copy this code to R, 

```
library(DiagrammeR)

# This doesn't work:
mermaid(
"graph LR
    a o--o A
    b <--> B
    c x--x |NA|C"
)

# This works:
mermaid(
  "graph LR
    a --> A
    b ==> B
    c --> |NA|C"
)
```
It feels like mermaid() doesn't support some features that are avaliable in mermaid.js.

**Comment by rich-iannone** [comment]
Closing this in favor of https://github.com/rich-iannone/DiagrammeR/issues/475.
