### ISSUE TITLE
Integrate r variables in Mermaid Graph

### ISSUE THREAD

**Issue by TazDP** [rich-iannone/DiagrammeR#483]
Hello, 

I've been pulling my hair out for this:

Is it possible to include r variables in a mermaid graph? Something like

my_var <- 10

```{r, echo = FALSE}
library(DiagrammeR)

my_var <- 10

mermaid("
graph LR
    A-->B
    B[%%%my_var%%%]
")
```

If not, shall I initiate a pull request?

Thanks a lot!

**Comment by olivroy** [comment]
You can always use other existing ways. DiagrammeR could possibly support that natively, but in the meantime, I can suggest using glue that uses `{` and `}` to deliminate R objects.

```r

my_var <- 10

mermaid(glue::glue("
graph LR
    A-->B
    B[{my_var}]
"))
```

If you want to use `%%%` as delimiters, you can use 

```r
mermaid(glue::glue("
graph LR
    A-->B
    B[%%%my_var%%%]
",
.open = "%%%",
.close = "%%%"))
```
