### ISSUE TITLE
github website link leads to spam

### ISSUE THREAD

**Issue by maxheld83** [rich-iannone/DiagrammeR#484]
this link listed on the repo sidebar: http://visualizers.co/diagrammer/

leads to this:

![spam](https://user-images.githubusercontent.com/5372770/232330103-fd17acbd-484f-4c44-a4c7-b84222872581.jpg)

**Comment by rich-iannone** [comment]
Apologies for that :( 

It's now been fully rebuilt and hosted on GH Pages.
