### ISSUE TITLE
grViz with R Shiny

### ISSUE THREAD

**Issue by vbakella** [rich-iannone/DiagrammeR#50]
Hi,

First of all - amazing package. Thank you so much!

I have been trying to create a grViz network diagram using Shiny. It gives me a parser error. Any help would be most appreciated.

Given below is the code and the error

Error
====
Parse error on line 2:
...s_and_circles {    node [shape = box, c
----------------------^
Expecting '{', '}', 'ALPHA', 'NUM', 'COLON', 'PLUS', 'EQUALS', 'MULT', 'DOT', 'BRKT', 'SPACE', 'MINUS', 'keywords', ';', '=', '[', ']', ',', ':', 'ARROW_POINT', 'ARROW_OPEN', got 'NODE'

In global.R
========
spec <- "
    digraph boxes_and_circles {
    node [shape = box, color = blue] 
    A; B; C; D; E
    F [color = black]
    
    node [shape = circle,
    fixedsize = true,
    width = 0.9] // sets as circles
    1; 2; 3; 4; 5; 6; 7; 8
    
    edge [color = gray] 
    A->1; B->2
    B->3 [color = red]
    B->4
    C->A [color = green]
    1->D; E->A; 2->4; 1->5; 1->F
    E->6; 4->6; 5->7; 6->7
    3->8 [color = blue]
    
    graph [overlap = true, fontsize = 10]
    }
"
ui.R
====
library(shiny)
library(dplyr)
library(DiagrammeR)
library(shinythemes)

shinyUI(navbarPage("AInspector", id="nav",theme = shinytheme("flatly"),
                    tabPanel("Test",
                            DiagrammeROutput('gVizDiagram',height = 1200, width = 1200)
                   )
                   
)) #end ShinyUI

server.R
======
shinyServer(function(input, output, session) {
  

  output$gVizDiagram <- renderDiagrammeR(
    DiagrammeR(diagram=spec,type="grViz",engine="neato")
  ) 
  
})

Thanks

**Comment by rich-iannone** [comment]
@vbakella the shiny implementation hasn't been updated after adding in the Graphviz library. So, it definitely needs and update and some testing.

@timelyportfolio: I know you're busy but could you comment on this issue? I suppose there should be an updated shiny app somewhere down the line...

**Comment by rich-iannone** [comment]
@vbakella forget to mention: thanks for trying out the package and for the good words! Still early days with this but improvements are forthcoming!

**Comment by timelyportfolio** [comment]
Will definitely work on `grViz` + Shiny, but will probably be later this week or early next week.

**Comment by timelyportfolio** [comment]
Want me to try to get this in before CRAN submission?

**Comment by rich-iannone** [comment]
Yeah! There's not many opportunities to update, so, for sure!
