### ISSUE TITLE
Test relies on specific output from sample_islands() for given seed

### ISSUE THREAD

**Issue by szhorvat** [rich-iannone/DiagrammeR#500]
The "counting the number of strongly connected components is possible" test currently relies on igraph's `sample_islands()` function returning a specific output for a specific seed. 

https://github.com/rich-iannone/DiagrammeR/blob/main/tests/testthat/test-count_entities.R#L129

We do not guarantee that the output of such stochastic functions won't change across versions (for the same seed). Can you please refactor the test not to rely on this? In an upcoming version of igraph, `sample_islands()` will change, causing this test to fail.

**Comment by szhorvat** [comment]
On a related note, the title of this test mentions "strongly connected components", but the test is executed for an _undirected_ graph, which doesn't look right.

**Comment by krlmlr** [comment]
New anticipated release data: January 12.

**Comment by krlmlr** [comment]
We're planning to send igraph to CRAN on January 23.
