### ISSUE TITLE
Release DiagrammeR 1.0.11

### ISSUE THREAD

**Issue by olivroy** [rich-iannone/DiagrammeR#515]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_DiagrammeR.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [ ] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Update `cran-comments.md`
* [ ] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`

@rich-iannone , whenever you have the time, it would be worth doing a new release for igraph 2.0.0 compatibility?

**Comment by rich-iannone** [comment]
Thanks @olivroy , I will work through this release checklist right away!

**Comment by rich-iannone** [comment]
── CHECK ────────────────────────────────────────────────────────────────────────── 97 packages ──
✔ airGRiwrm 0.6.2                        ── E: 0     | W: 0     | N: 0                            
✔ behaviorchange 0.5.5                   ── E: 0     | W: 0     | N: 0                            
✔ actel 1.3.0                            ── E: 0     | W: 0     | N: 1                            
✖ bpmnR 0.1.1                            ── E: 0  +1 | W: 0     | N: 0                            
✔ causact 0.5.3                          ── E: 0     | W: 0     | N: 1                            
I changepoints 1.1.0                     ── E: 1     | W: 0     | N: 0                            
✖ BiocPkgTools 1.20.0                    ── E: 0  +1 | W: 0     | N: 1                            
✔ cohorttools 0.1.6                      ── E: 0     | W: 0     | N: 0                            
✔ consortr 0.9.1                         ── E: 0     | W: 0     | N: 0                            
✔ consort 1.2.1                          ── E: 0     | W: 0     | N: 0                            
✔ constructive 0.2.0                     ── E: 0     | W: 0     | N: 0                            
✔ criticalpath 0.2.1                     ── E: 0     | W: 0     | N: 0                            
✔ critpath 0.2.2                         ── E: 0     | W: 0     | N: 1                            
✔ data.tree 1.1.0                        ── E: 0     | W: 0     | N: 0                            
✔ distill 1.6                            ── E: 0     | W: 0     | N: 0                            
✔ drf 1.1.0                              ── E: 0     | W: 0     | N: 2                            
✔ dm 1.0.10                              ── E: 0     | W: 0     | N: 0                            
✔ fishdata 1.0.1                         ── E: 0     | W: 0     | N: 0                            
✔ escalation 0.1.5                       ── E: 0     | W: 0     | N: 1                            
✔ GE 0.4.2                               ── E: 0     | W: 0     | N: 0                            
I gap 1.5.3                              ── E: 1     | W: 0     | N: 0                            
✔ geogenr 2.0.1                          ── E: 0     | W: 0     | N: 1                            
✔ greta 0.4.4                            ── E: 0     | W: 0     | N: 0                            
✔ GNET2 1.18.0                           ── E: 0     | W: 0     | N: 0                            
✔ grPipe 0.1.0                           ── E: 0     | W: 0     | N: 0                            
✔ hablar 0.3.2                           ── E: 0     | W: 0     | N: 0                            
✔ grf 2.3.1                              ── E: 0     | W: 0     | N: 1                            
✔ holiglm 0.2.6                          ── E: 0     | W: 0     | N: 0                            
✔ heuristicsmineR 0.3.0                  ── E: 0     | W: 0     | N: 0                            
✔ integr 1.0.0                           ── E: 0     | W: 0     | N: 0                            
✔ irboost 0.1.1.3                        ── E: 0     | W: 0     | N: 0                            
✔ irg 0.1.6                              ── E: 0     | W: 0     | N: 0                            
✔ inlabru 2.10.1                         ── E: 0     | W: 0     | N: 1                            
✔ justifier 0.2.6                        ── E: 0     | W: 0     | N: 0                            
✔ irtrees 1.0.0                          ── E: 0     | W: 0     | N: 0                            
✔ lavaanPlot 0.8.1                       ── E: 0     | W: 0     | N: 1                            
✔ m2b 1.0                                ── E: 0     | W: 0     | N: 1                            
✔ muir 0.1.0                             ── E: 0     | W: 0     | N: 1                            
I markovchain 0.9.5                      ── E: 1     | W: 0     | N: 1                            
✔ netSEM 0.6.2                           ── E: 0     | W: 0     | N: 0                            
✔ multitool 0.1.3                        ── E: 0     | W: 0     | N: 1                            
✔ mapping 1.4.1                          ── E: 0     | W: 0     | N: 1                            
✔ optimall 0.1.4                         ── E: 0     | W: 0     | N: 0                            
✔ oncomsm 0.1.4                          ── E: 0     | W: 0     | N: 1                            
✔ PaRe 0.1.12                            ── E: 0     | W: 0     | N: 0                            
✔ petrinetR 0.3.0                        ── E: 0     | W: 0     | N: 0                            
✔ piecewiseSEM 2.3.0                     ── E: 0     | W: 0     | N: 0                            
✔ pillar 1.9.0                           ── E: 0     | W: 0     | N: 0                            
✔ planr 0.3.0                            ── E: 0     | W: 0     | N: 0                            
✔ policytree 1.2.2                       ── E: 0     | W: 0     | N: 0                            
✔ primer 1.2.0                           ── E: 0     | W: 0     | N: 1                            
✔ poolfstat 2.2.0                        ── E: 0     | W: 0     | N: 0                            
✔ PRISMA2020 1.1.1                       ── E: 0     | W: 0     | N: 0                            
✔ prismadiagramR 1.0.0                   ── E: 0     | W: 0     | N: 0                            
✔ PRISMAstatement 1.1.1                  ── E: 0     | W: 0     | N: 1                            
✔ processanimateR 1.0.5                  ── E: 0     | W: 0     | N: 1                            
✔ nullranges 1.8.0                       ── E: 0     | W: 0     | N: 2                            
✔ processmapR 0.5.3                      ── E: 0     | W: 0     | N: 0                            
✔ profile 1.0.3                          ── E: 0     | W: 0     | N: 0                            
✔ psidread 1.0.2                         ── E: 0     | W: 0     | N: 0                            
✔ psyverse 0.2.6                         ── E: 0     | W: 0     | N: 1                            
✔ pTITAN2 1.0.2                          ── E: 0     | W: 0     | N: 0                            
✔ pvda 0.0.2                             ── E: 0     | W: 0     | N: 0                            
✔ public.ctn0094data 1.0.6               ── E: 0     | W: 0     | N: 0                            
✔ Rage 1.6.0                             ── E: 0     | W: 0     | N: 0                            
✔ radiant.model 1.6.3                    ── E: 0     | W: 0     | N: 0                            
✔ randomForestSRC 3.2.3                  ── E: 0     | W: 0     | N: 0                            
✔ RavenR 2.2.0                           ── E: 0     | W: 0     | N: 0                            
✔ rdecision 1.2.0                        ── E: 0     | W: 0     | N: 0                            
✔ Rcwl 1.18.0                            ── E: 0     | W: 0     | N: 2                            
✔ RFpredInterval 1.0.8                   ── E: 0     | W: 0     | N: 0                            
✔ Rgff 0.1.6                             ── E: 0     | W: 0     | N: 1                            
✔ robotoolbox 1.3.2                      ── E: 0     | W: 0     | N: 1                            
✔ rock 0.8.1                             ── E: 0     | W: 0     | N: 1                            
✔ rocTree 1.1.1                          ── E: 0     | W: 0     | N: 1                            
✔ rolog 0.9.14                           ── E: 0     | W: 0     | N: 1                            
✔ rolap 2.5.1                            ── E: 1     | W: 0     | N: 2                            
I sem 3.1.15                             ── E: 1     | W: 0     | N: 0                            
✔ sbfc 1.0.3                             ── E: 0     | W: 0     | N: 0                            
✔ sewage 0.2.5                           ── E: 0     | W: 0     | N: 0                            
✖ seminr 2.3.2                           ── E: 0  +1 | W: 0     | N: 2                            
✔ simmer.plot 0.1.18                     ── E: 0     | W: 0     | N: 0                            
I stratEst 1.1.6                         ── E: 1     | W: 0     | N: 0                            
✔ SpaDES.core 2.0.3                      ── E: 0     | W: 0     | N: 2                            
I sits 1.4.2.1                           ── E: 1     | W: 0     | N: 0                            
✔ tibble 3.2.1                           ── E: 0     | W: 0     | N: 0                            
✔ teachingApps 1.0.8                     ── E: 0     | W: 1     | N: 2                            
✔ simona 1.0.6                           ── E: 0     | W: 0     | N: 2                            
✔ ttgsea 1.10.0                          ── E: 0     | W: 0     | N: 0                            
✔ trialr 0.1.6                           ── E: 0     | W: 0     | N: 2                            
✔ umx 4.19.0                             ── E: 0     | W: 0     | N: 2                            
✔ vtree 5.6.5                            ── E: 0     | W: 0     | N: 0                            
✔ when 1.0.0                             ── E: 1     | W: 0     | N: 1                            
✔ VAExprs 1.8.0                          ── E: 0     | W: 0     | N: 1                            
✔ ViSEAGO 1.16.0                         ── E: 0     | W: 3     | N: 2                            
✔ xgboost 1.7.7.1                        ── E: 0     | W: 0     | N: 2                            
[96/97] 00:41:07 | ETA: 26s | OK: 94                                                            
BROKEN: 3
Total time: 41 min
── REPORT ────────────────────────────────────────────────────────────────────────────────────────

**Comment by olivroy** [comment]
Just checked bmpmR, 

calls `render_graph(layout = "neato")`, not accepted? should we change this to a warning ?

Due to https://github.com/rich-iannone/DiagrammeR/pull/507

I will review.

**Comment by rich-iannone** [comment]
── CHECK ────────────────────────────────────────────────────────────────────────── 97 packages ──
✔ airGRiwrm 0.6.2                        ── E: 0     | W: 0     | N: 0                            
✔ actel 1.3.0                            ── E: 0     | W: 0     | N: 1                            
✔ behaviorchange 0.5.5                   ── E: 0     | W: 0     | N: 0                            
✔ bpmnR 0.1.1                            ── E: 0     | W: 0     | N: 0                            
✔ causact 0.5.3                          ── E: 0     | W: 0     | N: 1                            
✔ BiocPkgTools 1.20.0                    ── E: 0     | W: 0     | N: 1                            
I changepoints 1.1.0                     ── E: 1     | W: 0     | N: 0                            
✔ cohorttools 0.1.6                      ── E: 0     | W: 0     | N: 0                            
✔ consortr 0.9.1                         ── E: 0     | W: 0     | N: 0                            
✔ consort 1.2.1                          ── E: 0     | W: 0     | N: 0                            
✔ constructive 0.2.0                     ── E: 0     | W: 0     | N: 0                            
✔ criticalpath 0.2.1                     ── E: 0     | W: 0     | N: 0                            
✔ critpath 0.2.2                         ── E: 0     | W: 0     | N: 1                            
✔ data.tree 1.1.0                        ── E: 0     | W: 0     | N: 0                            
✔ distill 1.6                            ── E: 0     | W: 0     | N: 0                            
✔ dm 1.0.10                              ── E: 0     | W: 0     | N: 0                            
✔ fishdata 1.0.1                         ── E: 0     | W: 0     | N: 0                            
✔ drf 1.1.0                              ── E: 0     | W: 0     | N: 2                            
I gap 1.5.3                              ── E: 1     | W: 0     | N: 0                            
✔ escalation 0.1.5                       ── E: 0     | W: 0     | N: 1                            
✔ GE 0.4.2                               ── E: 0     | W: 0     | N: 0                            
✔ geogenr 2.0.1                          ── E: 0     | W: 0     | N: 1                            
✔ GNET2 1.18.0                           ── E: 0     | W: 0     | N: 0                            
✔ bioCancer 1.30.0                       ── E: 2     | W: 0     | N: 1                            
✔ greta 0.4.4                            ── E: 0     | W: 0     | N: 0                            
✔ grPipe 0.1.0                           ── E: 0     | W: 0     | N: 0                            
✔ hablar 0.3.2                           ── E: 0     | W: 0     | N: 0                            
✔ grf 2.3.1                              ── E: 0     | W: 0     | N: 1                            
✔ holiglm 0.2.6                          ── E: 0     | W: 0     | N: 0                            
✔ heuristicsmineR 0.3.0                  ── E: 0     | W: 0     | N: 0                            
✔ integr 1.0.0                           ── E: 0     | W: 0     | N: 0                            
✔ inlabru 2.10.1                         ── E: 0     | W: 0     | N: 1                            
✔ irboost 0.1.1.3                        ── E: 0     | W: 0     | N: 0                            
✔ irg 0.1.6                              ── E: 0     | W: 0     | N: 0                            
✔ irtrees 1.0.0                          ── E: 0     | W: 0     | N: 0                            
✔ justifier 0.2.6                        ── E: 0     | W: 0     | N: 0                            
✔ lavaanPlot 0.8.1                       ── E: 0     | W: 0     | N: 1                            
✔ m2b 1.0                                ── E: 0     | W: 0     | N: 1                            
I markovchain 0.9.5                      ── E: 1     | W: 0     | N: 1                            
✔ muir 0.1.0                             ── E: 0     | W: 0     | N: 1                            
✔ multitool 0.1.3                        ── E: 0     | W: 0     | N: 1                            
✔ mapping 1.4.1                          ── E: 0     | W: 0     | N: 1                            
✔ netSEM 0.6.2                           ── E: 0     | W: 0     | N: 0                            
✔ optimall 0.1.4                         ── E: 0-1   | W: 0     | N: 0                            
✔ PaRe 0.1.12                            ── E: 0     | W: 0     | N: 0                            
✔ oncomsm 0.1.4                          ── E: 0     | W: 0     | N: 1                            
✔ petrinetR 0.3.0                        ── E: 0     | W: 0     | N: 0                            
✔ piecewiseSEM 2.3.0                     ── E: 0     | W: 0     | N: 0                            
✔ pillar 1.9.0                           ── E: 0     | W: 0     | N: 0                            
✔ nullranges 1.8.0                       ── E: 0     | W: 0     | N: 1                            
✔ planr 0.3.0                            ── E: 0     | W: 0     | N: 0                            
✔ policytree 1.2.2                       ── E: 0     | W: 0     | N: 0                            
✔ primer 1.2.0                           ── E: 0     | W: 0     | N: 1                            
✔ poolfstat 2.2.0                        ── E: 0     | W: 0     | N: 0                            
✔ PRISMA2020 1.1.1                       ── E: 0     | W: 0     | N: 0                            
✔ prismadiagramR 1.0.0                   ── E: 0     | W: 0     | N: 0                            
✔ PRISMAstatement 1.1.1                  ── E: 0     | W: 0     | N: 1                            
✔ processanimateR 1.0.5                  ── E: 0     | W: 0     | N: 1                            
✔ processmapR 0.5.3                      ── E: 0     | W: 0     | N: 0                            
✔ profile 1.0.3                          ── E: 0     | W: 0     | N: 0                            
✔ psidread 1.0.2                         ── E: 0     | W: 0     | N: 0                            
✔ psyverse 0.2.6                         ── E: 0     | W: 0     | N: 1                            
✔ pTITAN2 1.0.2                          ── E: 0     | W: 0     | N: 0                            
✔ public.ctn0094data 1.0.6               ── E: 0     | W: 0     | N: 0                            
✔ pvda 0.0.2                             ── E: 0     | W: 0     | N: 0                            
✔ Rage 1.6.0                             ── E: 0     | W: 0     | N: 0                            
✔ radiant.model 1.6.3                    ── E: 0     | W: 0     | N: 0                            
✔ randomForestSRC 3.2.3                  ── E: 0     | W: 0     | N: 0                            
✔ RavenR 2.2.0                           ── E: 0     | W: 0     | N: 0                            
✔ Rcwl 1.18.0                            ── E: 0     | W: 0     | N: 2                            
✔ rdecision 1.2.0                        ── E: 0     | W: 0     | N: 0                            
✔ Rgff 0.1.6                             ── E: 0     | W: 0     | N: 1                            
✔ RFpredInterval 1.0.8                   ── E: 0     | W: 0     | N: 0                            
✔ robotoolbox 1.3.2                      ── E: 0     | W: 0     | N: 1                            
✔ rock 0.8.1                             ── E: 0     | W: 0     | N: 1                            
✔ rocTree 1.1.1                          ── E: 0     | W: 0     | N: 1                            
✔ rolap 2.5.1                            ── E: 1     | W: 0     | N: 2                            
✔ rolog 0.9.14                           ── E: 0     | W: 0     | N: 1                            
I sem 3.1.15                             ── E: 1     | W: 0     | N: 0                            
✔ sbfc 1.0.3                             ── E: 0     | W: 0     | N: 0                            
✔ sewage 0.2.5                           ── E: 0     | W: 0     | N: 0                            
✔ simmer.plot 0.1.18                     ── E: 0     | W: 0     | N: 0                            
✔ seminr 2.3.2                           ── E: 0-1   | W: 0     | N: 2                            
I sits 1.4.2.1                           ── E: 1     | W: 0     | N: 0                            
✔ simona 1.0.6                           ── E: 0     | W: 0     | N: 2                            
I stratEst 1.1.6                         ── E: 1     | W: 0     | N: 0                            
✔ SpaDES.core 2.0.3                      ── E: 0     | W: 0     | N: 2                            
✔ tibble 3.2.1                           ── E: 0     | W: 0     | N: 0                            
✔ teachingApps 1.0.8                     ── E: 0     | W: 1     | N: 2                            
✔ ttgsea 1.10.0                          ── E: 0     | W: 0     | N: 0                            
✔ umx 4.19.0                             ── E: 0     | W: 0     | N: 2                            
✔ trialr 0.1.6                           ── E: 0     | W: 0     | N: 2                            
✔ VAExprs 1.8.0                          ── E: 0     | W: 0     | N: 1                            
✔ ViSEAGO 1.16.0                         ── E: 0     | W: 3     | N: 2                            
✔ vtree 5.6.5                            ── E: 0     | W: 0     | N: 0                            
✔ when 1.0.0                             ── E: 1     | W: 0     | N: 1                            
✔ xgboost 1.7.7.1                        ── E: 0     | W: 0     | N: 2                            
OK: 97                                                                                          
BROKEN: 0
Total time: 36 min

**Comment by rich-iannone** [comment]
> Just checked bmpmR,
> 
> calls `render_graph(layout = "neato")`, not accepted? should we change this to a warning ?
> 
> Due to #507
> 
> I will review.
> 
> Could not reproduce seminr failure locally and BiocPkgTools doesn't seem to use DiagrammeR in code even if it is in Suggests.

I just did the same thing! Pushed a few similar changes to the release branch PR. All revdep checks pass now. I'll resubmit to CRAN shortly.

**Comment by rich-iannone** [comment]
Just resubmitted to CRAN with an apology :/
