### ISSUE TITLE
Bug on Windows + RStudio + IExplorer + Mermaid

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#54]
There is a strange bug in Internet Explorer. When I create a graph with Mermaid on Rstudio, I see the Diagram in the Viewer (as expected).

Then I click the button to open it in a browser. On my work laptop, IE is default without a way to change it (of course).
Then... I got just that:
```
NoModificationAllowedError
```
I copy paste the link to Chrome and I see again my diagram.

I have IE 11.0.9600...
Windows 8.1 64 bits

Sorry to bring such horrible IE bugs here. May be there are other poor guys who need to use IE and will want to use DiagrammeR. However, in my specific case, I don't really care, I never use IE, but for some other, may be mandatory.

**Comment by rich-iannone** [comment]
I'm at somewhat of a disadvantage here because I'm developing on a Mac. However, this brings up an important point about testing for cross-browser compatibility (and at least reporting the results). I will get my VMWare Fusion up and running again soon and test across several browsers and several versions of them. That would then be a start toward possible bug fixes.

**Comment by pommedeterresautee** [comment]
let me know if you want me to run specific test.

http://stackoverflow.com/questions/24397135/why-does-changing-svg-bounding-box-throw-nomodificationallowederror-in-interne

**Comment by timelyportfolio** [comment]
I'll check but it looks like an issue with `mermaid`, so don't think we can do much here except file an issue over there and see if they deem it worthwhile.  Thanks for all the tests.

**Comment by rich-iannone** [comment]
This will be an ongoing issue we'll keep getting back to. With the browser compatibility table available now (and with occasionally checks as new versions roll out), I think I can close this.
