### ISSUE TITLE
Vignette not built

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#6]
I have no experience with writing / building vignette, but I don't see any reference to it in the built package but I see the source file.

Do I have something special to do during the compilation?
```
brary/3.1'
* installing *source* package 'DiagrammeR' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (DiagrammeR)
```

Help page:
```
Documentation for package ‘DiagrammeR’ version 0.01

DESCRIPTION file.
Help Pages

DiagrammeR	R + mermaid.js
DiagrammeROutput	Widget output function for use in Shiny
renderDiagrammeR	Widget render function for use in Shiny
```

**Comment by rich-iannone** [comment]
Having some difficulty getting the vignette source to compile, so, definitely looking into this. Hope to resolve this quickly.

**Comment by timelyportfolio** [comment]
is it as simple as `devtools::install_github(rich-iannone/DiagrammeR,build_vignettes = TRUE)` ?  Vignettes are not built by default with `devtools`.  Does this [chapter about vignettes](http://r-pkgs.had.co.nz/vignettes.html) in the @hadley book help?

**Comment by rich-iannone** [comment]
@timelyportfolio now can build. Had to update my local install of the knitr package.
