### ISSUE TITLE
docs for rstudio previewing / graphviz engine specification

### ISSUE THREAD

**Issue by jjallaire** [rich-iannone/DiagrammeR#64]
We are planning on releasing a new RStudio Preview on Tuesday that will have the new mermaid.js and graphviz authoring features in it. Once we have this I think it would be good to provide:

(a) A link to the preview release page so that users get the right version

(b) An example (perhaps a screenshot)

(c) Perhaps update the graphviz docs on engines to show how to specify the engine directly as a graph attribute (e.g. `layout = neato`). This is because RStudio calls DiagrammeR with the default arguments so there's no way to preview a non-default engine unless it's specified as part of the graphviz definition. 

If this is viewed as problematic we could do one other thing: allow the user to include a comment that notifies any previewer of the preferred engine. We do something similar to this for Sweave engines (this in turn was adapted from the behavior of popular LaTeX editors). e.g. you can add `% !Rnw weave = knitr` at the top of a Sweave document to tell us to preview it with knitr rather than Sweave. So we could do something like this:

```cpp
// !Graphviz engine = neato
```

This is obviously one more thing to implement and learn so if it's considered generally okay to put the engine in the graphviz definition that's simpler and thus preferred. Let me know what you think either way so I can get this into the preview for Tuesday.

**Comment by jjallaire** [comment]
BTW the daily build of RStudio has the DiagrammeR support now. You can check it out here: http://www.rstudio.org/download/daily/desktop/

**Comment by rich-iannone** [comment]
Just recently I revamped the DiagrammeR gh-pages website, it's at:

http://rich-iannone.github.io/DiagrammeR/

I did this because I wanted to make a sort of landing page with examples in it (none in there yet but I'm soliciting use case examples from others in diverse fields). I did make mention of the syntax coloring in the documentation and I included a screenshot. It's here:

http://rich-iannone.github.io/DiagrammeR/graphviz.html

I stated that a recently daily build was required (but couldn't provide the exact build number when that feature was added). I will update to provide that link for the daily build, and, will update again when the preview release is available.

I did notice that pressing Preview issued the `grViz` function, taking in the text from the working file and the default arguments. I did make some simple modifications to ensure that the templating with `@@` was the default. I've also thought along the same lines about placing the rendering engine choice within the document. My thinking is that I do want to extend the functionality of the footnote area (the bonus advantage is that the Graphviz parser ignores *everything* after `graph { ... }`). So, I might just expose that functionality with a simple key-value pair like:

`engine = neato`

It should be very easy to implement, and, quite easy to document as well.

On the topic of simple fixes, I noticed a small typo for this support: spelling in RStudio should be "Graphviz" and not "GraphViz".

Thanks again for supporting this package in RStudio! I think it has a lot of potential and many seem to be using it (or are interested in doing so).

**Comment by jjallaire** [comment]
The new website looks spectacular!!!!!

The DiagrammeR works is now in our official preview release (v0.99.233).
This is the link you can use to let people know how to download it:

http://www.rstudio.com/products/rstudio/download/preview/

**Comment by rich-iannone** [comment]
Thanks for liking it! Take a look at this page and let me know if it looks good to you:

http://rich-iannone.github.io/DiagrammeR/docs.html

Tonight I will continue working on the `mermaid` documentation. Then, onto the examples gallery on the main page.

By the way, I included you in the list of contributors (in the footer section of each page). Hope that's alright.

**Comment by jjallaire** [comment]
Looks fantastic all around!

One thing I might suggest is to add some documentation on using graphics generated by DiagrammeR. To me there would be three main use cases:

1. Include in an R Markdown report or presentation

2. Create a standalone graphic or web page

3. Include in a Shiny application

To me it seems like the first is the principle use case but there might be an awful lot of #2 going on for users that are e.g pasting into MS Office on email.

These are the docs I created around this for dygraphs: http://rstudio.github.io/dygraphs/r-console.html. Another example for networkD3: http://christophergandrud.github.io/networkD3/#networkD3output

One output option not mentioned at all in either of these is exporting a PNG or copying the widget to the clipboard. Both of these are possible from within the RStudio viewer.

Net: perhaps another top level section titled "Using" which outlines the various options for usage / output. This is so important that you might want to also link to it from the bottom of Getting Started.

**Comment by rich-iannone** [comment]
This is all very good and I'll definitely include this. Thanks for the example docs, those look very clear. Agree that this should be upfront as much as possible. I've had a few people asking about export options so this is undoubtedly important material.

**Comment by jjallaire** [comment]
Given how important output is I'd suggest including a top-level section called "Output" (in preference to "Usage" which I suggested earlier). In the opening sentence/paragraph it would be helpful to say that DiagrammeR supports many output types including export to graphic, R Markdown, Shiny, etc. (this is just to assure the reader that they will definitely be able to get the output where they need it). After that I think a section on R Markdown (which is IMHO the preferred way to use DiagrammeR), a section on export to PNG, HTML, etc. and then a section Shiny.

For the section on exporting, a picture may be worth many words. You could try a variation of this screenshot:

![screen shot 2015-02-09 at 9 57 57 pm](https://cloud.githubusercontent.com/assets/104391/6120662/beebe69a-b0a6-11e4-8861-8bd159edb7d0.png)

**Comment by rich-iannone** [comment]
Thanks for the direction on this. The documentation is starting to really come along!

I've started working on this and have indeed included a top-level section (I will put in some basic controls near the footer to move between sections). So far, just the viewing and export options from the Viewer are on the live site. I will address R Markdown and Shiny next (and I'll use the recommended order as suggested). Feel free to comment on this early version.

**Comment by jjallaire** [comment]
That looks great. I'd say just make sure that the first paragraph mentions
R Markdown and Shiny just so folks know that's possible. The section on
output from the Viewer is excellent!!! (best I've seen by any htmlwidget)

**Comment by rich-iannone** [comment]
Thanks again! I believe the docs are extremely important for package (especially given how customizable the **Graphviz** output can be). So, I'll spend a considerable amount of time iterating on the documentation.

I added a bit more to the section. Called it "I/O" because there is a lot to be said about the input methods (e.g., dedicated file types, **R Markdown**, **R** scripts, etc.). Have another look. I'll keep adding content at a steady clip.

**Comment by jjallaire** [comment]
Looking great!

I would flip the order of RStudio Viewer and R Markdown (but mention R
Markdown in the first pargraph so people know it's possible). My thinking
is that even though R Markdown is the preferred way to work there are tons
of people who still just want something they can copy and paste and I want
everyone to know that's possible.

**Comment by jjallaire** [comment]
FYI I just added DiagrammeR to the htmlwidgets showcase:
http://www.htmlwidgets.org/showcase_diagrammer.html

If you think Graphviz would make a more interesting example let me know. In
that case it would be nice to have a Graphviz example that was on the order
of 6-8 lines of code so that the code and visualization are both above the
fold.

**Comment by rich-iannone** [comment]
Alight, I flipped the order and added a more informative leading paragraph.

Thanks for featuring and linking to the page! The `mermaid` graph doesn't render on the device I happened to be using (iPhone), so, I think there are still some issues to sort out with `mermaid`. The Graphviz plots should work. I have a nice example that showcases what could be done:

grViz("
digraph twopi {
node [shape = circle, style = filled, color = grey, label = '', fillcolor = red]
a
node [fillcolor = green]
b c d
node [fillcolor = orange]
edge [color = grey]
a -> {b c d}
b -> {e f g h i j}
c -> {k l m n o p}
d -> {q r s t u v}
}", engine = "twopi")

It presents much more nicely. It's a bit long, so I'll work on condensing a bit.

**Comment by jjallaire** [comment]
I tried that out and I agree it's still too long (see screenshot below)

![screen shot 2015-02-12 at 5 13 29 pm](https://cloud.githubusercontent.com/assets/104391/6178190/a3709cae-b2da-11e4-8e03-fc12866a6701.png)

**Comment by rich-iannone** [comment]
Here is a more condensed, yet still readable, version:

```
grViz(engine = "twopi", "
digraph twopi {
node [shape = circle, style = filled, color = grey, label = '', fillcolor = red] a
[fillcolor = green] b c d ; node [fillcolor = orange] ; edge [color = grey]
a -> {b c d} ; b -> {e f g h i j} ; c -> {k l m n o p} ; d -> {q r s t u v} }")
```

Tested it and it does render the same diagram.

**Comment by jjallaire** [comment]
That runs into some width problems (see below). One of the concepts behind these examples is to illustrate how small bits of code can yield compelling results. I think having so much graphviz code for the example works a bit against that. Something very simple like your mermaid examples would I think be best.

![screen shot 2015-02-13 at 5 29 55 am](https://cloud.githubusercontent.com/assets/104391/6185908/992080a4-b341-11e4-9848-6be1f1f87814.png)

**Comment by rich-iannone** [comment]
Sorry about that. Yes, simple is better. Try this:

```
grViz(engine = "twopi", "
digraph twopi {
node [shape = circle]
A -> {B C D} }")
```

That should strike a better balance between showing functionality and keeping it minimal.

**Comment by jjallaire** [comment]
That's great! Just updated the site with this example.
