### ISSUE TITLE
setting seed with grViz

### ISSUE THREAD

**Issue by martinez-bakker** [rich-iannone/DiagrammeR#72]
Hello,

I was having trouble making diagrams reproducible when using grViz and the neato engine. I tried setting start and startType attributes, using the documentation on the Graphviz website, but that didn't seem to work. I also tried setting the seed in R. Is it possible to set the seed in DiagrammeR? 

Thanks in advance. The program is awesome!

Cheers,
Micaela

**Comment by timelyportfolio** [comment]
Glad you like.  Please share any output that you can.  I know @rich-iannone is trying to collect examples from various domains.  Here is how to set a seed.

```
grViz(
  "digraph {A->B;}"
  ,engine="neato"
  ,options= list(start =1234)
)
```

**Comment by martinez-bakker** [comment]
Hello,

Thanks for the help!! Attached is the diagram that I made today for a
manuscript. You are welcome to post it as an example. It is representing an
age structured epidemiological model.

Cheers,
Micaela

On Sun, Mar 1, 2015 at 6:41 PM, timelyportfolio <notifications@github.com>
wrote:

> Glad you like. Please share any output that you can. I know @rich-iannone
> <https://github.com/rich-iannone> is trying to collect examples from
> various domains. Here is how to set a seed.
>
> grViz(
>   "digraph {A->B;}"
>   ,engine="neato"
>   ,options= list(start =1234)
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rich-iannone/DiagrammeR/issues/72#issuecomment-76638735>
> .
>



-- 
---
Micaela Martinez-Bakker

NSF Doctoral Fellow
Department of Ecology and Evolutionary Biology
The Center for the Study of Complex Systems
University of Michigan
2044 Kraus Nat. Sci. Bldg.
830 North University
Ann Arbor, MI 48109, USA

e-mail:micaela.martinezbakker@gmail.com

web:
my website <http://micaelamartinezbakker.com/>
my UMich page
<http://www.lsa.umich.edu/vgn-ext-templating/v/index.jsp?vgnextoid=e8502c76f0fe0410VgnVCM100000c2b1d38dRCRD&vgnextchannel=6d14bc5377b30410VgnVCM100000c2b1d38dRCRD&vgnextfmt=detail>
<http://www.lsa.umich.edu/eeb/people/grads/bakkerma.html>

I tweet about Infectious Disease Ecology @MartinezBakker
<https://twitter.com/MartinezBakker>

**Comment by timelyportfolio** [comment]
Glad it worked, and it is good for reference for others I'm sure.  Bummer, but pictures  don't come through on Github with email.  Can you copy/paste in comment, or upload somewhere like Imgur?  Very delighted that you are using it.

**Comment by rich-iannone** [comment]
Yes! Definitely try again with sending a picture and also code (if you can share it). The work will be placed in the DiagrammeR website as an example to inspire others.

**Comment by rich-iannone** [comment]
@timelyportfolio this is actually something I've been wondering about: making the neato-type graphs reproducible. I think it'll be important if we implement D3 transitions between changing/sequential graphs. We should talk more about that sort of thing...

**Comment by martinez-bakker** [comment]
Will post code and figure soon. Thanks!

On Sunday, March 1, 2015, Richard Iannone <notifications@github.com> wrote:

> Yes! Definitely try again with sending a picture and also code (if you can
> share it). The work will be placed in the DiagrammeR website as an example
> to inspire others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rich-iannone/DiagrammeR/issues/72#issuecomment-76650184>
> .
>


-- 
---
Micaela Martinez-Bakker

NSF Doctoral Fellow
Department of Ecology and Evolutionary Biology
The Center for the Study of Complex Systems
University of Michigan
2044 Kraus Nat. Sci. Bldg.
830 North University
Ann Arbor, MI 48109, USA

e-mail:micaela.martinezbakker@gmail.com

web:
my website <http://micaelamartinezbakker.com/>
my UMich page
<http://www.lsa.umich.edu/vgn-ext-templating/v/index.jsp?vgnextoid=e8502c76f0fe0410VgnVCM100000c2b1d38dRCRD&vgnextchannel=6d14bc5377b30410VgnVCM100000c2b1d38dRCRD&vgnextfmt=detail>
<http://www.lsa.umich.edu/eeb/people/grads/bakkerma.html>

I tweet about Infectious Disease Ecology @MartinezBakker
<https://twitter.com/MartinezBakker>

**Comment by martinez-bakker** [comment]
Hi Guys,

Here is the link the the digram example code and output:

https://github.com/martinez-bakker/SIR-schematic-in-diagrammeR

On Sun, Mar 1, 2015 at 9:32 PM, Richard Iannone <notifications@github.com>
wrote:

> Yes! Definitely try again with sending a picture and also code (if you can
> share it). The work will be placed in the DiagrammeR website as an example
> to inspire others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rich-iannone/DiagrammeR/issues/72#issuecomment-76650184>
> .
>



-- 
---
Micaela Martinez-Bakker

NSF Doctoral Fellow
Department of Ecology and Evolutionary Biology
The Center for the Study of Complex Systems
University of Michigan
2044 Kraus Nat. Sci. Bldg.
830 North University
Ann Arbor, MI 48109, USA

e-mail:micaela.martinezbakker@gmail.com

web:
my website <http://micaelamartinezbakker.com/>
my UMich page
<http://www.lsa.umich.edu/vgn-ext-templating/v/index.jsp?vgnextoid=e8502c76f0fe0410VgnVCM100000c2b1d38dRCRD&vgnextchannel=6d14bc5377b30410VgnVCM100000c2b1d38dRCRD&vgnextfmt=detail>
<http://www.lsa.umich.edu/eeb/people/grads/bakkerma.html>

I tweet about Infectious Disease Ecology @MartinezBakker
<https://twitter.com/MartinezBakker>

**Comment by timelyportfolio** [comment]
Very nice @martinez-bakker ; thanks so much for sharing.

**Comment by timelyportfolio** [comment]
@martinez-bakker I'm so happy you did this and even happier that you shared.  Can we close this one?  Thanks again. Any new ones?

**Comment by martinez-bakker** [comment]
Actually, last week I was working with a more complicated diagram and set
the seed, but I was still getting different orientations.

On Tuesday, April 7, 2015, timelyportfolio <notifications@github.com> wrote:

> @martinez-bakker <https://github.com/martinez-bakker> I'm so happy you
> did this and even happier that you shared. Can we close this one? Thanks
> again. Any new ones?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rich-iannone/DiagrammeR/issues/72#issuecomment-90791498>
> .
>


-- 
---
Micaela Martinez-Bakker

NSF Doctoral Fellow
Department of Ecology and Evolutionary Biology
The Center for the Study of Complex Systems
University of Michigan
2044 Kraus Nat. Sci. Bldg.
830 North University
Ann Arbor, MI 48109, USA

e-mail:micaela.martinezbakker@gmail.com

web:
my website <http://micaelamartinezbakker.com/>
my UMich page
<http://www.lsa.umich.edu/vgn-ext-templating/v/index.jsp?vgnextoid=e8502c76f0fe0410VgnVCM100000c2b1d38dRCRD&vgnextchannel=6d14bc5377b30410VgnVCM100000c2b1d38dRCRD&vgnextfmt=detail>
<http://www.lsa.umich.edu/eeb/people/grads/bakkerma.html>

I tweet about Infectious Disease Ecology @MartinezBakker
<https://twitter.com/MartinezBakker>
