### ISSUE TITLE
Graphing nested list objects for source code workflow

### ISSUE THREAD

**Issue by wbuchanan** [rich-iannone/DiagrammeR#76]
I was wondering if there were any more of less automatic ways to use your package to create graphs based on the logic flow of R source code (i.e., put the condition of an if statement in a diamond shaped object and use an edge to show the contents within the if block that depend on the condition being satisfied)?  Not sure if this was something you were already working on or not, but thought it would be a great contribution if there was a tutorial that could show how to do something like that.

**Comment by timelyportfolio** [comment]
The parsing piece will be more difficult than the drawing piece.  Do you have code already that would handle the parsing piece?  I also think it would be really nice to graph magrittr/pipeR pipes.

**Comment by wbuchanan** [comment]
I don't have any code for the parsing piece unfortunately.  But given how time consuming it is to create workflow diagrams it seems like this could be a great contribution and even something that Hadley would possibly consider integrating into devtools to make the development process more robust and provide output that would be familiar to IT professionals that are still skeptical about integrating R into their workflows.

**Comment by rich-iannone** [comment]
@wbuchanan This has been worked on, and, now, it's possible! Sorry for not chiming in earlier but you had the right idea. It just took a while to implement.
