### ISSUE TITLE
Override Gantt Chart to Allow Custom Date Axis Instead of 0-52 Week Scale

### ISSUE THREAD

**Issue by abresler** [rich-iannone/DiagrammeR#77]
Figure out a way to change this default behavior

**Comment by timelyportfolio** [comment]
Try this for now.  It is ugly.  @rich-iannone, I am concerned about polluting the parameters with lots of chart/diagram specific options especially as `mermaid` adds so many different types with different config options.  `gantt` is especially strange in how they have chosen to config.  It essentially sets config in the `mermaid` namespace in `window`.  I'm still trying to think of the best way to support this in a non-hacky way.

@abresler, for now, here is an example how you can change.

```r
library(Diagrammer)
library(htmltools)

m1 <- mermaid('
  gantt
    title Gantt With Custom Config
    section To fix
      check with Rich         :a1, 2015-03-09, 2d
      add custom config param :a2, after a1, 20d
      get bresler feedback    :a3, after a2,  2d
',height = 200)

# make a copy so we can compare in a tag list later
m2 <- m1

m2$x$config = list(ganttConfig = list(
  # a little tricky setup in what is already a hack
  #  treat this like a filter function with filter as second component in array
  #  and the time formatter in the first
  #  more than likely you will want to know your scale
  axisFormatter = list(list(
    "%b %d, %Y" # date format to return; see d3 time formatting
    ,htmlwidgets::JS(
      'function(d){ return d.getDay() == 1 }' # filter for Mondays or day of week = 1
    )
  ))
))


html_print(tagList(
  tags$h1("Default Behavior")
  ,m1
  ,tags$h1("Hacked Behavior")
  ,m2
))
```

**Comment by zeigerpuppy** [comment]
Is it possible to use this same trick to get rid of `sidePadding`?
There is too much space on the side of the plot produced

**Comment by zeigerpuppy** [comment]
Ah, I'll answer my own question, yes it is possible, just use the following syntax:

```R
m2$x$config = list(ganttConfig = list(
  sidePadding = 0,
  axisFormatter = list(list(
    "%b %d, %Y" # date format to return; see d3 time formatting
    ,htmlwidgets::JS(
      'function(d){ return d.getDay() == 1 }' # filter for Mondays or day of week = 1
    )
  ))
))
```

**Comment by corinabioinformatic** [comment]
I was able to use the example provided by @timelyportfolio but I did not get the axis properly (just years, and one month/year?)
I also opened a ticket [here](https://stackoverflow.com/questions/55855853/change-font-and-time-aixis-labels-in-dyagrammermermaidgantt-chart/76102413#76102413)

<img width="790" alt="diagrammeR_mermaid_xAxisFormatt_error" src="https://user-images.githubusercontent.com/14955321/234312298-683c25c5-b614-48e8-8660-4039f19b4d03.PNG">
