### ISSUE TITLE
the default width for foreignobject class is too narrow to display the label on link properly for mermaid graph

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#80]
Most of the texts I have on my graph are displayed in half for the last character.

**Comment by timelyportfolio** [comment]
I think I understand, but please provide a reproducible example, so we can work through this.

**Comment by happyshows** [comment]
sorry my bad. I think it might be some conflict with shinydashboard, which I use regularly.
It works okay when shinydashboard is not included.

library(shiny)
library(shinydashboard)

test <- "graph LR;v1(A)==>|E|v3(B);v2(C)==>|93.4|v4(D);v3(E)==>|E|v2(F);v4(C)==>|99.0|v5(E);v5(E)==>|99.0|v6(X);"

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(fluidPage(
           DiagrammeROutput('diagram')
  ))
)

server <- function(input, output) { 
  output$diagram <- renderDiagrammeR(DiagrammeR(
    test
  ))}

shinyApp(ui, server)
