### ISSUE TITLE
Use importFrom for V8

### ISSUE THREAD

**Issue by jeroenooms** [rich-iannone/DiagrammeR#85]
I have added a copy of the `JS` function from htmlwidgets to V8. This results in a warning for DiagrammeR:

> Found the following significant warnings:
> Warning: replacing previous import by ‘htmlwidgets::JS’ when loading ‘DiagrammeR’

I think the easiest way to resolve this is to use `importFrom(V8, new_context)` instead of `import(V8)`.

**Comment by rich-iannone** [comment]
Thanks very much for this! I've incorporated this change and there are no issues now.

**Comment by jeroenooms** [comment]
FYI a new version of V8 has been pushed to cran so you will start to see warnings about this: http://cran.r-project.org/web/checks/check_results_DiagrammeR.html
