### ISSUE TITLE
Documentation related to parameters width and height is not provided

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#9]
I am not sure of how it works. If you put a size too small it will be increased to what is required, if it is a value to high then it is too big, finally if no value is provided, the best value is choosen. Am I right?

**Comment by timelyportfolio** [comment]
I am planning to work on this.  `mermaid.js` currently offers no real support for exact sizing.

**Comment by pommedeterresautee** [comment]
Thanks for the information. In the example of the README height is used. 
I think it should be removed until it has a real purpose.

**Comment by timelyportfolio** [comment]
@pommedeterresautee @rich-iannone is this safe to close now?  I feel pretty good about `height` and `width`.

**Comment by pommedeterresautee** [comment]
For me it's OK to close the issue
