### ISSUE TITLE
Unicode test breaking graphs

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rich-iannone/DiagrammeR#92]
Hello, I've narrowed down a row in my edge graph that prevents the graphviz_graph() function working as it has unicode characters in it.

I'm trying to regex my way out to clean up the data, but it would be nice for a graceful fail or treatment of the Unicode in the package.  Here is some example problem data:

    Browse[3]> edges[170:175,]
    edge_from                                             edge_to arrowhead
    170 p56122012                                                  it      none
    171 p60080323                           Exclude GG IP VPN Struer      none
    172 p60080323                              Exclude GG IP VPN USA      none
    173 p60080323 Exclude GG IP VPN GeoPlay netv<U+00C3><U+00A6>rket      none
    174 p60080323                           Exclude GG IP VPN Lyngby      none
    175 p60080323                        Exclude GG IP VPN Singapore      none

    Browse[3]> edges[173,]
        edge_from                                             edge_to arrowhead
    173 p60080323 Exclude GG IP VPN GeoPlay netv<U+00C3><U+00A6>rket      none
    
    Browse[3]> str(edges[173,])
    'data.frame':	1 obs. of  3 variables:
     $ edge_from: chr "p60080323"
     $ edge_to  : chr "Exclude GG IP VPN GeoPlay netv\u00c3\u00a6rket"
     $ arrowhead: Factor w/ 1 level "none": 1

If I make a graph from 1:172 it works, but 1:173 it just displays a blank page.

**Comment by MarkEdmondson1234** [comment]
For now to fix it I did these two lines:

      edges$edge_from <- iconv(edges$edge_from, "UTF-8", "ASCII",sub="")
      edges$edge_to <-   iconv(edges$edge_to, "UTF-8", "ASCII",sub="")

**Comment by rich-iannone** [comment]
@MarkEdmondson1234 Ah, that's a good fix. It's interesting you brought this up because I have a bit of work done on another package that replaces Unicode characters with ASCII (https://github.com/rich-iannone/UnidecodeR). I probably should implement a check and quick fix for this. The `iconv` method is a good way of doing it though.

Also, if you have any ideas/requests for development in general, please feel free to post as issues. I'm beginning to start work on graph analysis functions (now that a graph object is available).

**Comment by MarkEdmondson1234** [comment]
What a coincidence :) UnidecodeR looks much neater, but not yet supporting the Danish of my example ;) æ, ø å etc, but I'll defo use it when it does, as just deleting them makes some names unreadable. 

My main problem is I can't control what people call their GA profiles/filters for when I import it for graphing.

**Comment by rich-iannone** [comment]
Mark,

If you send me replacements (æ = ae, etc.), for non-ASCII characters, I'll quickly include it in the UnidecodeR package! It's just harder to find the proper replacements for transliterations not part of an official standard.

Thanks!

**Comment by MarkEdmondson1234** [comment]
Ok will do - will consult with the Danish wife :)

**Comment by rich-iannone** [comment]
@MarkEdmondson1234 Great news: Danish support is now in the UnidecodeR package. Please test it out. Quick question: what are the Danish quotation characters?

**Comment by MarkEdmondson1234** [comment]
Thats great, thanks!  I will use it and see how it goes.  The Danish quotes are sometimes the UK ones (" " ) but also sometimes » and « appear.  Check out this leading Danish news site: http://www.b.dk/nationalt/27.-april-advarsel-til-letsindige-vejledning-til-uvidende
