### ISSUE TITLE
Adjust diagramme height and width in Shiny?

### ISSUE THREAD

**Issue by sdc3** [rich-iannone/DiagrammeR#93]
Hello,

The DiagrammeR package is great!
I try to do a diagramme using Shiny and modify the height and width using input sliders.
The app works, but moving the sliders does not affect the size of the output.
The idea would be to increase the size when the number of nodes is large.

Below is a code example.
What I am doing wrong? Do grVizOutput parameters overpass graphviz_render parameters?

Thank you for your help!

````r
library(shiny)
library(DiagrammeR)
library(magrittr)

##------------------------------------------
## ui function

ui = shinyUI(fluidPage( 
  fluidRow(
    column(
      width=3,
      textInput('x', 'Node Name', 'a'),
      sliderInput(inputId = "height", label = "Height", min = 0, max = 1000, value = 300, step = 100),
      sliderInput(inputId = "width", label = "Width", min = 0, max = 1000, value = 300, step = 100)
    ),
    column(
      width = 8
      , grVizOutput('diagram', height = "1000px", width = "1000px")
    )
  )
)
)


##------------------------------------------
## server function

server = function(input, output){
  
  output$diagram <- renderGrViz({
    
    create_nodes(nodes = c(input$x, "b", "c", "d")) %>%
      graphviz_graph  %>% 
      graphviz_render(output = "DOT", width = input$width, height = input$height) %>%
      grViz
    
  })
}


##------------------------------------------
## run app

shinyApp(ui = ui, server = server)


## sessionInfo()
## R version 3.1.2 (2014-10-31)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## magrittr_1.5      DiagrammeR_0.5    shiny_0.11.1.9004

## Firefox 37.0.2

````

**Comment by rich-iannone** [comment]
Thanks for using the package! I'm going to test out the Shiny code you wrote and see what's going wrong. Hope to get to that pretty soon....

**Comment by happyshows** [comment]
@sdc3 can you try use a renderUI to wrap the vizoutput and adjust height and width instead?
 grVizOutput('diagram', height = "1000px", width = "1000px")

**Comment by sdc3** [comment]
The renderUI/uiOutput seems to be a very good idea @happyshows. I was not familiar with this function but after watching this video https://www.youtube.com/watch?v=JUop-YfRAuw, I managed to write the code below.
Not sure it is the best way to do it, but it works :-)
Thanks.

````r
library(shiny)
library(DiagrammeR)
library(magrittr)

##------------------------------------------
## ui function

ui <- shinyUI(fluidPage( 
  fluidRow(
    column(
      width=3,
      textInput('x', 'Node Name', 'a'),
      sliderInput(inputId = "height", label = "Height", min = 0, max = 2000, value = 300, step = 200),
      sliderInput(inputId = "width", label = "Width", min = 0, max = 2000, value = 300, step = 200)
    ),
    column(
      width = 8,
      uiOutput('d')
    )
  )
)
)


##------------------------------------------
## server function

server <- function(input, output){
  
  output$diagram <- renderGrViz({
    
    create_nodes(nodes = c(input$x, "b", "c", "d")) %>%
      graphviz_graph  %>% 
      graphviz_render(output = "DOT") %>%
      grViz
    
  })
  
  output$d <- renderUI({
    grVizOutput('diagram', height = input$height, width = input$width)
  })
  
}


##------------------------------------------
## run app

shinyApp(ui = ui, server = server)


## R version 3.1.2 (2014-10-31)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## magrittr_1.5      DiagrammeR_0.5    shiny_0.11.1.9004
## Firefox 37.0.2
````

**Comment by rich-iannone** [comment]
@sdc3  @happyshows that is excellent stuff! Thanks for working through this problem and sharing the working code here. @sdc3 : do you mind if I include the code as an example in the README?

**Comment by sdc3** [comment]
No problem.

**Comment by DamienGeorges** [comment]
Hi all,

I would like to use the exact same feature than the one devel above by @ghost. Since this solution was posted, DiagrammeR package has been updated quite a lot (functions have been renamed/removed) and I can't manage to make this example work with the latest release. Does someone could help me to adapt the code for the current DiagrammeR?
Or any other solution that allow diagramme plotting window to be resized in Shiny app?

Thanks a lot,
Damien
