### ISSUE TITLE
htmlwidgets 0.3.3 compatiblity?

### ISSUE THREAD

**Issue by happyshows** [rich-iannone/DiagrammeR#96]
Hi,

I'm wondering whether the latest version is compatible with 0.3.3? The other widgets I'm currently using doesn't, yet.

**Comment by rich-iannone** [comment]
I loaded in v0.3.3 and ran most of the examples. Everything rendered as expected on a Windows 7 test machine. Hope that helps. Let me know if this is not your experience.

**Comment by happyshows** [comment]
@rich-iannone please run the following code in 0.3.3. Browser showed blank page, while in 0.3.2 it's fine....

diagram <- "
graph LR
  A-->B
  A-->C
  C-->E
  B-->D
  C-->D
  D-->F
  E-->F
"

server <- function(input, output) {
  output$test <- renderDiagrammeR({
    isolate({
      return(DiagrammeR(diagram))
    })  
  })
}

ui <- fluidPage(
  DiagrammeROutput('test',width = "100%", height = "760px") 
)

shinyApp(ui = ui, server = server)

**Comment by rich-iannone** [comment]
This seemed to work in the RStudio external browser window in Windows 7. So, this may be a browser compatibility issue. Could you provide the system/browser info here?

**Comment by happyshows** [comment]
I'm using Chrome on win 7. It didn't work in my Rstudio viewer either.
I'm using
R version 3.2.0 Patched (2015-05-02 r68310)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
htmlwidgets_0.3.3   
DiagrammeR_0.6 

The standalone version works fine in View and Chrome.
DiagrammeR(diagram)

**Comment by happyshows** [comment]
it's working already with 0.4.0 hence I'm closing the issue.

**Comment by rich-iannone** [comment]
Thanks for verifying!
