### ISSUE TITLE
Any way of rendering in Sweave?

### ISSUE THREAD

**Issue by richarddmorey** [rich-iannone/DiagrammeR#97]
DiagrammeR looks really great, and I plan on using it. Is there any way of getting DiagrammeR plots to be rendered by Sweave/knitr to PDF? (The "best" way I've found is using exportSVG to get an SVG file, and grConvert to get a ps file, then manually converting the ps file to pdf; but this is far from the simplicity of just running grVis in an Sweave R code chunk)

**Comment by rich-iannone** [comment]
Unfortunately there is no headless method for exporting to other formats at the moment. Me and several others explored this topic, recognizing that the lack of graphical export options through functions is a bit of a limitation. However, we found only complex solutions (e.g., using phantom.js to perform image conversion, which requires building all of WebKit on the client side). I really do want to be able to export diagrams to other image formats and I have several ideas I might be able to test out (e.g., using lighter JS libraries, if they exist for this purpose, or, using calls to ImageMagick).

It may be that the htmlwidgets package may introduce this functionality soon, so, I'll check in there and see if that's a priority for that package.

If you should be able to find a solution to this, and it looks like you've been doing just that, do let me know! In the meantime, I'll keep exploring ways to get this done.

**Comment by richarddmorey** [comment]
Well, if there were an easy way of converting ps to pdf, then one could add it to this:

    viz2ps = function(vis.file, ps.file, ...){
      (svg <- DiagrammeR::exportSVG(DiagrammeR::grViz(vis.file, ...)))
      svg.fn = tempfile()
      cat(svg, file=svg.fn)
      grConvert::convertPicture(svg.fn, outfile = ps.file, inputFormat = "svg", outputFormat = "ps")
    }

but `grConvert` is not on CRAN and requires SVG libraries installed. So it isn't a generally workable solution.

**Comment by friendly** [comment]
Would something here help:
http://d3export.housegordon.org/
[FileSaver.js] (http://eligrey.com/demos/FileSaver.js/)

I'm interested in this question because John Fox recently added DiagrammeR as a renderer for path diagrams in the R-Forge version of the [sem package](https://r-forge.r-project.org/projects/sem/), but as yet there is no way implemented to even save the svg file.

**Comment by timelyportfolio** [comment]
@friendly do you want to save from the browser once the DiagrammeR has been rendered, or would you just like the SVG in `R`?  If the second, then there is [`exportSVG`](https://github.com/rich-iannone/DiagrammeR/blob/master/R/graphviz_export.R) which returns the rendered SVG.

I use this quite a bit even when including directly in HTML, since `viz.js` is such a big/heavy (>2mb) dependency.

I'm happy to provide more examples if you would like.

*On a side note, thanks @friendly for all your wonderful work.*

**Comment by timelyportfolio** [comment]
@friendly, using the example from `?pathDiagram`, I put this together quickly as an example.


```r
# get newest sem
# install.packages("sem",repos="http://R-Forge.R-project.org")

# get newest DiagrammeR
# install.packages("rich-iannone/DiagrammeR")

## example from ?pathDiagram from the sem package

# The Duncan, Haller, and Portes Peer-Influences Model

R.DHP <- readMoments(diag=FALSE, names=c('ROccAsp', 'REdAsp', 'FOccAsp', 
                                         'FEdAsp', 'RParAsp', 'RIQ', 'RSES', 'FSES', 'FIQ', 'FParAsp'))
.6247                                                              
.3269  .3669                                                        
.4216  .3275  .6404                                      
.2137  .2742  .1124  .0839                                
.4105  .4043  .2903  .2598  .1839                          
.3240  .4047  .3054  .2786  .0489  .2220                    
.2930  .2407  .4105  .3607  .0186  .1861  .2707              
.2995  .2863  .5191  .5007  .0782  .3355  .2302  .2950        
.0760  .0702  .2784  .1988  .1147  .1021  .0931 -.0438  .2087  

model.dhp <- specifyModel()
RParAsp  -> RGenAsp, gam11,  NA
RIQ      -> RGenAsp, gam12,  NA
RSES     -> RGenAsp, gam13,  NA
FSES     -> RGenAsp, gam14,  NA
RSES     -> FGenAsp, gam23,  NA
FSES     -> FGenAsp, gam24,  NA
FIQ      -> FGenAsp, gam25,  NA
FParAsp  -> FGenAsp, gam26,  NA
FGenAsp  -> RGenAsp, beta12, NA
RGenAsp  -> FGenAsp, beta21, NA
RGenAsp  -> ROccAsp,  NA,       1
RGenAsp  -> REdAsp,  lam21,  NA
FGenAsp  -> FOccAsp,  NA,       1
FGenAsp  -> FEdAsp,  lam42,  NA
RGenAsp <-> RGenAsp, ps11,   NA
FGenAsp <-> FGenAsp, ps22,   NA
RGenAsp <-> FGenAsp, ps12,   NA
ROccAsp <-> ROccAsp, theta1, NA
REdAsp  <-> REdAsp,  theta2, NA
FOccAsp <-> FOccAsp, theta3, NA
FEdAsp  <-> FEdAsp,  theta4, NA

sem.dhp <- sem(model.dhp, R.DHP, 329,
               fixed.x=c('RParAsp', 'RIQ', 'RSES', 'FSES', 'FIQ', 'FParAsp'))

path_diag <- capture.output(
  pathDiagram(sem.dhp, min.rank='RIQ, RSES, RParAsp, FParAsp, FSES, FIQ', 
            max.rank='ROccAsp, REdAsp, FEdAsp, FOccAsp')
)

DiagrammeR::exportSVG( grViz( diagram=path_diag ) )

# then to incorporate in HTML we could do something like this
library(htmltools)

browsable(
  tagList(
     tags$h1( "DiagrammeR and sem in HTML" )
     ,tags$div(style="height:100%;width:100%;"
        ,HTML(
          DiagrammeR::exportSVG( grViz( diagram=path_diag ) )
        )
     )
  )
)
```
