### ISSUE TITLE
ER diagrams?

### ISSUE THREAD

**Issue by pe3** [rich-iannone/DiagrammeR#99]
Is it possible to create ER-diagrams with DiagrammeR. If not would it make sense to integrate [JointJS](http://www.jointjs.com/demos/erd).

**Comment by rich-iannone** [comment]
Seems like a natural fit and there are examples of DOT code for this purpose. I'll take a look at JointJS and see about getting its output transformed into DOT. If you make any progress on this, do let me know.

**Comment by timelyportfolio** [comment]
Not a license expert, so posting for those that understand.  See [JointJS license](http://www.jointjs.com/license).
